#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.headless.design.library.dto.v1_0.StyleBook
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Design.Library)
osgi.jaxrs.resource=true