apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
    labels:
        component: backup-create-platform
    name: backup-create-cluster-workflow-template
spec:
    entrypoint: main
    podGC:
        {{- .Values.argo.workflowSpec.podGC | toYaml | nindent 8 }}
    serviceAccountName: backup-create-service-account
    templates:
        -   inputs:
                parameters:
                    -   name: environment-id
                    -   name: project-id
            name: create-backup
            outputs:
                parameters:
                    -   name: backup-name
                        valueFrom:
                            jsonPath: "{.metadata.name}"
            resource:
                action: create
                manifest: |-
                    apiVersion: backup.liferay.cloud/v1alpha1
                    kind: LiferayBackup
                    metadata:
                        generateName: "liferay-{{ "{{" }}inputs.parameters.project-id}}-{{ "{{" }}inputs.parameters.environment-id}}-"
                        namespace: {{ "{{" }}workflow.namespace}}
                    spec:
                        databaseSnapshot:
                            databaseInstanceLookup:
                                matchLabels:
                                    active: "true"
                                    app: liferay
                                    environment-id: {{ "{{" }}inputs.parameters.environment-id}}
                                    project-id: {{ "{{" }}inputs.parameters.project-id}}
                                    should-back-up: "true"
                        documentLibrary:
                            destination:
                                gcs:
                                    bucketLookup:
                                        matchLabels:
                                            app: liferay
                                            environment-id: {{ "{{" }}inputs.parameters.environment-id}}
                                            is-backup-vault: "true"
                                            project-id: {{ "{{" }}inputs.parameters.project-id}}
                                type: gcs
                            source:
                                gcs:
                                    bucketLookup:
                                        matchLabels:
                                            active: "true"
                                            app: liferay
                                            environment-id: {{ "{{" }}inputs.parameters.environment-id}}
                                            project-id: {{ "{{" }}inputs.parameters.project-id}}
                                            should-back-up: "true"
                                type: gcs
        -   name: get-project-id-and-environment-id
            outputs:
                parameters:
                    -   name: environment-id
                        valueFrom:
                            path: /tmp/environment-id.txt
                    -   name: project-id
                        valueFrom:
                            path: /tmp/project-id.txt
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- tpl (.Files.Get "scripts/get-project-id-and-environment-id.sh") . | nindent 20 }}
        -   name: main
            steps:
                -   -   name: get-project-id-and-environment-id
                        template: get-project-id-and-environment-id
                -   -   arguments:
                            parameters:
                                -   name: environment-id
                                    value: "{{ "{{" }}steps.get-project-id-and-environment-id.outputs.parameters.environment-id}}"
                                -   name: project-id
                                    value: "{{ "{{" }}steps.get-project-id-and-environment-id.outputs.parameters.project-id}}"
                        name: create-backup
                        template: create-backup
                -   -   arguments:
                            parameters:
                                -   name: backup-name
                                    value: "{{ "{{" }}steps.create-backup.outputs.parameters.backup-name}}"
                        name: wait-for-backup
                        template: wait-for-backup
        -   inputs:
                parameters:
                    -   name: backup-name
            name: wait-for-backup
            script:
                command: [sh]
                image: "{{ .Values.images.helmKubectl.repository }}:{{ .Values.images.helmKubectl.tag }}"
                resources:
                    {{- .Values.resources.default | toYaml | nindent 20 }}
                source: |-
                    {{- tpl (.Files.Get "scripts/wait-for-backup.sh") . | nindent 20 }}
    ttlStrategy:
        {{- .Values.argo.workflowSpec.ttlStrategy | toYaml | nindent 8 }}