resource "kubernetes_manifest" "argocd_gateway" {
	count=var.argocd_domain_config.hostname != null ? 1 : 0
	depends_on=[kubernetes_manifest.argocd_server_tls_external_secret]
	manifest={
		apiVersion="gateway.networking.k8s.io/v1"
		kind="Gateway"
		metadata={
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"=local.argocd_gateway_name
				})
			name=local.argocd_gateway_name
			namespace=var.argocd_namespace
		}
		spec={
			gatewayClassName=local.argocd_gateway_class_name
			listeners=concat(
				[
					{
						allowedRoutes={
							namespaces={
								from="Same"
							}
						}
						hostname=var.argocd_domain_config.hostname
						name="http"
						port=80
						protocol="HTTP"
					},
				],
				local.argocd_tls_enabled ? [
					{
						allowedRoutes={
							namespaces={
								from="Same"
							}
						}
						hostname=var.argocd_domain_config.hostname
						name="https"
						port=443
						protocol="HTTPS"
						tls={
							certificateRefs=[{name=local.argocd_tls_secret_name}]
							mode="Terminate"
						}
					},
				] : [])
		}
	}
}
resource "kubernetes_manifest" "argocd_gateway_class" {
	manifest={
		apiVersion="gateway.networking.k8s.io/v1"
		kind="GatewayClass"
		metadata={
			name=local.argocd_gateway_class_name
		}
		spec={
			controllerName="gateway.envoyproxy.io/gatewayclass-controller"
			parametersRef={
				group="gateway.envoyproxy.io"
				kind="EnvoyProxy"
				name="${local.argocd_gateway_name}-proxy-config"
				namespace=var.gateway_namespace
			}
		}
	}
}
resource "kubernetes_manifest" "argocd_gateway_proxy_config" {
	manifest={
		apiVersion="gateway.envoyproxy.io/v1alpha1"
		kind="EnvoyProxy"
		metadata={
			labels=local.common_labels
			name="${local.argocd_gateway_name}-proxy-config"
			namespace=var.gateway_namespace
		}
		spec={
			provider={
				kubernetes={
					envoyDeployment={
						pod={
							annotations={
								"eks.amazonaws.com/role-arn"=local.envoy_proxy_role_arn
							}
						}
						replicas=2
					}
					envoyService={
						annotations={
							"service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol"="TCP"
							"service.beta.kubernetes.io/aws-load-balancer-manage-backend-security-group-rules"="false"
							"service.beta.kubernetes.io/aws-load-balancer-scheme"="internet-facing"
							"service.beta.kubernetes.io/aws-load-balancer-type"="nlb"
							"service.beta.kubernetes.io/load-balancer-source-ranges"=join(",", local.argocd_source_ranges)
						}
					}
				}
				type="Kubernetes"
			}
		}
	}
}
resource "kubernetes_manifest" "argocd_httproute" {
	count=var.argocd_domain_config.hostname != null ? 1 : 0
	manifest={
		apiVersion="gateway.networking.k8s.io/v1"
		kind="HTTPRoute"
		metadata={
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="argocd-server-route"
				})
			name="argocd-server-route"
			namespace=var.argocd_namespace
		}
		spec={
			hostnames=[var.argocd_domain_config.hostname]
			parentRefs=[
				{
					name=local.argocd_gateway_name
					sectionName=local.argocd_tls_enabled ? "https" : "http"
				},
			]
			rules=[
				{
					backendRefs=[
						{
							name="argocd-server"
							port=80
						},
					]
				},
			]
		}
	}
}
resource "kubernetes_manifest" "argocd_https_redirect" {
	count=local.argocd_tls_enabled ? 1 : 0
	manifest={
		apiVersion="gateway.networking.k8s.io/v1"
		kind="HTTPRoute"
		metadata={
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="argocd-redirect-route"
				})
			name="argocd-redirect-route"
			namespace=var.argocd_namespace
		}
		spec={
			hostnames=[var.argocd_domain_config.hostname]
			parentRefs=[
				{
					name=local.argocd_gateway_name
					sectionName="http"
				},
			]
			rules=[
				{
					filters=[
						{
							requestRedirect={
								scheme="https"
								statusCode=301
							}
							type="RequestRedirect"
						},
					]
				},
			]
		}
	}
}
resource "kubernetes_manifest" "argocd_server_tls_external_secret" {
	count=local.argocd_tls_external_secret_name != null ? 1 : 0
	depends_on=[kubernetes_manifest.secret_store]
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="external-secrets.io/v1"
		kind="ExternalSecret"
		metadata={
			labels=local.common_labels
			name=local.argocd_tls_secret_name
			namespace=var.argocd_namespace
		}
		spec={
			dataFrom=[
				{
					extract={
						decodingStrategy="Auto"
						key=local.argocd_tls_external_secret_name
					}
				},
			]
			refreshInterval="1h0m0s"
			secretStoreRef={
				kind="ClusterSecretStore"
				name=local.secret_store_name
			}
			target={
				creationPolicy="Owner"
				name=local.argocd_tls_secret_name
				template={
					metadata={
						labels=merge(
							local.common_labels,
							{
								"app.kubernetes.io/name"=local.argocd_tls_secret_name
							})
					}
					type="kubernetes.io/tls"
				}
			}
		}
	}
}