#
# Application
#

liferay.marketplace.analytics.auth.email.address=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_EMAIL_ADDRESS}
liferay.marketplace.analytics.auth.password=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_PASSWORD}
liferay.marketplace.analytics.auth.url=${LIFERAY_MARKETPLACE_ANALYTICS_AUTH_URL}
liferay.marketplace.analytics.internal.auth.email.address=${LIFERAY_MARKETPLACE_ANALYTICS_INTERNAL_AUTH_EMAIL_ADDRESS:}
liferay.marketplace.analytics.internal.auth.password=${LIFERAY_MARKETPLACE_ANALYTICS_INTERNAL_AUTH_PASSWORD:}
liferay.marketplace.analytics.internal.auth.url=${LIFERAY_MARKETPLACE_ANALYTICS_INTERNAL_AUTH_URL:}
liferay.marketplace.console.auth.email.address=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_EMAIL_ADDRESS}
liferay.marketplace.console.auth.password=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_PASSWORD}
liferay.marketplace.console.auth.url=${LIFERAY_MARKETPLACE_CONSOLE_AUTH_URL}
liferay.marketplace.console.cluster=${LIFERAY_MARKETPLACE_CONSOLE_CLUSTER}
liferay.marketplace.console.project.prefix=${LIFERAY_MARKETPLACE_CONSOLE_PROJECT_PREFIX}
liferay.marketplace.console.project.uid=${LIFERAY_MARKETPLACE_CONSOLE_PROJECT_UID}
liferay.marketplace.console.ssa.cluster=${LIFERAY_MARKETPLACE_CONSOLE_SSA_CLUSTER}
liferay.marketplace.console.ssa.project.prefix=${LIFERAY_MARKETPLACE_CONSOLE_SSA_PROJECT_PREFIX}
liferay.marketplace.console.ssa.project.uid=${LIFERAY_MARKETPLACE_CONSOLE_SSA_PROJECT_UID}
liferay.marketplace.dxp.auth.client.id=${LIFERAY_MARKETPLACE_DXP_AUTH_CLIENT_ID}
liferay.marketplace.dxp.auth.client.secret=${LIFERAY_MARKETPLACE_DXP_AUTH_CLIENT_SECRET}
liferay.marketplace.koroneiki.auth.token=${LIFERAY_MARKETPLACE_KORONEIKI_AUTH_TOKEN}
liferay.marketplace.koroneiki.auth.url=${LIFERAY_MARKETPLACE_KORONEIKI_AUTH_URL}
liferay.marketplace.koroneiki.product.keys=${LIFERAY_MARKETPLACE_KORONEIKI_PRODUCT_KEYS:}
liferay.marketplace.pubsub.gcp.disabled.topic.names=${LIFERAY_MARKETPLACE_PUBSUB_GCP_DISABLED_TOPICS:}
liferay.marketplace.pubsub.gcp.project.id=${LIFERAY_MARKETPLACE_PUBSUB_GCP_PROJECT_ID:}
liferay.marketplace.pubsub.gcp.service.account.key=${LIFERAY_MARKETPLACE_PUBSUB_GCP_SERVICE_ACCOUNT_KEY:}
liferay.marketplace.pubsub.topic.prefix=${LIFERAY_MARKETPLACE_PUBSUB_TOPIC_PREFIX:marketplace_}
liferay.marketplace.salesforce.gcf.audience=${LIFERAY_MARKETPLACE_SALESFORCE_GCF_AUDIENCE}
liferay.marketplace.salesforce.gcf.base.url=${LIFERAY_MARKETPLACE_SALESFORCE_GCF_BASE_URL}
liferay.marketplace.salesforce.gcf.service.account.key=${LIFERAY_MARKETPLACE_SALESFORCE_GCF_SERVICE_ACCOUNT_KEY}
liferay.marketplace.trial.admin.email.address=${LIFERAY_MARKETPLACE_TRIAL_ADMIN_EMAIL_ADDRESS}
liferay.marketplace.trial.dxp.domain=${LIFERAY_MARKETPLACE_TRIAL_DXP_DOMAIN}
liferay.marketplace.trial.ssa.dxp.domain=${LIFERAY_MARKETPLACE_TRIAL_SSA_DXP_DOMAIN}

logging.level.com.liferay.osb.koroneiki.phloem.rest.client.http.HttpInvoker=ERROR
logging.level.com.liferay.osb.provisioning.marketplace.rest.client.http.HttpInvoker=ERROR

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-marketplace-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_MARKETPLACE_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    external-ai-hub,\
    external-provisioning,\
    external-ssa,\
    external-trial,\
    liferay-marketplace-etc-cron-oahs,\
    liferay-marketplace-etc-spring-boot-oahs,\
    liferay-marketplace-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081