/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.type.virtual.order.model.impl;

import com.liferay.commerce.product.type.virtual.order.model.CommerceVirtualOrderItemFileEntry;
import com.liferay.commerce.product.type.virtual.order.model.CommerceVirtualOrderItemFileEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceVirtualOrderItemFileEntry service. Represents a row in the &quot;CVirtualOrderItemFileEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceVirtualOrderItemFileEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceVirtualOrderItemFileEntryImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceVirtualOrderItemFileEntryImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceVirtualOrderItemFileEntryModelImpl
	extends BaseModelImpl<CommerceVirtualOrderItemFileEntry>
	implements CommerceVirtualOrderItemFileEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce virtual order item file entry model instance should use the <code>CommerceVirtualOrderItemFileEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "CVirtualOrderItemFileEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"cVirtualOrderItemFileEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"commerceVirtualOrderItemId", Types.BIGINT},
		{"fileEntryId", Types.BIGINT}, {"url", Types.VARCHAR},
		{"usages", Types.INTEGER}, {"version", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cVirtualOrderItemFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceVirtualOrderItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usages", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CVirtualOrderItemFileEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,cVirtualOrderItemFileEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceVirtualOrderItemId LONG,fileEntryId LONG,url VARCHAR(255) null,usages INTEGER,version VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CVirtualOrderItemFileEntry";

	public static final String ENTITY_ALIAS =
		"commerceVirtualOrderItemFileEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceVirtualOrderItemFileEntry.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CVirtualOrderItemFileEntry.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEVIRTUALORDERITEMID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommerceVirtualOrderItemFileEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceVirtualOrderItemFileEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceVirtualOrderItemFileEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceVirtualOrderItemFileEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceVirtualOrderItemFileEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceVirtualOrderItemFileEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceVirtualOrderItemFileEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommerceVirtualOrderItemFileEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceVirtualOrderItemFileEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceVirtualOrderItemFileEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceVirtualOrderItemFileEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceVirtualOrderItemFileEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<CommerceVirtualOrderItemFileEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion",
				CommerceVirtualOrderItemFileEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"uuid", CommerceVirtualOrderItemFileEntry::getUuid);
			attributeGetterFunctions.put(
				"commerceVirtualOrderItemFileEntryId",
				CommerceVirtualOrderItemFileEntry::
					getCommerceVirtualOrderItemFileEntryId);
			attributeGetterFunctions.put(
				"groupId", CommerceVirtualOrderItemFileEntry::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CommerceVirtualOrderItemFileEntry::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CommerceVirtualOrderItemFileEntry::getUserId);
			attributeGetterFunctions.put(
				"userName", CommerceVirtualOrderItemFileEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", CommerceVirtualOrderItemFileEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate",
				CommerceVirtualOrderItemFileEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"commerceVirtualOrderItemId",
				CommerceVirtualOrderItemFileEntry::
					getCommerceVirtualOrderItemId);
			attributeGetterFunctions.put(
				"fileEntryId",
				CommerceVirtualOrderItemFileEntry::getFileEntryId);
			attributeGetterFunctions.put(
				"url", CommerceVirtualOrderItemFileEntry::getUrl);
			attributeGetterFunctions.put(
				"usages", CommerceVirtualOrderItemFileEntry::getUsages);
			attributeGetterFunctions.put(
				"version", CommerceVirtualOrderItemFileEntry::getVersion);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CommerceVirtualOrderItemFileEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CommerceVirtualOrderItemFileEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String,
						 BiConsumer<CommerceVirtualOrderItemFileEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, String>)
					CommerceVirtualOrderItemFileEntry::setUuid);
			attributeSetterBiConsumers.put(
				"commerceVirtualOrderItemFileEntryId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::
						setCommerceVirtualOrderItemFileEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, String>)
					CommerceVirtualOrderItemFileEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Date>)
					CommerceVirtualOrderItemFileEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Date>)
					CommerceVirtualOrderItemFileEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"commerceVirtualOrderItemId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::
						setCommerceVirtualOrderItemId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Long>)
					CommerceVirtualOrderItemFileEntry::setFileEntryId);
			attributeSetterBiConsumers.put(
				"url",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, String>)
					CommerceVirtualOrderItemFileEntry::setUrl);
			attributeSetterBiConsumers.put(
				"usages",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, Integer>)
					CommerceVirtualOrderItemFileEntry::setUsages);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<CommerceVirtualOrderItemFileEntry, String>)
					CommerceVirtualOrderItemFileEntry::setVersion);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCommerceVirtualOrderItemFileEntryId() {
		return _commerceVirtualOrderItemFileEntryId;
	}

	@Override
	public void setCommerceVirtualOrderItemFileEntryId(
		long commerceVirtualOrderItemFileEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceVirtualOrderItemFileEntryId =
			commerceVirtualOrderItemFileEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceVirtualOrderItemId() {
		return _commerceVirtualOrderItemId;
	}

	@Override
	public void setCommerceVirtualOrderItemId(long commerceVirtualOrderItemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceVirtualOrderItemId = commerceVirtualOrderItemId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceVirtualOrderItemId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceVirtualOrderItemId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFileEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("fileEntryId"));
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public int getUsages() {
		return _usages;
	}

	@Override
	public void setUsages(int usages) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usages = usages;
	}

	@JSON
	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CommerceVirtualOrderItemFileEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceVirtualOrderItemFileEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceVirtualOrderItemFileEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceVirtualOrderItemFileEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceVirtualOrderItemFileEntryImpl
			commerceVirtualOrderItemFileEntryImpl =
				new CommerceVirtualOrderItemFileEntryImpl();

		commerceVirtualOrderItemFileEntryImpl.setMvccVersion(getMvccVersion());
		commerceVirtualOrderItemFileEntryImpl.setUuid(getUuid());
		commerceVirtualOrderItemFileEntryImpl.
			setCommerceVirtualOrderItemFileEntryId(
				getCommerceVirtualOrderItemFileEntryId());
		commerceVirtualOrderItemFileEntryImpl.setGroupId(getGroupId());
		commerceVirtualOrderItemFileEntryImpl.setCompanyId(getCompanyId());
		commerceVirtualOrderItemFileEntryImpl.setUserId(getUserId());
		commerceVirtualOrderItemFileEntryImpl.setUserName(getUserName());
		commerceVirtualOrderItemFileEntryImpl.setCreateDate(getCreateDate());
		commerceVirtualOrderItemFileEntryImpl.setModifiedDate(
			getModifiedDate());
		commerceVirtualOrderItemFileEntryImpl.setCommerceVirtualOrderItemId(
			getCommerceVirtualOrderItemId());
		commerceVirtualOrderItemFileEntryImpl.setFileEntryId(getFileEntryId());
		commerceVirtualOrderItemFileEntryImpl.setUrl(getUrl());
		commerceVirtualOrderItemFileEntryImpl.setUsages(getUsages());
		commerceVirtualOrderItemFileEntryImpl.setVersion(getVersion());

		commerceVirtualOrderItemFileEntryImpl.resetOriginalValues();

		return commerceVirtualOrderItemFileEntryImpl;
	}

	@Override
	public CommerceVirtualOrderItemFileEntry cloneWithOriginalValues() {
		CommerceVirtualOrderItemFileEntryImpl
			commerceVirtualOrderItemFileEntryImpl =
				new CommerceVirtualOrderItemFileEntryImpl();

		commerceVirtualOrderItemFileEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceVirtualOrderItemFileEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		commerceVirtualOrderItemFileEntryImpl.
			setCommerceVirtualOrderItemFileEntryId(
				this.<Long>getColumnOriginalValue(
					"cVirtualOrderItemFileEntryId"));
		commerceVirtualOrderItemFileEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		commerceVirtualOrderItemFileEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceVirtualOrderItemFileEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceVirtualOrderItemFileEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceVirtualOrderItemFileEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceVirtualOrderItemFileEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceVirtualOrderItemFileEntryImpl.setCommerceVirtualOrderItemId(
			this.<Long>getColumnOriginalValue("commerceVirtualOrderItemId"));
		commerceVirtualOrderItemFileEntryImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		commerceVirtualOrderItemFileEntryImpl.setUrl(
			this.<String>getColumnOriginalValue("url"));
		commerceVirtualOrderItemFileEntryImpl.setUsages(
			this.<Integer>getColumnOriginalValue("usages"));
		commerceVirtualOrderItemFileEntryImpl.setVersion(
			this.<String>getColumnOriginalValue("version"));

		return commerceVirtualOrderItemFileEntryImpl;
	}

	@Override
	public int compareTo(
		CommerceVirtualOrderItemFileEntry commerceVirtualOrderItemFileEntry) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commerceVirtualOrderItemFileEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceVirtualOrderItemFileEntry)) {
			return false;
		}

		CommerceVirtualOrderItemFileEntry commerceVirtualOrderItemFileEntry =
			(CommerceVirtualOrderItemFileEntry)object;

		long primaryKey = commerceVirtualOrderItemFileEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceVirtualOrderItemFileEntry> toCacheModel() {
		CommerceVirtualOrderItemFileEntryCacheModel
			commerceVirtualOrderItemFileEntryCacheModel =
				new CommerceVirtualOrderItemFileEntryCacheModel();

		commerceVirtualOrderItemFileEntryCacheModel.mvccVersion =
			getMvccVersion();

		commerceVirtualOrderItemFileEntryCacheModel.uuid = getUuid();

		String uuid = commerceVirtualOrderItemFileEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commerceVirtualOrderItemFileEntryCacheModel.uuid = null;
		}

		commerceVirtualOrderItemFileEntryCacheModel.
			commerceVirtualOrderItemFileEntryId =
				getCommerceVirtualOrderItemFileEntryId();

		commerceVirtualOrderItemFileEntryCacheModel.groupId = getGroupId();

		commerceVirtualOrderItemFileEntryCacheModel.companyId = getCompanyId();

		commerceVirtualOrderItemFileEntryCacheModel.userId = getUserId();

		commerceVirtualOrderItemFileEntryCacheModel.userName = getUserName();

		String userName = commerceVirtualOrderItemFileEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceVirtualOrderItemFileEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceVirtualOrderItemFileEntryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceVirtualOrderItemFileEntryCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceVirtualOrderItemFileEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceVirtualOrderItemFileEntryCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		commerceVirtualOrderItemFileEntryCacheModel.commerceVirtualOrderItemId =
			getCommerceVirtualOrderItemId();

		commerceVirtualOrderItemFileEntryCacheModel.fileEntryId =
			getFileEntryId();

		commerceVirtualOrderItemFileEntryCacheModel.url = getUrl();

		String url = commerceVirtualOrderItemFileEntryCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			commerceVirtualOrderItemFileEntryCacheModel.url = null;
		}

		commerceVirtualOrderItemFileEntryCacheModel.usages = getUsages();

		commerceVirtualOrderItemFileEntryCacheModel.version = getVersion();

		String version = commerceVirtualOrderItemFileEntryCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			commerceVirtualOrderItemFileEntryCacheModel.version = null;
		}

		return commerceVirtualOrderItemFileEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry
				<String, Function<CommerceVirtualOrderItemFileEntry, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceVirtualOrderItemFileEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceVirtualOrderItemFileEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceVirtualOrderItemFileEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CommerceVirtualOrderItemFileEntry.class,
						ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _commerceVirtualOrderItemFileEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceVirtualOrderItemId;
	private long _fileEntryId;
	private String _url;
	private int _usages;
	private String _version;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CommerceVirtualOrderItemFileEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceVirtualOrderItemFileEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"cVirtualOrderItemFileEntryId",
			_commerceVirtualOrderItemFileEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"commerceVirtualOrderItemId", _commerceVirtualOrderItemId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("usages", _usages);
		_columnOriginalValues.put("version", _version);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"cVirtualOrderItemFileEntryId",
			"commerceVirtualOrderItemFileEntryId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("cVirtualOrderItemFileEntryId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("commerceVirtualOrderItemId", 512L);

		columnBitmasks.put("fileEntryId", 1024L);

		columnBitmasks.put("url", 2048L);

		columnBitmasks.put("usages", 4096L);

		columnBitmasks.put("version", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceVirtualOrderItemFileEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-249294698