/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPConfigurationList;
import com.liferay.commerce.product.model.CPConfigurationListModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPConfigurationList service. Represents a row in the &quot;CPConfigurationList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPConfigurationListModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPConfigurationListImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPConfigurationListImpl
 * @generated
 */
@JSON(strict = true)
public class CPConfigurationListModelImpl
	extends BaseModelImpl<CPConfigurationList>
	implements CPConfigurationListModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp configuration list model instance should use the <code>CPConfigurationList</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPConfigurationList";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"CPConfigurationListId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"parentCPConfigurationListId", Types.BIGINT},
		{"master", Types.BOOLEAN}, {"name", Types.VARCHAR},
		{"priority", Types.DOUBLE}, {"displayDate", Types.TIMESTAMP},
		{"expirationDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPConfigurationListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentCPConfigurationListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("master", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("displayDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPConfigurationList (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,CPConfigurationListId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentCPConfigurationListId LONG,master BOOLEAN,name VARCHAR(75) null,priority DOUBLE,displayDate DATE null,expirationDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (CPConfigurationListId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table CPConfigurationList";

	public static final String ENTITY_ALIAS = "cpConfigurationList";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpConfigurationList.createDate DESC, cpConfigurationList.displayDate DESC, cpConfigurationList.priority DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPConfigurationList.createDate DESC, CPConfigurationList.displayDate DESC, CPConfigurationList.priority DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DISPLAYDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MASTER_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTCPCONFIGURATIONLISTID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITY_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CPConfigurationListModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPConfigurationListId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPConfigurationListId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPConfigurationListId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPConfigurationList.class;
	}

	@Override
	public String getModelClassName() {
		return CPConfigurationList.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPConfigurationList, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPConfigurationList, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationList, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CPConfigurationList)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPConfigurationList, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPConfigurationList, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPConfigurationList)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPConfigurationList, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPConfigurationList, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CPConfigurationList, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CPConfigurationList, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CPConfigurationList, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CPConfigurationList::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", CPConfigurationList::getCtCollectionId);
			attributeGetterFunctions.put("uuid", CPConfigurationList::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				CPConfigurationList::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"CPConfigurationListId",
				CPConfigurationList::getCPConfigurationListId);
			attributeGetterFunctions.put(
				"groupId", CPConfigurationList::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CPConfigurationList::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CPConfigurationList::getUserId);
			attributeGetterFunctions.put(
				"userName", CPConfigurationList::getUserName);
			attributeGetterFunctions.put(
				"createDate", CPConfigurationList::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CPConfigurationList::getModifiedDate);
			attributeGetterFunctions.put(
				"parentCPConfigurationListId",
				CPConfigurationList::getParentCPConfigurationListId);
			attributeGetterFunctions.put(
				"master", CPConfigurationList::getMaster);
			attributeGetterFunctions.put("name", CPConfigurationList::getName);
			attributeGetterFunctions.put(
				"priority", CPConfigurationList::getPriority);
			attributeGetterFunctions.put(
				"displayDate", CPConfigurationList::getDisplayDate);
			attributeGetterFunctions.put(
				"expirationDate", CPConfigurationList::getExpirationDate);
			attributeGetterFunctions.put(
				"lastPublishDate", CPConfigurationList::getLastPublishDate);
			attributeGetterFunctions.put(
				"status", CPConfigurationList::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", CPConfigurationList::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", CPConfigurationList::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", CPConfigurationList::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CPConfigurationList, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CPConfigurationList, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CPConfigurationList, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CPConfigurationList, String>)
					CPConfigurationList::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<CPConfigurationList, String>)
					CPConfigurationList::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"CPConfigurationListId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setCPConfigurationListId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CPConfigurationList, String>)
					CPConfigurationList::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setModifiedDate);
			attributeSetterBiConsumers.put(
				"parentCPConfigurationListId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setParentCPConfigurationListId);
			attributeSetterBiConsumers.put(
				"master",
				(BiConsumer<CPConfigurationList, Boolean>)
					CPConfigurationList::setMaster);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<CPConfigurationList, String>)
					CPConfigurationList::setName);
			attributeSetterBiConsumers.put(
				"priority",
				(BiConsumer<CPConfigurationList, Double>)
					CPConfigurationList::setPriority);
			attributeSetterBiConsumers.put(
				"displayDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setDisplayDate);
			attributeSetterBiConsumers.put(
				"expirationDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setExpirationDate);
			attributeSetterBiConsumers.put(
				"lastPublishDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setLastPublishDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<CPConfigurationList, Integer>)
					CPConfigurationList::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<CPConfigurationList, Long>)
					CPConfigurationList::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<CPConfigurationList, String>)
					CPConfigurationList::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<CPConfigurationList, Date>)
					CPConfigurationList::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getCPConfigurationListId() {
		return _CPConfigurationListId;
	}

	@Override
	public void setCPConfigurationListId(long CPConfigurationListId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPConfigurationListId = CPConfigurationListId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getParentCPConfigurationListId() {
		return _parentCPConfigurationListId;
	}

	@Override
	public void setParentCPConfigurationListId(
		long parentCPConfigurationListId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentCPConfigurationListId = parentCPConfigurationListId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentCPConfigurationListId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentCPConfigurationListId"));
	}

	@JSON
	@Override
	public boolean getMaster() {
		return _master;
	}

	@JSON
	@Override
	public boolean isMaster() {
		return _master;
	}

	@Override
	public void setMaster(boolean master) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_master = master;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalMaster() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("master"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public double getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(double priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public Date getDisplayDate() {
		return _displayDate;
	}

	@Override
	public void setDisplayDate(Date displayDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_displayDate = displayDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDisplayDate() {
		return getColumnOriginalValue("displayDate");
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CPConfigurationList.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPConfigurationList.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPConfigurationList toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPConfigurationList>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPConfigurationListImpl cpConfigurationListImpl =
			new CPConfigurationListImpl();

		cpConfigurationListImpl.setMvccVersion(getMvccVersion());
		cpConfigurationListImpl.setCtCollectionId(getCtCollectionId());
		cpConfigurationListImpl.setUuid(getUuid());
		cpConfigurationListImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		cpConfigurationListImpl.setCPConfigurationListId(
			getCPConfigurationListId());
		cpConfigurationListImpl.setGroupId(getGroupId());
		cpConfigurationListImpl.setCompanyId(getCompanyId());
		cpConfigurationListImpl.setUserId(getUserId());
		cpConfigurationListImpl.setUserName(getUserName());
		cpConfigurationListImpl.setCreateDate(getCreateDate());
		cpConfigurationListImpl.setModifiedDate(getModifiedDate());
		cpConfigurationListImpl.setParentCPConfigurationListId(
			getParentCPConfigurationListId());
		cpConfigurationListImpl.setMaster(isMaster());
		cpConfigurationListImpl.setName(getName());
		cpConfigurationListImpl.setPriority(getPriority());
		cpConfigurationListImpl.setDisplayDate(getDisplayDate());
		cpConfigurationListImpl.setExpirationDate(getExpirationDate());
		cpConfigurationListImpl.setLastPublishDate(getLastPublishDate());
		cpConfigurationListImpl.setStatus(getStatus());
		cpConfigurationListImpl.setStatusByUserId(getStatusByUserId());
		cpConfigurationListImpl.setStatusByUserName(getStatusByUserName());
		cpConfigurationListImpl.setStatusDate(getStatusDate());

		cpConfigurationListImpl.resetOriginalValues();

		return cpConfigurationListImpl;
	}

	@Override
	public CPConfigurationList cloneWithOriginalValues() {
		CPConfigurationListImpl cpConfigurationListImpl =
			new CPConfigurationListImpl();

		cpConfigurationListImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cpConfigurationListImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		cpConfigurationListImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		cpConfigurationListImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		cpConfigurationListImpl.setCPConfigurationListId(
			this.<Long>getColumnOriginalValue("CPConfigurationListId"));
		cpConfigurationListImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		cpConfigurationListImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cpConfigurationListImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cpConfigurationListImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cpConfigurationListImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		cpConfigurationListImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		cpConfigurationListImpl.setParentCPConfigurationListId(
			this.<Long>getColumnOriginalValue("parentCPConfigurationListId"));
		cpConfigurationListImpl.setMaster(
			this.<Boolean>getColumnOriginalValue("master"));
		cpConfigurationListImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		cpConfigurationListImpl.setPriority(
			this.<Double>getColumnOriginalValue("priority"));
		cpConfigurationListImpl.setDisplayDate(
			this.<Date>getColumnOriginalValue("displayDate"));
		cpConfigurationListImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));
		cpConfigurationListImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		cpConfigurationListImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		cpConfigurationListImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		cpConfigurationListImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		cpConfigurationListImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return cpConfigurationListImpl;
	}

	@Override
	public int compareTo(CPConfigurationList cpConfigurationList) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), cpConfigurationList.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(
			getDisplayDate(), cpConfigurationList.getDisplayDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		if (getPriority() < cpConfigurationList.getPriority()) {
			value = -1;
		}
		else if (getPriority() > cpConfigurationList.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPConfigurationList)) {
			return false;
		}

		CPConfigurationList cpConfigurationList = (CPConfigurationList)object;

		long primaryKey = cpConfigurationList.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPConfigurationList> toCacheModel() {
		CPConfigurationListCacheModel cpConfigurationListCacheModel =
			new CPConfigurationListCacheModel();

		cpConfigurationListCacheModel.mvccVersion = getMvccVersion();

		cpConfigurationListCacheModel.ctCollectionId = getCtCollectionId();

		cpConfigurationListCacheModel.uuid = getUuid();

		String uuid = cpConfigurationListCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cpConfigurationListCacheModel.uuid = null;
		}

		cpConfigurationListCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			cpConfigurationListCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			cpConfigurationListCacheModel.externalReferenceCode = null;
		}

		cpConfigurationListCacheModel.CPConfigurationListId =
			getCPConfigurationListId();

		cpConfigurationListCacheModel.groupId = getGroupId();

		cpConfigurationListCacheModel.companyId = getCompanyId();

		cpConfigurationListCacheModel.userId = getUserId();

		cpConfigurationListCacheModel.userName = getUserName();

		String userName = cpConfigurationListCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpConfigurationListCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpConfigurationListCacheModel.createDate = createDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpConfigurationListCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpConfigurationListCacheModel.parentCPConfigurationListId =
			getParentCPConfigurationListId();

		cpConfigurationListCacheModel.master = isMaster();

		cpConfigurationListCacheModel.name = getName();

		String name = cpConfigurationListCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cpConfigurationListCacheModel.name = null;
		}

		cpConfigurationListCacheModel.priority = getPriority();

		Date displayDate = getDisplayDate();

		if (displayDate != null) {
			cpConfigurationListCacheModel.displayDate = displayDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.displayDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			cpConfigurationListCacheModel.expirationDate =
				expirationDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			cpConfigurationListCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		cpConfigurationListCacheModel.status = getStatus();

		cpConfigurationListCacheModel.statusByUserId = getStatusByUserId();

		cpConfigurationListCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName =
			cpConfigurationListCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			cpConfigurationListCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			cpConfigurationListCacheModel.statusDate = statusDate.getTime();
		}
		else {
			cpConfigurationListCacheModel.statusDate = Long.MIN_VALUE;
		}

		return cpConfigurationListCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPConfigurationList, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPConfigurationList, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationList, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CPConfigurationList)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CPConfigurationList>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CPConfigurationList.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _CPConfigurationListId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentCPConfigurationListId;
	private boolean _master;
	private String _name;
	private double _priority;
	private Date _displayDate;
	private Date _expirationDate;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CPConfigurationList, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPConfigurationList)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"CPConfigurationListId", _CPConfigurationListId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"parentCPConfigurationListId", _parentCPConfigurationListId);
		_columnOriginalValues.put("master", _master);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("displayDate", _displayDate);
		_columnOriginalValues.put("expirationDate", _expirationDate);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("CPConfigurationListId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("parentCPConfigurationListId", 2048L);

		columnBitmasks.put("master", 4096L);

		columnBitmasks.put("name", 8192L);

		columnBitmasks.put("priority", 16384L);

		columnBitmasks.put("displayDate", 32768L);

		columnBitmasks.put("expirationDate", 65536L);

		columnBitmasks.put("lastPublishDate", 131072L);

		columnBitmasks.put("status", 262144L);

		columnBitmasks.put("statusByUserId", 524288L);

		columnBitmasks.put("statusByUserName", 1048576L);

		columnBitmasks.put("statusDate", 2097152L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPConfigurationList _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:11556623