/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPConfigurationEntrySetting;
import com.liferay.commerce.product.model.CPConfigurationEntrySettingModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPConfigurationEntrySetting service. Represents a row in the &quot;CPConfigurationEntrySetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPConfigurationEntrySettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPConfigurationEntrySettingImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPConfigurationEntrySettingImpl
 * @generated
 */
@JSON(strict = true)
public class CPConfigurationEntrySettingModelImpl
	extends BaseModelImpl<CPConfigurationEntrySetting>
	implements CPConfigurationEntrySettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp configuration entry setting model instance should use the <code>CPConfigurationEntrySetting</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPConfigurationEntrySetting";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR},
		{"CPConfigurationEntrySettingId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"CPConfigurationEntryId", Types.BIGINT}, {"type_", Types.INTEGER},
		{"value", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPConfigurationEntrySettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CPConfigurationEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("value", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPConfigurationEntrySetting (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,CPConfigurationEntrySettingId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,CPConfigurationEntryId LONG,type_ INTEGER,value TEXT null,primary key (CPConfigurationEntrySettingId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table CPConfigurationEntrySetting";

	public static final String ENTITY_ALIAS = "cpConfigurationEntrySetting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpConfigurationEntrySetting.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPConfigurationEntrySetting.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPCONFIGURATIONENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CPConfigurationEntrySettingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPConfigurationEntrySettingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPConfigurationEntrySettingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPConfigurationEntrySettingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPConfigurationEntrySetting.class;
	}

	@Override
	public String getModelClassName() {
		return CPConfigurationEntrySetting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPConfigurationEntrySetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPConfigurationEntrySetting, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationEntrySetting, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CPConfigurationEntrySetting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPConfigurationEntrySetting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPConfigurationEntrySetting, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPConfigurationEntrySetting)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPConfigurationEntrySetting, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPConfigurationEntrySetting, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CPConfigurationEntrySetting, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CPConfigurationEntrySetting, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<CPConfigurationEntrySetting, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CPConfigurationEntrySetting::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId",
				CPConfigurationEntrySetting::getCtCollectionId);
			attributeGetterFunctions.put(
				"uuid", CPConfigurationEntrySetting::getUuid);
			attributeGetterFunctions.put(
				"CPConfigurationEntrySettingId",
				CPConfigurationEntrySetting::getCPConfigurationEntrySettingId);
			attributeGetterFunctions.put(
				"groupId", CPConfigurationEntrySetting::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CPConfigurationEntrySetting::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CPConfigurationEntrySetting::getUserId);
			attributeGetterFunctions.put(
				"userName", CPConfigurationEntrySetting::getUserName);
			attributeGetterFunctions.put(
				"createDate", CPConfigurationEntrySetting::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CPConfigurationEntrySetting::getModifiedDate);
			attributeGetterFunctions.put(
				"CPConfigurationEntryId",
				CPConfigurationEntrySetting::getCPConfigurationEntryId);
			attributeGetterFunctions.put(
				"type", CPConfigurationEntrySetting::getType);
			attributeGetterFunctions.put(
				"value", CPConfigurationEntrySetting::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CPConfigurationEntrySetting, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CPConfigurationEntrySetting, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CPConfigurationEntrySetting, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CPConfigurationEntrySetting, String>)
					CPConfigurationEntrySetting::setUuid);
			attributeSetterBiConsumers.put(
				"CPConfigurationEntrySettingId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::
						setCPConfigurationEntrySettingId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CPConfigurationEntrySetting, String>)
					CPConfigurationEntrySetting::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CPConfigurationEntrySetting, Date>)
					CPConfigurationEntrySetting::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CPConfigurationEntrySetting, Date>)
					CPConfigurationEntrySetting::setModifiedDate);
			attributeSetterBiConsumers.put(
				"CPConfigurationEntryId",
				(BiConsumer<CPConfigurationEntrySetting, Long>)
					CPConfigurationEntrySetting::setCPConfigurationEntryId);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<CPConfigurationEntrySetting, Integer>)
					CPConfigurationEntrySetting::setType);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<CPConfigurationEntrySetting, String>)
					CPConfigurationEntrySetting::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCPConfigurationEntrySettingId() {
		return _CPConfigurationEntrySettingId;
	}

	@Override
	public void setCPConfigurationEntrySettingId(
		long CPConfigurationEntrySettingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPConfigurationEntrySettingId = CPConfigurationEntrySettingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCPConfigurationEntryId() {
		return _CPConfigurationEntryId;
	}

	@Override
	public void setCPConfigurationEntryId(long CPConfigurationEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPConfigurationEntryId = CPConfigurationEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCPConfigurationEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CPConfigurationEntryId"));
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalType() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("type_"));
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CPConfigurationEntrySetting.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPConfigurationEntrySetting.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPConfigurationEntrySetting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPConfigurationEntrySetting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPConfigurationEntrySettingImpl cpConfigurationEntrySettingImpl =
			new CPConfigurationEntrySettingImpl();

		cpConfigurationEntrySettingImpl.setMvccVersion(getMvccVersion());
		cpConfigurationEntrySettingImpl.setCtCollectionId(getCtCollectionId());
		cpConfigurationEntrySettingImpl.setUuid(getUuid());
		cpConfigurationEntrySettingImpl.setCPConfigurationEntrySettingId(
			getCPConfigurationEntrySettingId());
		cpConfigurationEntrySettingImpl.setGroupId(getGroupId());
		cpConfigurationEntrySettingImpl.setCompanyId(getCompanyId());
		cpConfigurationEntrySettingImpl.setUserId(getUserId());
		cpConfigurationEntrySettingImpl.setUserName(getUserName());
		cpConfigurationEntrySettingImpl.setCreateDate(getCreateDate());
		cpConfigurationEntrySettingImpl.setModifiedDate(getModifiedDate());
		cpConfigurationEntrySettingImpl.setCPConfigurationEntryId(
			getCPConfigurationEntryId());
		cpConfigurationEntrySettingImpl.setType(getType());
		cpConfigurationEntrySettingImpl.setValue(getValue());

		cpConfigurationEntrySettingImpl.resetOriginalValues();

		return cpConfigurationEntrySettingImpl;
	}

	@Override
	public CPConfigurationEntrySetting cloneWithOriginalValues() {
		CPConfigurationEntrySettingImpl cpConfigurationEntrySettingImpl =
			new CPConfigurationEntrySettingImpl();

		cpConfigurationEntrySettingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cpConfigurationEntrySettingImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		cpConfigurationEntrySettingImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		cpConfigurationEntrySettingImpl.setCPConfigurationEntrySettingId(
			this.<Long>getColumnOriginalValue("CPConfigurationEntrySettingId"));
		cpConfigurationEntrySettingImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		cpConfigurationEntrySettingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cpConfigurationEntrySettingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cpConfigurationEntrySettingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cpConfigurationEntrySettingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		cpConfigurationEntrySettingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		cpConfigurationEntrySettingImpl.setCPConfigurationEntryId(
			this.<Long>getColumnOriginalValue("CPConfigurationEntryId"));
		cpConfigurationEntrySettingImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));
		cpConfigurationEntrySettingImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return cpConfigurationEntrySettingImpl;
	}

	@Override
	public int compareTo(
		CPConfigurationEntrySetting cpConfigurationEntrySetting) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), cpConfigurationEntrySetting.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPConfigurationEntrySetting)) {
			return false;
		}

		CPConfigurationEntrySetting cpConfigurationEntrySetting =
			(CPConfigurationEntrySetting)object;

		long primaryKey = cpConfigurationEntrySetting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPConfigurationEntrySetting> toCacheModel() {
		CPConfigurationEntrySettingCacheModel
			cpConfigurationEntrySettingCacheModel =
				new CPConfigurationEntrySettingCacheModel();

		cpConfigurationEntrySettingCacheModel.mvccVersion = getMvccVersion();

		cpConfigurationEntrySettingCacheModel.ctCollectionId =
			getCtCollectionId();

		cpConfigurationEntrySettingCacheModel.uuid = getUuid();

		String uuid = cpConfigurationEntrySettingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cpConfigurationEntrySettingCacheModel.uuid = null;
		}

		cpConfigurationEntrySettingCacheModel.CPConfigurationEntrySettingId =
			getCPConfigurationEntrySettingId();

		cpConfigurationEntrySettingCacheModel.groupId = getGroupId();

		cpConfigurationEntrySettingCacheModel.companyId = getCompanyId();

		cpConfigurationEntrySettingCacheModel.userId = getUserId();

		cpConfigurationEntrySettingCacheModel.userName = getUserName();

		String userName = cpConfigurationEntrySettingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpConfigurationEntrySettingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpConfigurationEntrySettingCacheModel.createDate =
				createDate.getTime();
		}
		else {
			cpConfigurationEntrySettingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpConfigurationEntrySettingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			cpConfigurationEntrySettingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpConfigurationEntrySettingCacheModel.CPConfigurationEntryId =
			getCPConfigurationEntryId();

		cpConfigurationEntrySettingCacheModel.type = getType();

		cpConfigurationEntrySettingCacheModel.value = getValue();

		String value = cpConfigurationEntrySettingCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			cpConfigurationEntrySettingCacheModel.value = null;
		}

		return cpConfigurationEntrySettingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPConfigurationEntrySetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPConfigurationEntrySetting, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationEntrySetting, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CPConfigurationEntrySetting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CPConfigurationEntrySetting>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CPConfigurationEntrySetting.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _CPConfigurationEntrySettingId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _CPConfigurationEntryId;
	private int _type;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CPConfigurationEntrySetting, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPConfigurationEntrySetting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"CPConfigurationEntrySettingId", _CPConfigurationEntrySettingId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"CPConfigurationEntryId", _CPConfigurationEntryId);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("CPConfigurationEntrySettingId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("CPConfigurationEntryId", 1024L);

		columnBitmasks.put("type_", 2048L);

		columnBitmasks.put("value", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPConfigurationEntrySetting _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1099375714