/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.model.impl;

import com.liferay.commerce.product.model.CPConfigurationListRel;
import com.liferay.commerce.product.model.CPConfigurationListRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPConfigurationListRel service. Represents a row in the &quot;CPConfigurationListRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPConfigurationListRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPConfigurationListRelImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPConfigurationListRelImpl
 * @generated
 */
@JSON(strict = true)
public class CPConfigurationListRelModelImpl
	extends BaseModelImpl<CPConfigurationListRel>
	implements CPConfigurationListRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp configuration list rel model instance should use the <code>CPConfigurationListRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPConfigurationListRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"CPConfigurationListRelId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"CPConfigurationListId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CPConfigurationListRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CPConfigurationListId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPConfigurationListRel (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,CPConfigurationListRelId LONG not null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,CPConfigurationListId LONG,primary key (CPConfigurationListRelId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table CPConfigurationListRel";

	public static final String ENTITY_ALIAS = "cpConfigurationListRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpConfigurationListRel.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPConfigurationListRel.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPCONFIGURATIONLISTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CPConfigurationListRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPConfigurationListRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPConfigurationListRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPConfigurationListRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPConfigurationListRel.class;
	}

	@Override
	public String getModelClassName() {
		return CPConfigurationListRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPConfigurationListRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPConfigurationListRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationListRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CPConfigurationListRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPConfigurationListRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPConfigurationListRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPConfigurationListRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPConfigurationListRel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPConfigurationListRel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CPConfigurationListRel, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CPConfigurationListRel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CPConfigurationListRel, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CPConfigurationListRel::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", CPConfigurationListRel::getCtCollectionId);
			attributeGetterFunctions.put(
				"CPConfigurationListRelId",
				CPConfigurationListRel::getCPConfigurationListRelId);
			attributeGetterFunctions.put(
				"companyId", CPConfigurationListRel::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CPConfigurationListRel::getUserId);
			attributeGetterFunctions.put(
				"userName", CPConfigurationListRel::getUserName);
			attributeGetterFunctions.put(
				"createDate", CPConfigurationListRel::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CPConfigurationListRel::getModifiedDate);
			attributeGetterFunctions.put(
				"classNameId", CPConfigurationListRel::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", CPConfigurationListRel::getClassPK);
			attributeGetterFunctions.put(
				"CPConfigurationListId",
				CPConfigurationListRel::getCPConfigurationListId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CPConfigurationListRel, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CPConfigurationListRel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CPConfigurationListRel, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"CPConfigurationListRelId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setCPConfigurationListRelId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CPConfigurationListRel, String>)
					CPConfigurationListRel::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CPConfigurationListRel, Date>)
					CPConfigurationListRel::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CPConfigurationListRel, Date>)
					CPConfigurationListRel::setModifiedDate);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setClassPK);
			attributeSetterBiConsumers.put(
				"CPConfigurationListId",
				(BiConsumer<CPConfigurationListRel, Long>)
					CPConfigurationListRel::setCPConfigurationListId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public long getCPConfigurationListRelId() {
		return _CPConfigurationListRelId;
	}

	@Override
	public void setCPConfigurationListRelId(long CPConfigurationListRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPConfigurationListRelId = CPConfigurationListRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@JSON
	@Override
	public long getCPConfigurationListId() {
		return _CPConfigurationListId;
	}

	@Override
	public void setCPConfigurationListId(long CPConfigurationListId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPConfigurationListId = CPConfigurationListId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCPConfigurationListId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CPConfigurationListId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPConfigurationListRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPConfigurationListRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPConfigurationListRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPConfigurationListRelImpl cpConfigurationListRelImpl =
			new CPConfigurationListRelImpl();

		cpConfigurationListRelImpl.setMvccVersion(getMvccVersion());
		cpConfigurationListRelImpl.setCtCollectionId(getCtCollectionId());
		cpConfigurationListRelImpl.setCPConfigurationListRelId(
			getCPConfigurationListRelId());
		cpConfigurationListRelImpl.setCompanyId(getCompanyId());
		cpConfigurationListRelImpl.setUserId(getUserId());
		cpConfigurationListRelImpl.setUserName(getUserName());
		cpConfigurationListRelImpl.setCreateDate(getCreateDate());
		cpConfigurationListRelImpl.setModifiedDate(getModifiedDate());
		cpConfigurationListRelImpl.setClassNameId(getClassNameId());
		cpConfigurationListRelImpl.setClassPK(getClassPK());
		cpConfigurationListRelImpl.setCPConfigurationListId(
			getCPConfigurationListId());

		cpConfigurationListRelImpl.resetOriginalValues();

		return cpConfigurationListRelImpl;
	}

	@Override
	public CPConfigurationListRel cloneWithOriginalValues() {
		CPConfigurationListRelImpl cpConfigurationListRelImpl =
			new CPConfigurationListRelImpl();

		cpConfigurationListRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cpConfigurationListRelImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		cpConfigurationListRelImpl.setCPConfigurationListRelId(
			this.<Long>getColumnOriginalValue("CPConfigurationListRelId"));
		cpConfigurationListRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cpConfigurationListRelImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cpConfigurationListRelImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cpConfigurationListRelImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		cpConfigurationListRelImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		cpConfigurationListRelImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		cpConfigurationListRelImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		cpConfigurationListRelImpl.setCPConfigurationListId(
			this.<Long>getColumnOriginalValue("CPConfigurationListId"));

		return cpConfigurationListRelImpl;
	}

	@Override
	public int compareTo(CPConfigurationListRel cpConfigurationListRel) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), cpConfigurationListRel.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPConfigurationListRel)) {
			return false;
		}

		CPConfigurationListRel cpConfigurationListRel =
			(CPConfigurationListRel)object;

		long primaryKey = cpConfigurationListRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPConfigurationListRel> toCacheModel() {
		CPConfigurationListRelCacheModel cpConfigurationListRelCacheModel =
			new CPConfigurationListRelCacheModel();

		cpConfigurationListRelCacheModel.mvccVersion = getMvccVersion();

		cpConfigurationListRelCacheModel.ctCollectionId = getCtCollectionId();

		cpConfigurationListRelCacheModel.CPConfigurationListRelId =
			getCPConfigurationListRelId();

		cpConfigurationListRelCacheModel.companyId = getCompanyId();

		cpConfigurationListRelCacheModel.userId = getUserId();

		cpConfigurationListRelCacheModel.userName = getUserName();

		String userName = cpConfigurationListRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpConfigurationListRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpConfigurationListRelCacheModel.createDate = createDate.getTime();
		}
		else {
			cpConfigurationListRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpConfigurationListRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			cpConfigurationListRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpConfigurationListRelCacheModel.classNameId = getClassNameId();

		cpConfigurationListRelCacheModel.classPK = getClassPK();

		cpConfigurationListRelCacheModel.CPConfigurationListId =
			getCPConfigurationListId();

		return cpConfigurationListRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPConfigurationListRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPConfigurationListRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPConfigurationListRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CPConfigurationListRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CPConfigurationListRel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CPConfigurationListRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _CPConfigurationListRelId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _CPConfigurationListId;

	public <T> T getColumnValue(String columnName) {
		Function<CPConfigurationListRel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPConfigurationListRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put(
			"CPConfigurationListRelId", _CPConfigurationListRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put(
			"CPConfigurationListId", _CPConfigurationListId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("CPConfigurationListRelId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("classNameId", 256L);

		columnBitmasks.put("classPK", 512L);

		columnBitmasks.put("CPConfigurationListId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPConfigurationListRel _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-797012813