{{- if .Values.enabled -}}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
        helm.sh/resource-policy: keep
    name: {{ .Release.Name }}-db-root-password-generator
    namespace: {{ .Release.Namespace }}
spec:
    allowRepeat: false
    digits: 5
    length: 24
    noUpper: false
    symbolCharacters: -_$@
    symbols: 2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
        helm.sh/resource-policy: keep
    name: {{ .Release.Name }}-db-root-password
    namespace: {{ .Release.Namespace }}
spec:
    dataFrom:
        -   sourceRef:
                generatorRef:
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: Password
                    name: {{ .Release.Name }}-db-root-password-generator
    refreshInterval: 0s
    target:
        creationPolicy: Owner
        deletionPolicy: Retain
        name: {{ .Release.Name }}-db-root-password
{{- end -}}