{{- if .Values.enabled }}
{{- range $secretName := .Values.secretNames }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: {{ $secretName | quote }}
    namespace: {{ $.Release.Namespace }}
spec:
    data:
        -   remoteRef:
                key: {{ $secretName | quote }}
                metadataPolicy: Fetch
            secretKey: metadata
        -   remoteRef:
                key: {{ $secretName | quote }}
            secretKey: data
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ $.Values.secretStoreName | quote }}
    target:
        creationPolicy: {{ $.Values.externalSecretCreationPolicy | quote }}
        deletionPolicy: Retain
        template:
            metadata:
                annotations:
                    eso.validated-namespace: |-
                        {{`
                        {{- $destinationNamespace := index ((.metadata | toString | fromJson).labels | default dict) "esm-app-destination-namespace" -}}
                        {{- $expectedNamespace := `}}{{ $.Release.Namespace | quote }}{{` -}}

                        {{- if eq $destinationNamespace $expectedNamespace -}}
                        {{- $expectedNamespace -}}
                        {{- else -}}
                        {{- fail (printf "GSM namespace label %q does not match the ExternalSecret namespace %q" $destinationNamespace $expectedNamespace) -}}
                        {{- end -}}
                        `}}
            templateFrom:
                -   literal: |
                        {{`
                        {{- (.metadata | toString | fromJson).annotations | toYaml -}}
                        `}}
                    target: Annotations
                -   literal: |
                        {{`
                        {{- $data := .data | toString -}}

                        {{- if and (hasPrefix "{" $data) (hasSuffix "}" $data) -}}
                        {{- range $k, $v := ($data | fromJson) }}
                        {{ $k }}: {{ $v | toString | quote }}
                        {{- end }}
                        {{- else }}
                        secret: {{ $data | quote }}
                        {{- end -}}
                        `}}
                    target: Data
                -   literal: |
                        {{`
                        {{- (.metadata | toString | fromJson).labels | toYaml -}}
                        `}}
                    target: Labels
{{- end }}
{{- end }}