{{- if .Values.overlay.enabled -}}
apiVersion: gcp.liferay.com/v1alpha1
kind: LiferayOverlay
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/sync-wave: "-20"
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    commonTags:
        {{- merge (dict "project_id" .Values.projectId) (.Values.overlay.commonTags | default dict) | toYaml | nindent 8 }}
    forceDestroy: {{ .Values.overlay.forceDestroy }}
    orphanOnDelete: {{ .Values.overlay.orphanOnDelete }}
    projectId: {{ .Values.projectId }}
    region: {{ .Values.region }}
{{- end -}}