/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat700.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntry;
import com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ArrayableEntry service. Represents a row in the &quot;ArrayableEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ArrayableEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArrayableEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArrayableEntryImpl
 * @generated
 */
public class ArrayableEntryModelImpl
	extends BaseModelImpl<ArrayableEntry> implements ArrayableEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a arrayable entry model instance should use the <code>ArrayableEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ArrayableEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"arrayableEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"integer_", Types.INTEGER}, {"name", Types.VARCHAR},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("arrayableEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("integer_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ArrayableEntry (arrayableEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,integer_ INTEGER,name VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ArrayableEntry";

	public static final String ENTITY_ALIAS = "arrayableEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY arrayableEntry.integer ASC, arrayableEntry.type ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ArrayableEntry.integer_ ASC, ArrayableEntry.type_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat700.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat700.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat700.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntry"),
		true);

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long INTEGER_COLUMN_BITMASK = 2L;

	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat700.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat700.model.ArrayableEntry"));

	public ArrayableEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _arrayableEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setArrayableEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _arrayableEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ArrayableEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ArrayableEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ArrayableEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ArrayableEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ArrayableEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ArrayableEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ArrayableEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ArrayableEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ArrayableEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ArrayableEntry.class.getClassLoader(), ArrayableEntry.class,
			ModelWrapper.class);

		try {
			Constructor<ArrayableEntry> constructor =
				(Constructor<ArrayableEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ArrayableEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ArrayableEntry, Object>>();

		attributeGetterFunctions.put(
			"arrayableEntryId",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getArrayableEntryId();
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getGroupId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getUserId();
				}

			});
		attributeGetterFunctions.put(
			"integer",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getInteger();
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getName();
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<ArrayableEntry, Object>() {

				@Override
				public Object apply(ArrayableEntry arrayableEntry) {
					return arrayableEntry.getType();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ArrayableEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ArrayableEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ArrayableEntry, ?>>();

		attributeSetterBiConsumers.put(
			"arrayableEntryId",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry,
					Object arrayableEntryIdObject) {

					arrayableEntry.setArrayableEntryId(
						(Long)arrayableEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object groupIdObject) {

					arrayableEntry.setGroupId((Long)groupIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object companyIdObject) {

					arrayableEntry.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object userIdObject) {

					arrayableEntry.setUserId((Long)userIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"integer",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object integerObject) {

					arrayableEntry.setInteger((Integer)integerObject);
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object nameObject) {

					arrayableEntry.setName((String)nameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<ArrayableEntry, Object>() {

				@Override
				public void accept(
					ArrayableEntry arrayableEntry, Object typeObject) {

					arrayableEntry.setType((String)typeObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getArrayableEntryId() {
		return _arrayableEntryId;
	}

	@Override
	public void setArrayableEntryId(long arrayableEntryId) {
		_arrayableEntryId = arrayableEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public int getInteger() {
		return _integer;
	}

	@Override
	public void setInteger(int integer) {
		_columnBitmask = -1L;

		_integer = integer;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask = -1L;

		_type = type;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ArrayableEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ArrayableEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ArrayableEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArrayableEntryImpl arrayableEntryImpl = new ArrayableEntryImpl();

		arrayableEntryImpl.setArrayableEntryId(getArrayableEntryId());
		arrayableEntryImpl.setGroupId(getGroupId());
		arrayableEntryImpl.setCompanyId(getCompanyId());
		arrayableEntryImpl.setUserId(getUserId());
		arrayableEntryImpl.setInteger(getInteger());
		arrayableEntryImpl.setName(getName());
		arrayableEntryImpl.setType(getType());

		arrayableEntryImpl.resetOriginalValues();

		return arrayableEntryImpl;
	}

	@Override
	public int compareTo(ArrayableEntry arrayableEntry) {
		int value = 0;

		if (getInteger() < arrayableEntry.getInteger()) {
			value = -1;
		}
		else if (getInteger() > arrayableEntry.getInteger()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getType().compareTo(arrayableEntry.getType());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ArrayableEntry)) {
			return false;
		}

		ArrayableEntry arrayableEntry = (ArrayableEntry)object;

		long primaryKey = arrayableEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ArrayableEntry> toCacheModel() {
		ArrayableEntryCacheModel arrayableEntryCacheModel =
			new ArrayableEntryCacheModel();

		arrayableEntryCacheModel.arrayableEntryId = getArrayableEntryId();

		arrayableEntryCacheModel.groupId = getGroupId();

		arrayableEntryCacheModel.companyId = getCompanyId();

		arrayableEntryCacheModel.userId = getUserId();

		arrayableEntryCacheModel.integer = getInteger();

		arrayableEntryCacheModel.name = getName();

		String name = arrayableEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			arrayableEntryCacheModel.name = null;
		}

		arrayableEntryCacheModel.type = getType();

		String type = arrayableEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			arrayableEntryCacheModel.type = null;
		}

		return arrayableEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ArrayableEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ArrayableEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ArrayableEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _arrayableEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private int _integer;
	private String _name;
	private String _type;
	private long _columnBitmask;
	private ArrayableEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1316343934