/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.tax.model.impl;

import com.liferay.commerce.tax.model.CommerceTaxCategoryMapping;
import com.liferay.commerce.tax.model.CommerceTaxCategoryMappingModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceTaxCategoryMapping service. Represents a row in the &quot;CommerceTaxCategoryMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceTaxCategoryMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceTaxCategoryMappingImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceTaxCategoryMappingImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceTaxCategoryMappingModelImpl
	extends BaseModelImpl<CommerceTaxCategoryMapping>
	implements CommerceTaxCategoryMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce tax category mapping model instance should use the <code>CommerceTaxCategoryMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceTaxCategoryMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"externalReferenceCode", Types.VARCHAR},
		{"commerceTaxCategoryMappingId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"commerceTaxMethodId", Types.BIGINT}, {"CPTaxCategoryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commerceTaxCategoryMappingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceTaxMethodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CPTaxCategoryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceTaxCategoryMapping (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,commerceTaxCategoryMappingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceTaxMethodId LONG,CPTaxCategoryId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceTaxCategoryMapping";

	public static final String ENTITY_ALIAS = "commerceTaxCategoryMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceTaxCategoryMapping.commerceTaxCategoryMappingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceTaxCategoryMapping.commerceTaxCategoryMappingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPTAXCATEGORYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCETAXMETHODID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCETAXCATEGORYMAPPINGID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommerceTaxCategoryMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceTaxCategoryMappingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceTaxCategoryMappingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceTaxCategoryMappingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceTaxCategoryMapping.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceTaxCategoryMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceTaxCategoryMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceTaxCategoryMapping, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceTaxCategoryMapping, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommerceTaxCategoryMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceTaxCategoryMapping, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceTaxCategoryMapping, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceTaxCategoryMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceTaxCategoryMapping, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceTaxCategoryMapping, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CommerceTaxCategoryMapping, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CommerceTaxCategoryMapping, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<CommerceTaxCategoryMapping, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CommerceTaxCategoryMapping::getMvccVersion);
			attributeGetterFunctions.put(
				"uuid", CommerceTaxCategoryMapping::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				CommerceTaxCategoryMapping::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"commerceTaxCategoryMappingId",
				CommerceTaxCategoryMapping::getCommerceTaxCategoryMappingId);
			attributeGetterFunctions.put(
				"groupId", CommerceTaxCategoryMapping::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CommerceTaxCategoryMapping::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CommerceTaxCategoryMapping::getUserId);
			attributeGetterFunctions.put(
				"userName", CommerceTaxCategoryMapping::getUserName);
			attributeGetterFunctions.put(
				"createDate", CommerceTaxCategoryMapping::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CommerceTaxCategoryMapping::getModifiedDate);
			attributeGetterFunctions.put(
				"commerceTaxMethodId",
				CommerceTaxCategoryMapping::getCommerceTaxMethodId);
			attributeGetterFunctions.put(
				"CPTaxCategoryId",
				CommerceTaxCategoryMapping::getCPTaxCategoryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CommerceTaxCategoryMapping, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CommerceTaxCategoryMapping, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CommerceTaxCategoryMapping, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CommerceTaxCategoryMapping, String>)
					CommerceTaxCategoryMapping::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<CommerceTaxCategoryMapping, String>)
					CommerceTaxCategoryMapping::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"commerceTaxCategoryMappingId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::
						setCommerceTaxCategoryMappingId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CommerceTaxCategoryMapping, String>)
					CommerceTaxCategoryMapping::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CommerceTaxCategoryMapping, Date>)
					CommerceTaxCategoryMapping::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CommerceTaxCategoryMapping, Date>)
					CommerceTaxCategoryMapping::setModifiedDate);
			attributeSetterBiConsumers.put(
				"commerceTaxMethodId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setCommerceTaxMethodId);
			attributeSetterBiConsumers.put(
				"CPTaxCategoryId",
				(BiConsumer<CommerceTaxCategoryMapping, Long>)
					CommerceTaxCategoryMapping::setCPTaxCategoryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getCommerceTaxCategoryMappingId() {
		return _commerceTaxCategoryMappingId;
	}

	@Override
	public void setCommerceTaxCategoryMappingId(
		long commerceTaxCategoryMappingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceTaxCategoryMappingId = commerceTaxCategoryMappingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceTaxMethodId() {
		return _commerceTaxMethodId;
	}

	@Override
	public void setCommerceTaxMethodId(long commerceTaxMethodId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceTaxMethodId = commerceTaxMethodId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceTaxMethodId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceTaxMethodId"));
	}

	@JSON
	@Override
	public long getCPTaxCategoryId() {
		return _CPTaxCategoryId;
	}

	@Override
	public void setCPTaxCategoryId(long CPTaxCategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPTaxCategoryId = CPTaxCategoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCPTaxCategoryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CPTaxCategoryId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CommerceTaxCategoryMapping.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceTaxCategoryMapping.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceTaxCategoryMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceTaxCategoryMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceTaxCategoryMappingImpl commerceTaxCategoryMappingImpl =
			new CommerceTaxCategoryMappingImpl();

		commerceTaxCategoryMappingImpl.setMvccVersion(getMvccVersion());
		commerceTaxCategoryMappingImpl.setUuid(getUuid());
		commerceTaxCategoryMappingImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		commerceTaxCategoryMappingImpl.setCommerceTaxCategoryMappingId(
			getCommerceTaxCategoryMappingId());
		commerceTaxCategoryMappingImpl.setGroupId(getGroupId());
		commerceTaxCategoryMappingImpl.setCompanyId(getCompanyId());
		commerceTaxCategoryMappingImpl.setUserId(getUserId());
		commerceTaxCategoryMappingImpl.setUserName(getUserName());
		commerceTaxCategoryMappingImpl.setCreateDate(getCreateDate());
		commerceTaxCategoryMappingImpl.setModifiedDate(getModifiedDate());
		commerceTaxCategoryMappingImpl.setCommerceTaxMethodId(
			getCommerceTaxMethodId());
		commerceTaxCategoryMappingImpl.setCPTaxCategoryId(getCPTaxCategoryId());

		commerceTaxCategoryMappingImpl.resetOriginalValues();

		return commerceTaxCategoryMappingImpl;
	}

	@Override
	public CommerceTaxCategoryMapping cloneWithOriginalValues() {
		CommerceTaxCategoryMappingImpl commerceTaxCategoryMappingImpl =
			new CommerceTaxCategoryMappingImpl();

		commerceTaxCategoryMappingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceTaxCategoryMappingImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		commerceTaxCategoryMappingImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		commerceTaxCategoryMappingImpl.setCommerceTaxCategoryMappingId(
			this.<Long>getColumnOriginalValue("commerceTaxCategoryMappingId"));
		commerceTaxCategoryMappingImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		commerceTaxCategoryMappingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceTaxCategoryMappingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceTaxCategoryMappingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceTaxCategoryMappingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceTaxCategoryMappingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceTaxCategoryMappingImpl.setCommerceTaxMethodId(
			this.<Long>getColumnOriginalValue("commerceTaxMethodId"));
		commerceTaxCategoryMappingImpl.setCPTaxCategoryId(
			this.<Long>getColumnOriginalValue("CPTaxCategoryId"));

		return commerceTaxCategoryMappingImpl;
	}

	@Override
	public int compareTo(
		CommerceTaxCategoryMapping commerceTaxCategoryMapping) {

		long primaryKey = commerceTaxCategoryMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceTaxCategoryMapping)) {
			return false;
		}

		CommerceTaxCategoryMapping commerceTaxCategoryMapping =
			(CommerceTaxCategoryMapping)object;

		long primaryKey = commerceTaxCategoryMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceTaxCategoryMapping> toCacheModel() {
		CommerceTaxCategoryMappingCacheModel
			commerceTaxCategoryMappingCacheModel =
				new CommerceTaxCategoryMappingCacheModel();

		commerceTaxCategoryMappingCacheModel.mvccVersion = getMvccVersion();

		commerceTaxCategoryMappingCacheModel.uuid = getUuid();

		String uuid = commerceTaxCategoryMappingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commerceTaxCategoryMappingCacheModel.uuid = null;
		}

		commerceTaxCategoryMappingCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			commerceTaxCategoryMappingCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			commerceTaxCategoryMappingCacheModel.externalReferenceCode = null;
		}

		commerceTaxCategoryMappingCacheModel.commerceTaxCategoryMappingId =
			getCommerceTaxCategoryMappingId();

		commerceTaxCategoryMappingCacheModel.groupId = getGroupId();

		commerceTaxCategoryMappingCacheModel.companyId = getCompanyId();

		commerceTaxCategoryMappingCacheModel.userId = getUserId();

		commerceTaxCategoryMappingCacheModel.userName = getUserName();

		String userName = commerceTaxCategoryMappingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceTaxCategoryMappingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceTaxCategoryMappingCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceTaxCategoryMappingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceTaxCategoryMappingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceTaxCategoryMappingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceTaxCategoryMappingCacheModel.commerceTaxMethodId =
			getCommerceTaxMethodId();

		commerceTaxCategoryMappingCacheModel.CPTaxCategoryId =
			getCPTaxCategoryId();

		return commerceTaxCategoryMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceTaxCategoryMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceTaxCategoryMapping, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceTaxCategoryMapping, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceTaxCategoryMapping)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceTaxCategoryMapping>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CommerceTaxCategoryMapping.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private String _externalReferenceCode;
	private long _commerceTaxCategoryMappingId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceTaxMethodId;
	private long _CPTaxCategoryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CommerceTaxCategoryMapping, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceTaxCategoryMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"commerceTaxCategoryMappingId", _commerceTaxCategoryMappingId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("commerceTaxMethodId", _commerceTaxMethodId);
		_columnOriginalValues.put("CPTaxCategoryId", _CPTaxCategoryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("externalReferenceCode", 4L);

		columnBitmasks.put("commerceTaxCategoryMappingId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("commerceTaxMethodId", 1024L);

		columnBitmasks.put("CPTaxCategoryId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceTaxCategoryMapping _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:162096751