#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.portal.security.audit.rest.dto.v1_0.AuditEvent
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Audit.REST)
osgi.jaxrs.resource=true