#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.mcp.server.rest.dto.v1_0.ToolSet
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.MCP.Server)
osgi.jaxrs.resource=true