create table Audit_AuditEvent (
	auditEventId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(200) null,
	createDate DATE null,
	accountEntryId LONG,
	additionalInfo TEXT null,
	className VARCHAR(200) null,
	classPK VARCHAR(75) null,
	clientHost VARCHAR(255) null,
	clientIP VARCHAR(255) null,
	contextName VARCHAR(75) null,
	eventType VARCHAR(75) null,
	message STRING null,
	serverName VARCHAR(255) null,
	serverPort INTEGER,
	sessionID VARCHAR(255) null
);