/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.workflow.kaleo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.workflow.kaleo.model.KaleoNodeSetting;
import com.liferay.portal.workflow.kaleo.model.KaleoNodeSettingModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KaleoNodeSetting service. Represents a row in the &quot;KaleoNodeSetting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KaleoNodeSettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KaleoNodeSettingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KaleoNodeSettingImpl
 * @generated
 */
public class KaleoNodeSettingModelImpl
	extends BaseModelImpl<KaleoNodeSetting> implements KaleoNodeSettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kaleo node setting model instance should use the <code>KaleoNodeSetting</code> interface instead.
	 */
	public static final String TABLE_NAME = "KaleoNodeSetting";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"kaleoNodeSettingId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"kaleoNodeId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"value", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kaleoNodeSettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("kaleoNodeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table KaleoNodeSetting (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,kaleoNodeSettingId LONG not null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,kaleoNodeId LONG,name VARCHAR(75) null,value TEXT null,primary key (kaleoNodeSettingId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table KaleoNodeSetting";

	public static final String ENTITY_ALIAS = "kaleoNodeSetting";

	public static final String ORDER_BY_JPQL =
		" ORDER BY kaleoNodeSetting.kaleoNodeSettingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY KaleoNodeSetting.kaleoNodeSettingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KALEONODEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KALEONODESETTINGID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public KaleoNodeSettingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _kaleoNodeSettingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKaleoNodeSettingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _kaleoNodeSettingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KaleoNodeSetting.class;
	}

	@Override
	public String getModelClassName() {
		return KaleoNodeSetting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KaleoNodeSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KaleoNodeSetting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KaleoNodeSetting, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((KaleoNodeSetting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KaleoNodeSetting, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KaleoNodeSetting, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KaleoNodeSetting)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KaleoNodeSetting, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KaleoNodeSetting, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<KaleoNodeSetting, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<KaleoNodeSetting, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<KaleoNodeSetting, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", KaleoNodeSetting::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", KaleoNodeSetting::getCtCollectionId);
			attributeGetterFunctions.put(
				"kaleoNodeSettingId", KaleoNodeSetting::getKaleoNodeSettingId);
			attributeGetterFunctions.put(
				"companyId", KaleoNodeSetting::getCompanyId);
			attributeGetterFunctions.put("userId", KaleoNodeSetting::getUserId);
			attributeGetterFunctions.put(
				"userName", KaleoNodeSetting::getUserName);
			attributeGetterFunctions.put(
				"createDate", KaleoNodeSetting::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", KaleoNodeSetting::getModifiedDate);
			attributeGetterFunctions.put(
				"kaleoNodeId", KaleoNodeSetting::getKaleoNodeId);
			attributeGetterFunctions.put("name", KaleoNodeSetting::getName);
			attributeGetterFunctions.put("value", KaleoNodeSetting::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<KaleoNodeSetting, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<KaleoNodeSetting, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<KaleoNodeSetting, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"kaleoNodeSettingId",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setKaleoNodeSettingId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<KaleoNodeSetting, String>)
					KaleoNodeSetting::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<KaleoNodeSetting, Date>)
					KaleoNodeSetting::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<KaleoNodeSetting, Date>)
					KaleoNodeSetting::setModifiedDate);
			attributeSetterBiConsumers.put(
				"kaleoNodeId",
				(BiConsumer<KaleoNodeSetting, Long>)
					KaleoNodeSetting::setKaleoNodeId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<KaleoNodeSetting, String>)
					KaleoNodeSetting::setName);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<KaleoNodeSetting, String>)
					KaleoNodeSetting::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getKaleoNodeSettingId() {
		return _kaleoNodeSettingId;
	}

	@Override
	public void setKaleoNodeSettingId(long kaleoNodeSettingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kaleoNodeSettingId = kaleoNodeSettingId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getKaleoNodeId() {
		return _kaleoNodeId;
	}

	@Override
	public void setKaleoNodeId(long kaleoNodeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kaleoNodeId = kaleoNodeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalKaleoNodeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("kaleoNodeId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), KaleoNodeSetting.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KaleoNodeSetting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KaleoNodeSetting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KaleoNodeSettingImpl kaleoNodeSettingImpl = new KaleoNodeSettingImpl();

		kaleoNodeSettingImpl.setMvccVersion(getMvccVersion());
		kaleoNodeSettingImpl.setCtCollectionId(getCtCollectionId());
		kaleoNodeSettingImpl.setKaleoNodeSettingId(getKaleoNodeSettingId());
		kaleoNodeSettingImpl.setCompanyId(getCompanyId());
		kaleoNodeSettingImpl.setUserId(getUserId());
		kaleoNodeSettingImpl.setUserName(getUserName());
		kaleoNodeSettingImpl.setCreateDate(getCreateDate());
		kaleoNodeSettingImpl.setModifiedDate(getModifiedDate());
		kaleoNodeSettingImpl.setKaleoNodeId(getKaleoNodeId());
		kaleoNodeSettingImpl.setName(getName());
		kaleoNodeSettingImpl.setValue(getValue());

		kaleoNodeSettingImpl.resetOriginalValues();

		return kaleoNodeSettingImpl;
	}

	@Override
	public KaleoNodeSetting cloneWithOriginalValues() {
		KaleoNodeSettingImpl kaleoNodeSettingImpl = new KaleoNodeSettingImpl();

		kaleoNodeSettingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		kaleoNodeSettingImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		kaleoNodeSettingImpl.setKaleoNodeSettingId(
			this.<Long>getColumnOriginalValue("kaleoNodeSettingId"));
		kaleoNodeSettingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		kaleoNodeSettingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		kaleoNodeSettingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		kaleoNodeSettingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		kaleoNodeSettingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		kaleoNodeSettingImpl.setKaleoNodeId(
			this.<Long>getColumnOriginalValue("kaleoNodeId"));
		kaleoNodeSettingImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		kaleoNodeSettingImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return kaleoNodeSettingImpl;
	}

	@Override
	public int compareTo(KaleoNodeSetting kaleoNodeSetting) {
		long primaryKey = kaleoNodeSetting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KaleoNodeSetting)) {
			return false;
		}

		KaleoNodeSetting kaleoNodeSetting = (KaleoNodeSetting)object;

		long primaryKey = kaleoNodeSetting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KaleoNodeSetting> toCacheModel() {
		KaleoNodeSettingCacheModel kaleoNodeSettingCacheModel =
			new KaleoNodeSettingCacheModel();

		kaleoNodeSettingCacheModel.mvccVersion = getMvccVersion();

		kaleoNodeSettingCacheModel.ctCollectionId = getCtCollectionId();

		kaleoNodeSettingCacheModel.kaleoNodeSettingId = getKaleoNodeSettingId();

		kaleoNodeSettingCacheModel.companyId = getCompanyId();

		kaleoNodeSettingCacheModel.userId = getUserId();

		kaleoNodeSettingCacheModel.userName = getUserName();

		String userName = kaleoNodeSettingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			kaleoNodeSettingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			kaleoNodeSettingCacheModel.createDate = createDate.getTime();
		}
		else {
			kaleoNodeSettingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			kaleoNodeSettingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			kaleoNodeSettingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		kaleoNodeSettingCacheModel.kaleoNodeId = getKaleoNodeId();

		kaleoNodeSettingCacheModel.name = getName();

		String name = kaleoNodeSettingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			kaleoNodeSettingCacheModel.name = null;
		}

		kaleoNodeSettingCacheModel.value = getValue();

		String value = kaleoNodeSettingCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			kaleoNodeSettingCacheModel.value = null;
		}

		return kaleoNodeSettingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KaleoNodeSetting, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KaleoNodeSetting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KaleoNodeSetting, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(KaleoNodeSetting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KaleoNodeSetting>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					KaleoNodeSetting.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _kaleoNodeSettingId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _kaleoNodeId;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		Function<KaleoNodeSetting, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((KaleoNodeSetting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("kaleoNodeSettingId", _kaleoNodeSettingId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("kaleoNodeId", _kaleoNodeId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("kaleoNodeSettingId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("kaleoNodeId", 256L);

		columnBitmasks.put("name", 512L);

		columnBitmasks.put("value", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private KaleoNodeSetting _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1425139873