apiDir: ../headless-design-library-api/src/main/java
apiPackagePath: com.liferay.headless.design.library
application:
    baseURI: /headless-design-library
    className: HeadlessDesignLibraryApplication
    name: Liferay.Headless.Design.Library
author: Luis Ortiz
clientDir: ../headless-design-library-client/src/main/java
compatibilityVersion: 15
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../headless-design-library-test/src/testIntegration/java