/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.UniqueFinderEntry;
import com.liferay.portal.tools.service.builder.test.service.UniqueFinderEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.UniqueFinderEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.UniqueFinderEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the unique finder entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.UniqueFinderEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.UniqueFinderEntryLocalServiceImpl
 * @generated
 */
public abstract class UniqueFinderEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, UniqueFinderEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UniqueFinderEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>UniqueFinderEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the unique finder entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueFinderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueFinderEntry the unique finder entry
	 * @return the unique finder entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UniqueFinderEntry addUniqueFinderEntry(
		UniqueFinderEntry uniqueFinderEntry) {

		uniqueFinderEntry.setNew(true);

		return uniqueFinderEntryPersistence.update(uniqueFinderEntry);
	}

	/**
	 * Creates a new unique finder entry with the primary key. Does not add the unique finder entry to the database.
	 *
	 * @param uniqueFinderEntryId the primary key for the new unique finder entry
	 * @return the new unique finder entry
	 */
	@Override
	@Transactional(enabled = false)
	public UniqueFinderEntry createUniqueFinderEntry(long uniqueFinderEntryId) {
		return uniqueFinderEntryPersistence.create(uniqueFinderEntryId);
	}

	/**
	 * Deletes the unique finder entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueFinderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueFinderEntryId the primary key of the unique finder entry
	 * @return the unique finder entry that was removed
	 * @throws PortalException if a unique finder entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UniqueFinderEntry deleteUniqueFinderEntry(long uniqueFinderEntryId)
		throws PortalException {

		return uniqueFinderEntryPersistence.remove(uniqueFinderEntryId);
	}

	/**
	 * Deletes the unique finder entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueFinderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueFinderEntry the unique finder entry
	 * @return the unique finder entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UniqueFinderEntry deleteUniqueFinderEntry(
		UniqueFinderEntry uniqueFinderEntry) {

		return uniqueFinderEntryPersistence.remove(uniqueFinderEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return uniqueFinderEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UniqueFinderEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return uniqueFinderEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueFinderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return uniqueFinderEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueFinderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return uniqueFinderEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return uniqueFinderEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return uniqueFinderEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UniqueFinderEntry fetchUniqueFinderEntry(long uniqueFinderEntryId) {
		return uniqueFinderEntryPersistence.fetchByPrimaryKey(
			uniqueFinderEntryId);
	}

	/**
	 * Returns the unique finder entry with the primary key.
	 *
	 * @param uniqueFinderEntryId the primary key of the unique finder entry
	 * @return the unique finder entry
	 * @throws PortalException if a unique finder entry with the primary key could not be found
	 */
	@Override
	public UniqueFinderEntry getUniqueFinderEntry(long uniqueFinderEntryId)
		throws PortalException {

		return uniqueFinderEntryPersistence.findByPrimaryKey(
			uniqueFinderEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			uniqueFinderEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UniqueFinderEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("uniqueFinderEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			uniqueFinderEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UniqueFinderEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"uniqueFinderEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			uniqueFinderEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UniqueFinderEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("uniqueFinderEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return uniqueFinderEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement UniqueFinderEntryLocalServiceImpl#deleteUniqueFinderEntry(UniqueFinderEntry) to avoid orphaned data");
		}

		return uniqueFinderEntryLocalService.deleteUniqueFinderEntry(
			(UniqueFinderEntry)persistedModel);
	}

	@Override
	public BasePersistence<UniqueFinderEntry> getBasePersistence() {
		return uniqueFinderEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return uniqueFinderEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the unique finder entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueFinderEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of unique finder entries
	 * @param end the upper bound of the range of unique finder entries (not inclusive)
	 * @return the range of unique finder entries
	 */
	@Override
	public List<UniqueFinderEntry> getUniqueFinderEntries(int start, int end) {
		return uniqueFinderEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of unique finder entries.
	 *
	 * @return the number of unique finder entries
	 */
	@Override
	public int getUniqueFinderEntriesCount() {
		return uniqueFinderEntryPersistence.countAll();
	}

	/**
	 * Updates the unique finder entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueFinderEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueFinderEntry the unique finder entry
	 * @return the unique finder entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UniqueFinderEntry updateUniqueFinderEntry(
		UniqueFinderEntry uniqueFinderEntry) {

		return uniqueFinderEntryPersistence.update(uniqueFinderEntry);
	}

	/**
	 * Returns the unique finder entry local service.
	 *
	 * @return the unique finder entry local service
	 */
	public UniqueFinderEntryLocalService getUniqueFinderEntryLocalService() {
		return uniqueFinderEntryLocalService;
	}

	/**
	 * Sets the unique finder entry local service.
	 *
	 * @param uniqueFinderEntryLocalService the unique finder entry local service
	 */
	public void setUniqueFinderEntryLocalService(
		UniqueFinderEntryLocalService uniqueFinderEntryLocalService) {

		this.uniqueFinderEntryLocalService = uniqueFinderEntryLocalService;
	}

	/**
	 * Returns the unique finder entry persistence.
	 *
	 * @return the unique finder entry persistence
	 */
	public UniqueFinderEntryPersistence getUniqueFinderEntryPersistence() {
		return uniqueFinderEntryPersistence;
	}

	/**
	 * Sets the unique finder entry persistence.
	 *
	 * @param uniqueFinderEntryPersistence the unique finder entry persistence
	 */
	public void setUniqueFinderEntryPersistence(
		UniqueFinderEntryPersistence uniqueFinderEntryPersistence) {

		this.uniqueFinderEntryPersistence = uniqueFinderEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		UniqueFinderEntryLocalServiceUtil.setService(
			uniqueFinderEntryLocalService);
	}

	public void destroy() {
		UniqueFinderEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UniqueFinderEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UniqueFinderEntry.class;
	}

	protected String getModelClassName() {
		return UniqueFinderEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = uniqueFinderEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = UniqueFinderEntryLocalService.class)
	protected UniqueFinderEntryLocalService uniqueFinderEntryLocalService;

	@BeanReference(type = UniqueFinderEntryPersistence.class)
	protected UniqueFinderEntryPersistence uniqueFinderEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		UniqueFinderEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:169057127