buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
		classpath group: "org.springframework.boot", name: "spring-boot-gradle-plugin", version: "2.7.18"
	}

	repositories {
		maven {
			url new File(rootProject.projectDir, "../../.m2-tmp")
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.source.formatter"
apply plugin: "java-library"
apply plugin: "org.springframework.boot"

def liferayReleaseToolEEDir = file("liferay-release-tool-ee")

clean {
	delete liferayReleaseToolEEDir
}

def executeCommand = {
	String command ->
	def process = command.execute()

	if (process.waitFor() != 0) {
		throw new GradleException(
			"Failed: ${command}\n${process.err.text}")
	}
}

task cloneReleaseToolEE

cloneReleaseToolEE {
	outputs.dir liferayReleaseToolEEDir

	onlyIf {
		!liferayReleaseToolEEDir.exists()
	}

	doLast {
		executeCommand("git clone --branch master --filter=blob:none --no-checkout git@github.com:liferay/liferay-release-tool-ee.git ${liferayReleaseToolEEDir.absolutePath}")
		executeCommand("git -C ${liferayReleaseToolEEDir.absolutePath} sparse-checkout set --no-cone ext/shared")
		executeCommand("git -C ${liferayReleaseToolEEDir.absolutePath} checkout HEAD")
	}
}

dependencies {
	implementation group: "com.liferay", name: "com.liferay.client.extension.util.spring.boot3", version: "latest.release"
	implementation group: "com.liferay", name: "com.liferay.headless.admin.user.client", version: "4.0.50"
	implementation group: "com.liferay", name: "com.liferay.notification.rest.client", version: "latest.release"
	implementation group: "com.liferay", name: "com.liferay.petra.io", version: "latest.release"
	implementation group: "com.liferay", name: "com.liferay.petra.string", version: "latest.release"
	implementation group: "com.liferay", name: "org.apache.commons.logging", version: "1.2.LIFERAY-PATCHED-2"
	implementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "latest.release"
	implementation group: "org.json", name: "json", version: "20231013"
	implementation group: "org.springframework.boot", name: "spring-boot-starter-oauth2-resource-server", version: "2.7.18"
	implementation group: "org.springframework.boot", name: "spring-boot-starter-web", version: "2.7.18"
	implementation group: "org.springframework.boot", name: "spring-boot-starter-webflux", version: "2.7.18"
	testImplementation group: "org.springframework.boot", name: "spring-boot-starter-test", version: "2.7.18"
}

repositories {
	maven {
		url new File(rootProject.projectDir, "../../.m2-tmp")
	}

	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}

sourceSets {
	main {
		java {
			srcDirs += "liferay-release-tool-ee/ext/shared/ext-impl/src"
		}
	}
}

test {
	jvmArgs(
		"--add-opens=java.base/java.lang=ALL-UNNAMED",
		"--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
		"--add-opens=java.base/java.lang.reflect=ALL-UNNAMED"
	)
	useJUnitPlatform()
}

compileJava.dependsOn cloneReleaseToolEE