/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.model.impl;

import com.liferay.commerce.model.CommerceOrderAttachment;
import com.liferay.commerce.model.CommerceOrderAttachmentModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceOrderAttachment service. Represents a row in the &quot;CommerceOrderAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceOrderAttachmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceOrderAttachmentImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommerceOrderAttachmentImpl
 * @generated
 */
@JSON(strict = true)
public class CommerceOrderAttachmentModelImpl
	extends BaseModelImpl<CommerceOrderAttachment>
	implements CommerceOrderAttachmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce order attachment model instance should use the <code>CommerceOrderAttachment</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceOrderAttachment";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"externalReferenceCode", Types.VARCHAR},
		{"commerceOrderAttachmentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"commerceOrderId", Types.BIGINT},
		{"fileEntryId", Types.BIGINT}, {"priority", Types.DOUBLE},
		{"restricted", Types.BOOLEAN}, {"title", Types.VARCHAR},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commerceOrderAttachmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceOrderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("priority", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("restricted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceOrderAttachment (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,commerceOrderAttachmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceOrderId LONG,fileEntryId LONG,priority DOUBLE,restricted BOOLEAN,title VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceOrderAttachment";

	public static final String ENTITY_ALIAS = "commerceOrderAttachment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceOrderAttachment.priority ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceOrderAttachment.priority ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEORDERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESTRICTED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIORITY_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommerceOrderAttachmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceOrderAttachmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceOrderAttachmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceOrderAttachmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceOrderAttachment.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceOrderAttachment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceOrderAttachment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceOrderAttachment, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceOrderAttachment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommerceOrderAttachment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceOrderAttachment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceOrderAttachment, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceOrderAttachment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceOrderAttachment, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceOrderAttachment, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CommerceOrderAttachment, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CommerceOrderAttachment, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CommerceOrderAttachment, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CommerceOrderAttachment::getMvccVersion);
			attributeGetterFunctions.put(
				"uuid", CommerceOrderAttachment::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				CommerceOrderAttachment::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"commerceOrderAttachmentId",
				CommerceOrderAttachment::getCommerceOrderAttachmentId);
			attributeGetterFunctions.put(
				"groupId", CommerceOrderAttachment::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CommerceOrderAttachment::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CommerceOrderAttachment::getUserId);
			attributeGetterFunctions.put(
				"userName", CommerceOrderAttachment::getUserName);
			attributeGetterFunctions.put(
				"createDate", CommerceOrderAttachment::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CommerceOrderAttachment::getModifiedDate);
			attributeGetterFunctions.put(
				"commerceOrderId", CommerceOrderAttachment::getCommerceOrderId);
			attributeGetterFunctions.put(
				"fileEntryId", CommerceOrderAttachment::getFileEntryId);
			attributeGetterFunctions.put(
				"priority", CommerceOrderAttachment::getPriority);
			attributeGetterFunctions.put(
				"restricted", CommerceOrderAttachment::getRestricted);
			attributeGetterFunctions.put(
				"title", CommerceOrderAttachment::getTitle);
			attributeGetterFunctions.put(
				"type", CommerceOrderAttachment::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CommerceOrderAttachment, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CommerceOrderAttachment, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CommerceOrderAttachment, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CommerceOrderAttachment, String>)
					CommerceOrderAttachment::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<CommerceOrderAttachment, String>)
					CommerceOrderAttachment::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"commerceOrderAttachmentId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setCommerceOrderAttachmentId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CommerceOrderAttachment, String>)
					CommerceOrderAttachment::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CommerceOrderAttachment, Date>)
					CommerceOrderAttachment::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CommerceOrderAttachment, Date>)
					CommerceOrderAttachment::setModifiedDate);
			attributeSetterBiConsumers.put(
				"commerceOrderId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setCommerceOrderId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<CommerceOrderAttachment, Long>)
					CommerceOrderAttachment::setFileEntryId);
			attributeSetterBiConsumers.put(
				"priority",
				(BiConsumer<CommerceOrderAttachment, Double>)
					CommerceOrderAttachment::setPriority);
			attributeSetterBiConsumers.put(
				"restricted",
				(BiConsumer<CommerceOrderAttachment, Boolean>)
					CommerceOrderAttachment::setRestricted);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<CommerceOrderAttachment, String>)
					CommerceOrderAttachment::setTitle);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<CommerceOrderAttachment, String>)
					CommerceOrderAttachment::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getCommerceOrderAttachmentId() {
		return _commerceOrderAttachmentId;
	}

	@Override
	public void setCommerceOrderAttachmentId(long commerceOrderAttachmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceOrderAttachmentId = commerceOrderAttachmentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceOrderId() {
		return _commerceOrderId;
	}

	@Override
	public void setCommerceOrderId(long commerceOrderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceOrderId = commerceOrderId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceOrderId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceOrderId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public double getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(double priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getRestricted() {
		return _restricted;
	}

	@JSON
	@Override
	public boolean isRestricted() {
		return _restricted;
	}

	@Override
	public void setRestricted(boolean restricted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_restricted = restricted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalRestricted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("restricted"));
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CommerceOrderAttachment.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceOrderAttachment.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceOrderAttachment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceOrderAttachment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceOrderAttachmentImpl commerceOrderAttachmentImpl =
			new CommerceOrderAttachmentImpl();

		commerceOrderAttachmentImpl.setMvccVersion(getMvccVersion());
		commerceOrderAttachmentImpl.setUuid(getUuid());
		commerceOrderAttachmentImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		commerceOrderAttachmentImpl.setCommerceOrderAttachmentId(
			getCommerceOrderAttachmentId());
		commerceOrderAttachmentImpl.setGroupId(getGroupId());
		commerceOrderAttachmentImpl.setCompanyId(getCompanyId());
		commerceOrderAttachmentImpl.setUserId(getUserId());
		commerceOrderAttachmentImpl.setUserName(getUserName());
		commerceOrderAttachmentImpl.setCreateDate(getCreateDate());
		commerceOrderAttachmentImpl.setModifiedDate(getModifiedDate());
		commerceOrderAttachmentImpl.setCommerceOrderId(getCommerceOrderId());
		commerceOrderAttachmentImpl.setFileEntryId(getFileEntryId());
		commerceOrderAttachmentImpl.setPriority(getPriority());
		commerceOrderAttachmentImpl.setRestricted(isRestricted());
		commerceOrderAttachmentImpl.setTitle(getTitle());
		commerceOrderAttachmentImpl.setType(getType());

		commerceOrderAttachmentImpl.resetOriginalValues();

		return commerceOrderAttachmentImpl;
	}

	@Override
	public CommerceOrderAttachment cloneWithOriginalValues() {
		CommerceOrderAttachmentImpl commerceOrderAttachmentImpl =
			new CommerceOrderAttachmentImpl();

		commerceOrderAttachmentImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceOrderAttachmentImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		commerceOrderAttachmentImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		commerceOrderAttachmentImpl.setCommerceOrderAttachmentId(
			this.<Long>getColumnOriginalValue("commerceOrderAttachmentId"));
		commerceOrderAttachmentImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		commerceOrderAttachmentImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceOrderAttachmentImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceOrderAttachmentImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceOrderAttachmentImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceOrderAttachmentImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceOrderAttachmentImpl.setCommerceOrderId(
			this.<Long>getColumnOriginalValue("commerceOrderId"));
		commerceOrderAttachmentImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		commerceOrderAttachmentImpl.setPriority(
			this.<Double>getColumnOriginalValue("priority"));
		commerceOrderAttachmentImpl.setRestricted(
			this.<Boolean>getColumnOriginalValue("restricted"));
		commerceOrderAttachmentImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		commerceOrderAttachmentImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return commerceOrderAttachmentImpl;
	}

	@Override
	public int compareTo(CommerceOrderAttachment commerceOrderAttachment) {
		int value = 0;

		if (getPriority() < commerceOrderAttachment.getPriority()) {
			value = -1;
		}
		else if (getPriority() > commerceOrderAttachment.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceOrderAttachment)) {
			return false;
		}

		CommerceOrderAttachment commerceOrderAttachment =
			(CommerceOrderAttachment)object;

		long primaryKey = commerceOrderAttachment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceOrderAttachment> toCacheModel() {
		CommerceOrderAttachmentCacheModel commerceOrderAttachmentCacheModel =
			new CommerceOrderAttachmentCacheModel();

		commerceOrderAttachmentCacheModel.mvccVersion = getMvccVersion();

		commerceOrderAttachmentCacheModel.uuid = getUuid();

		String uuid = commerceOrderAttachmentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commerceOrderAttachmentCacheModel.uuid = null;
		}

		commerceOrderAttachmentCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			commerceOrderAttachmentCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			commerceOrderAttachmentCacheModel.externalReferenceCode = null;
		}

		commerceOrderAttachmentCacheModel.commerceOrderAttachmentId =
			getCommerceOrderAttachmentId();

		commerceOrderAttachmentCacheModel.groupId = getGroupId();

		commerceOrderAttachmentCacheModel.companyId = getCompanyId();

		commerceOrderAttachmentCacheModel.userId = getUserId();

		commerceOrderAttachmentCacheModel.userName = getUserName();

		String userName = commerceOrderAttachmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceOrderAttachmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceOrderAttachmentCacheModel.createDate = createDate.getTime();
		}
		else {
			commerceOrderAttachmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceOrderAttachmentCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceOrderAttachmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceOrderAttachmentCacheModel.commerceOrderId =
			getCommerceOrderId();

		commerceOrderAttachmentCacheModel.fileEntryId = getFileEntryId();

		commerceOrderAttachmentCacheModel.priority = getPriority();

		commerceOrderAttachmentCacheModel.restricted = isRestricted();

		commerceOrderAttachmentCacheModel.title = getTitle();

		String title = commerceOrderAttachmentCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			commerceOrderAttachmentCacheModel.title = null;
		}

		commerceOrderAttachmentCacheModel.type = getType();

		String type = commerceOrderAttachmentCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			commerceOrderAttachmentCacheModel.type = null;
		}

		return commerceOrderAttachmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceOrderAttachment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceOrderAttachment, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceOrderAttachment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceOrderAttachment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceOrderAttachment>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CommerceOrderAttachment.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private String _externalReferenceCode;
	private long _commerceOrderAttachmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceOrderId;
	private long _fileEntryId;
	private double _priority;
	private boolean _restricted;
	private String _title;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CommerceOrderAttachment, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceOrderAttachment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"commerceOrderAttachmentId", _commerceOrderAttachmentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("commerceOrderId", _commerceOrderId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("restricted", _restricted);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("externalReferenceCode", 4L);

		columnBitmasks.put("commerceOrderAttachmentId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("commerceOrderId", 1024L);

		columnBitmasks.put("fileEntryId", 2048L);

		columnBitmasks.put("priority", 4096L);

		columnBitmasks.put("restricted", 8192L);

		columnBitmasks.put("title", 16384L);

		columnBitmasks.put("type_", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceOrderAttachment _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-673593320