/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

const execa = require('execa');

module.exports = {
	customBuild: {
		esbuild: false,
		other: async () => {
			await execa('node', ['./clay/clay-css/scripts/build.js'], {
				stdio: 'inherit',
			});
		},
	},
	exports: [
		'@clayui/alert',
		'@clayui/autocomplete',
		'@clayui/badge',
		'@clayui/breadcrumb',
		'@clayui/button',
		'@clayui/card',
		'@clayui/color-picker',
		'@clayui/core',
		'@clayui/data-provider',
		'@clayui/date-picker',
		'@clayui/drop-down',
		'@clayui/empty-state',
		'@clayui/form',
		'@clayui/icon',
		'@clayui/label',
		'@clayui/layout',
		'@clayui/link',
		'@clayui/list',
		'@clayui/loading-indicator',
		'@clayui/localized-input',
		'@clayui/management-toolbar',
		'@clayui/modal',
		'@clayui/multi-select',
		'@clayui/multi-step-nav',
		'@clayui/nav',
		'@clayui/navigation-bar',
		'@clayui/pagination',
		'@clayui/pagination-bar',
		'@clayui/panel',
		'@clayui/popover',
		'@clayui/progress-bar',
		'@clayui/provider',
		'@clayui/shared',
		'@clayui/slider',
		'@clayui/sticker',
		'@clayui/table',
		'@clayui/tabs',
		'@clayui/time-picker',
		'@clayui/toolbar',
		'@clayui/tooltip',
		'@clayui/upper-toolbar',
		'@clayui/css/lib/css/atlas.css',
		'@clayui/css/lib/css/base.css',
		'@clayui/css/lib/css/cadmin.css',
	],
	main: './src/main/resources/META-INF/resources/js/index.ts',
	symbols: {
		'@clayui/core': [
			'Body',
			'Button',
			'ButtonWithIcon',
			'Cell',
			'FocusTrap',
			'Head',
			'Heading',
			'Icon',
			'IconSelector',
			'KeyboardArrowsIndicator',
			'LanguagePicker',
			'Modal',
			'ModalContext',
			'Nav',
			'Option',
			'OverlayMask',
			'Picker',
			'Provider',
			'ResizeHandle',
			'Row',
			'SidePanel',
			'SidePanelWithDrilldown',
			'Table',
			'Text',
			'TextHighlight',
			'TreeView',
			'VerticalBar',
			'VerticalNav',
			'__EXPERIMENTAL_MENU',
			'__NOT_PUBLIC_COLLECTION',
			'__NOT_PUBLIC_LIVE_ANNOUNCER',
			'useModal',
			'useProvider',
		],
		'@clayui/date-picker': ['FirstDayOfWeek', 'default'],
		'@clayui/provider': [
			'Provider',
			'__UNSTABLE_DataClient',
			'useProvider',
		],
	},
};
