/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.cookies.model.impl;

import com.liferay.cookies.model.CookiesConsentPreference;
import com.liferay.cookies.model.CookiesConsentPreferenceModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CookiesConsentPreference service. Represents a row in the &quot;CookiesConsentPreference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CookiesConsentPreferenceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CookiesConsentPreferenceImpl}.
 * </p>
 *
 * @author Christopher Kian
 * @see CookiesConsentPreferenceImpl
 * @generated
 */
@JSON(strict = true)
public class CookiesConsentPreferenceModelImpl
	extends BaseModelImpl<CookiesConsentPreference>
	implements CookiesConsentPreferenceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cookies consent preference model instance should use the <code>CookiesConsentPreference</code> interface instead.
	 */
	public static final String TABLE_NAME = "CookiesConsentPreference";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"cookiesConsentPreferenceId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"domain", Types.VARCHAR},
		{"expirationDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cookiesConsentPreferenceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("domain", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CookiesConsentPreference (mvccVersion LONG default 0 not null,cookiesConsentPreferenceId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,domain VARCHAR(75) null,expirationDate DATE null,name VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CookiesConsentPreference";

	public static final String ENTITY_ALIAS = "cookiesConsentPreference";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cookiesConsentPreference.cookiesConsentPreferenceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CookiesConsentPreference.cookiesConsentPreferenceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOMAIN_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPIRATIONDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COOKIESCONSENTPREFERENCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CookiesConsentPreferenceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cookiesConsentPreferenceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCookiesConsentPreferenceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cookiesConsentPreferenceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CookiesConsentPreference.class;
	}

	@Override
	public String getModelClassName() {
		return CookiesConsentPreference.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CookiesConsentPreference, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CookiesConsentPreference, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CookiesConsentPreference, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CookiesConsentPreference)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CookiesConsentPreference, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CookiesConsentPreference, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CookiesConsentPreference)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CookiesConsentPreference, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CookiesConsentPreference, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CookiesConsentPreference, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CookiesConsentPreference, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CookiesConsentPreference, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CookiesConsentPreference::getMvccVersion);
			attributeGetterFunctions.put(
				"cookiesConsentPreferenceId",
				CookiesConsentPreference::getCookiesConsentPreferenceId);
			attributeGetterFunctions.put(
				"companyId", CookiesConsentPreference::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CookiesConsentPreference::getUserId);
			attributeGetterFunctions.put(
				"userName", CookiesConsentPreference::getUserName);
			attributeGetterFunctions.put(
				"domain", CookiesConsentPreference::getDomain);
			attributeGetterFunctions.put(
				"expirationDate", CookiesConsentPreference::getExpirationDate);
			attributeGetterFunctions.put(
				"name", CookiesConsentPreference::getName);
			attributeGetterFunctions.put(
				"value", CookiesConsentPreference::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CookiesConsentPreference, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CookiesConsentPreference, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CookiesConsentPreference, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CookiesConsentPreference, Long>)
					CookiesConsentPreference::setMvccVersion);
			attributeSetterBiConsumers.put(
				"cookiesConsentPreferenceId",
				(BiConsumer<CookiesConsentPreference, Long>)
					CookiesConsentPreference::setCookiesConsentPreferenceId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CookiesConsentPreference, Long>)
					CookiesConsentPreference::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CookiesConsentPreference, Long>)
					CookiesConsentPreference::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CookiesConsentPreference, String>)
					CookiesConsentPreference::setUserName);
			attributeSetterBiConsumers.put(
				"domain",
				(BiConsumer<CookiesConsentPreference, String>)
					CookiesConsentPreference::setDomain);
			attributeSetterBiConsumers.put(
				"expirationDate",
				(BiConsumer<CookiesConsentPreference, Date>)
					CookiesConsentPreference::setExpirationDate);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<CookiesConsentPreference, String>)
					CookiesConsentPreference::setName);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<CookiesConsentPreference, String>)
					CookiesConsentPreference::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCookiesConsentPreferenceId() {
		return _cookiesConsentPreferenceId;
	}

	@Override
	public void setCookiesConsentPreferenceId(long cookiesConsentPreferenceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cookiesConsentPreferenceId = cookiesConsentPreferenceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getDomain() {
		if (_domain == null) {
			return "";
		}
		else {
			return _domain;
		}
	}

	@Override
	public void setDomain(String domain) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_domain = domain;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDomain() {
		return getColumnOriginalValue("domain");
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalExpirationDate() {
		return getColumnOriginalValue("expirationDate");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CookiesConsentPreference.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CookiesConsentPreference toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CookiesConsentPreference>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CookiesConsentPreferenceImpl cookiesConsentPreferenceImpl =
			new CookiesConsentPreferenceImpl();

		cookiesConsentPreferenceImpl.setMvccVersion(getMvccVersion());
		cookiesConsentPreferenceImpl.setCookiesConsentPreferenceId(
			getCookiesConsentPreferenceId());
		cookiesConsentPreferenceImpl.setCompanyId(getCompanyId());
		cookiesConsentPreferenceImpl.setUserId(getUserId());
		cookiesConsentPreferenceImpl.setUserName(getUserName());
		cookiesConsentPreferenceImpl.setDomain(getDomain());
		cookiesConsentPreferenceImpl.setExpirationDate(getExpirationDate());
		cookiesConsentPreferenceImpl.setName(getName());
		cookiesConsentPreferenceImpl.setValue(getValue());

		cookiesConsentPreferenceImpl.resetOriginalValues();

		return cookiesConsentPreferenceImpl;
	}

	@Override
	public CookiesConsentPreference cloneWithOriginalValues() {
		CookiesConsentPreferenceImpl cookiesConsentPreferenceImpl =
			new CookiesConsentPreferenceImpl();

		cookiesConsentPreferenceImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cookiesConsentPreferenceImpl.setCookiesConsentPreferenceId(
			this.<Long>getColumnOriginalValue("cookiesConsentPreferenceId"));
		cookiesConsentPreferenceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cookiesConsentPreferenceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cookiesConsentPreferenceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cookiesConsentPreferenceImpl.setDomain(
			this.<String>getColumnOriginalValue("domain"));
		cookiesConsentPreferenceImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));
		cookiesConsentPreferenceImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		cookiesConsentPreferenceImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return cookiesConsentPreferenceImpl;
	}

	@Override
	public int compareTo(CookiesConsentPreference cookiesConsentPreference) {
		long primaryKey = cookiesConsentPreference.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CookiesConsentPreference)) {
			return false;
		}

		CookiesConsentPreference cookiesConsentPreference =
			(CookiesConsentPreference)object;

		long primaryKey = cookiesConsentPreference.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CookiesConsentPreference> toCacheModel() {
		CookiesConsentPreferenceCacheModel cookiesConsentPreferenceCacheModel =
			new CookiesConsentPreferenceCacheModel();

		cookiesConsentPreferenceCacheModel.mvccVersion = getMvccVersion();

		cookiesConsentPreferenceCacheModel.cookiesConsentPreferenceId =
			getCookiesConsentPreferenceId();

		cookiesConsentPreferenceCacheModel.companyId = getCompanyId();

		cookiesConsentPreferenceCacheModel.userId = getUserId();

		cookiesConsentPreferenceCacheModel.userName = getUserName();

		String userName = cookiesConsentPreferenceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cookiesConsentPreferenceCacheModel.userName = null;
		}

		cookiesConsentPreferenceCacheModel.domain = getDomain();

		String domain = cookiesConsentPreferenceCacheModel.domain;

		if ((domain != null) && (domain.length() == 0)) {
			cookiesConsentPreferenceCacheModel.domain = null;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			cookiesConsentPreferenceCacheModel.expirationDate =
				expirationDate.getTime();
		}
		else {
			cookiesConsentPreferenceCacheModel.expirationDate = Long.MIN_VALUE;
		}

		cookiesConsentPreferenceCacheModel.name = getName();

		String name = cookiesConsentPreferenceCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cookiesConsentPreferenceCacheModel.name = null;
		}

		cookiesConsentPreferenceCacheModel.value = getValue();

		String value = cookiesConsentPreferenceCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			cookiesConsentPreferenceCacheModel.value = null;
		}

		return cookiesConsentPreferenceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CookiesConsentPreference, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CookiesConsentPreference, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CookiesConsentPreference, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CookiesConsentPreference)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CookiesConsentPreference>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CookiesConsentPreference.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _cookiesConsentPreferenceId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private String _domain;
	private Date _expirationDate;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		Function<CookiesConsentPreference, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CookiesConsentPreference)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"cookiesConsentPreferenceId", _cookiesConsentPreferenceId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("domain", _domain);
		_columnOriginalValues.put("expirationDate", _expirationDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("cookiesConsentPreferenceId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("domain", 32L);

		columnBitmasks.put("expirationDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("value", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CookiesConsentPreference _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1337580002