/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.product.type.virtual.model.impl;

import com.liferay.commerce.product.type.virtual.model.CPDVirtualSettingFileEntry;
import com.liferay.commerce.product.type.virtual.model.CPDVirtualSettingFileEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPDVirtualSettingFileEntry service. Represents a row in the &quot;CPDVirtualSettingFileEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPDVirtualSettingFileEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPDVirtualSettingFileEntryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CPDVirtualSettingFileEntryImpl
 * @generated
 */
@JSON(strict = true)
public class CPDVirtualSettingFileEntryModelImpl
	extends BaseModelImpl<CPDVirtualSettingFileEntry>
	implements CPDVirtualSettingFileEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cpd virtual setting file entry model instance should use the <code>CPDVirtualSettingFileEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPDVirtualSettingFileEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"CPDVirtualSettingFileEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"CPDefinitionVirtualSettingId", Types.BIGINT},
		{"fileEntryId", Types.BIGINT}, {"url", Types.VARCHAR},
		{"version", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPDVirtualSettingFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CPDefinitionVirtualSettingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPDVirtualSettingFileEntry (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,CPDVirtualSettingFileEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,CPDefinitionVirtualSettingId LONG,fileEntryId LONG,url VARCHAR(255) null,version VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CPDVirtualSettingFileEntry";

	public static final String ENTITY_ALIAS = "cpdVirtualSettingFileEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpdVirtualSettingFileEntry.CPDefinitionVirtualSettingFileEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPDVirtualSettingFileEntry.CPDVirtualSettingFileEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CPDEFINITIONVIRTUALSETTINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long
		CPDEFINITIONVIRTUALSETTINGFILEENTRYID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CPDVirtualSettingFileEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CPDefinitionVirtualSettingFileEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCPDefinitionVirtualSettingFileEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CPDefinitionVirtualSettingFileEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPDVirtualSettingFileEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CPDVirtualSettingFileEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPDVirtualSettingFileEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPDVirtualSettingFileEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPDVirtualSettingFileEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CPDVirtualSettingFileEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPDVirtualSettingFileEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPDVirtualSettingFileEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPDVirtualSettingFileEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPDVirtualSettingFileEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPDVirtualSettingFileEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CPDVirtualSettingFileEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CPDVirtualSettingFileEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<CPDVirtualSettingFileEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CPDVirtualSettingFileEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"uuid", CPDVirtualSettingFileEntry::getUuid);
			attributeGetterFunctions.put(
				"CPDefinitionVirtualSettingFileEntryId",
				CPDVirtualSettingFileEntry::
					getCPDefinitionVirtualSettingFileEntryId);
			attributeGetterFunctions.put(
				"groupId", CPDVirtualSettingFileEntry::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CPDVirtualSettingFileEntry::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CPDVirtualSettingFileEntry::getUserId);
			attributeGetterFunctions.put(
				"userName", CPDVirtualSettingFileEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", CPDVirtualSettingFileEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CPDVirtualSettingFileEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"CPDefinitionVirtualSettingId",
				CPDVirtualSettingFileEntry::getCPDefinitionVirtualSettingId);
			attributeGetterFunctions.put(
				"fileEntryId", CPDVirtualSettingFileEntry::getFileEntryId);
			attributeGetterFunctions.put(
				"url", CPDVirtualSettingFileEntry::getUrl);
			attributeGetterFunctions.put(
				"version", CPDVirtualSettingFileEntry::getVersion);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CPDVirtualSettingFileEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CPDVirtualSettingFileEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CPDVirtualSettingFileEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CPDVirtualSettingFileEntry, String>)
					CPDVirtualSettingFileEntry::setUuid);
			attributeSetterBiConsumers.put(
				"CPDefinitionVirtualSettingFileEntryId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::
						setCPDefinitionVirtualSettingFileEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CPDVirtualSettingFileEntry, String>)
					CPDVirtualSettingFileEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CPDVirtualSettingFileEntry, Date>)
					CPDVirtualSettingFileEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CPDVirtualSettingFileEntry, Date>)
					CPDVirtualSettingFileEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"CPDefinitionVirtualSettingId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::
						setCPDefinitionVirtualSettingId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<CPDVirtualSettingFileEntry, Long>)
					CPDVirtualSettingFileEntry::setFileEntryId);
			attributeSetterBiConsumers.put(
				"url",
				(BiConsumer<CPDVirtualSettingFileEntry, String>)
					CPDVirtualSettingFileEntry::setUrl);
			attributeSetterBiConsumers.put(
				"version",
				(BiConsumer<CPDVirtualSettingFileEntry, String>)
					CPDVirtualSettingFileEntry::setVersion);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCPDefinitionVirtualSettingFileEntryId() {
		return _CPDefinitionVirtualSettingFileEntryId;
	}

	@Override
	public void setCPDefinitionVirtualSettingFileEntryId(
		long CPDefinitionVirtualSettingFileEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPDefinitionVirtualSettingFileEntryId =
			CPDefinitionVirtualSettingFileEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCPDefinitionVirtualSettingId() {
		return _CPDefinitionVirtualSettingId;
	}

	@Override
	public void setCPDefinitionVirtualSettingId(
		long CPDefinitionVirtualSettingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CPDefinitionVirtualSettingId = CPDefinitionVirtualSettingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCPDefinitionVirtualSettingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("CPDefinitionVirtualSettingId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFileEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("fileEntryId"));
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CPDVirtualSettingFileEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CPDVirtualSettingFileEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPDVirtualSettingFileEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPDVirtualSettingFileEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPDVirtualSettingFileEntryImpl cpdVirtualSettingFileEntryImpl =
			new CPDVirtualSettingFileEntryImpl();

		cpdVirtualSettingFileEntryImpl.setMvccVersion(getMvccVersion());
		cpdVirtualSettingFileEntryImpl.setUuid(getUuid());
		cpdVirtualSettingFileEntryImpl.setCPDefinitionVirtualSettingFileEntryId(
			getCPDefinitionVirtualSettingFileEntryId());
		cpdVirtualSettingFileEntryImpl.setGroupId(getGroupId());
		cpdVirtualSettingFileEntryImpl.setCompanyId(getCompanyId());
		cpdVirtualSettingFileEntryImpl.setUserId(getUserId());
		cpdVirtualSettingFileEntryImpl.setUserName(getUserName());
		cpdVirtualSettingFileEntryImpl.setCreateDate(getCreateDate());
		cpdVirtualSettingFileEntryImpl.setModifiedDate(getModifiedDate());
		cpdVirtualSettingFileEntryImpl.setCPDefinitionVirtualSettingId(
			getCPDefinitionVirtualSettingId());
		cpdVirtualSettingFileEntryImpl.setFileEntryId(getFileEntryId());
		cpdVirtualSettingFileEntryImpl.setUrl(getUrl());
		cpdVirtualSettingFileEntryImpl.setVersion(getVersion());

		cpdVirtualSettingFileEntryImpl.resetOriginalValues();

		return cpdVirtualSettingFileEntryImpl;
	}

	@Override
	public CPDVirtualSettingFileEntry cloneWithOriginalValues() {
		CPDVirtualSettingFileEntryImpl cpdVirtualSettingFileEntryImpl =
			new CPDVirtualSettingFileEntryImpl();

		cpdVirtualSettingFileEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		cpdVirtualSettingFileEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		cpdVirtualSettingFileEntryImpl.setCPDefinitionVirtualSettingFileEntryId(
			this.<Long>getColumnOriginalValue("CPDVirtualSettingFileEntryId"));
		cpdVirtualSettingFileEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		cpdVirtualSettingFileEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cpdVirtualSettingFileEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cpdVirtualSettingFileEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cpdVirtualSettingFileEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		cpdVirtualSettingFileEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		cpdVirtualSettingFileEntryImpl.setCPDefinitionVirtualSettingId(
			this.<Long>getColumnOriginalValue("CPDefinitionVirtualSettingId"));
		cpdVirtualSettingFileEntryImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		cpdVirtualSettingFileEntryImpl.setUrl(
			this.<String>getColumnOriginalValue("url"));
		cpdVirtualSettingFileEntryImpl.setVersion(
			this.<String>getColumnOriginalValue("version"));

		return cpdVirtualSettingFileEntryImpl;
	}

	@Override
	public int compareTo(
		CPDVirtualSettingFileEntry cpdVirtualSettingFileEntry) {

		long primaryKey = cpdVirtualSettingFileEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPDVirtualSettingFileEntry)) {
			return false;
		}

		CPDVirtualSettingFileEntry cpdVirtualSettingFileEntry =
			(CPDVirtualSettingFileEntry)object;

		long primaryKey = cpdVirtualSettingFileEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPDVirtualSettingFileEntry> toCacheModel() {
		CPDVirtualSettingFileEntryCacheModel
			cpdVirtualSettingFileEntryCacheModel =
				new CPDVirtualSettingFileEntryCacheModel();

		cpdVirtualSettingFileEntryCacheModel.mvccVersion = getMvccVersion();

		cpdVirtualSettingFileEntryCacheModel.uuid = getUuid();

		String uuid = cpdVirtualSettingFileEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cpdVirtualSettingFileEntryCacheModel.uuid = null;
		}

		cpdVirtualSettingFileEntryCacheModel.
			CPDefinitionVirtualSettingFileEntryId =
				getCPDefinitionVirtualSettingFileEntryId();

		cpdVirtualSettingFileEntryCacheModel.groupId = getGroupId();

		cpdVirtualSettingFileEntryCacheModel.companyId = getCompanyId();

		cpdVirtualSettingFileEntryCacheModel.userId = getUserId();

		cpdVirtualSettingFileEntryCacheModel.userName = getUserName();

		String userName = cpdVirtualSettingFileEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cpdVirtualSettingFileEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cpdVirtualSettingFileEntryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			cpdVirtualSettingFileEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cpdVirtualSettingFileEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			cpdVirtualSettingFileEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cpdVirtualSettingFileEntryCacheModel.CPDefinitionVirtualSettingId =
			getCPDefinitionVirtualSettingId();

		cpdVirtualSettingFileEntryCacheModel.fileEntryId = getFileEntryId();

		cpdVirtualSettingFileEntryCacheModel.url = getUrl();

		String url = cpdVirtualSettingFileEntryCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			cpdVirtualSettingFileEntryCacheModel.url = null;
		}

		cpdVirtualSettingFileEntryCacheModel.version = getVersion();

		String version = cpdVirtualSettingFileEntryCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			cpdVirtualSettingFileEntryCacheModel.version = null;
		}

		return cpdVirtualSettingFileEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPDVirtualSettingFileEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPDVirtualSettingFileEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPDVirtualSettingFileEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CPDVirtualSettingFileEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CPDVirtualSettingFileEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CPDVirtualSettingFileEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _CPDefinitionVirtualSettingFileEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _CPDefinitionVirtualSettingId;
	private long _fileEntryId;
	private String _url;
	private String _version;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CPDVirtualSettingFileEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPDVirtualSettingFileEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"CPDVirtualSettingFileEntryId",
			_CPDefinitionVirtualSettingFileEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"CPDefinitionVirtualSettingId", _CPDefinitionVirtualSettingId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("version", _version);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put(
			"CPDVirtualSettingFileEntryId",
			"CPDefinitionVirtualSettingFileEntryId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("CPDVirtualSettingFileEntryId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("CPDefinitionVirtualSettingId", 512L);

		columnBitmasks.put("fileEntryId", 1024L);

		columnBitmasks.put("url", 2048L);

		columnBitmasks.put("version", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPDVirtualSettingFileEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-487358780