apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-120"
    labels:
        name: elastic-system
        pod-security.kubernetes.io/enforce: restricted
    name: elastic-system