/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat730.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat730.model.ArrayableEntry;
import com.liferay.portal.tools.service.builder.test.compat730.model.ArrayableEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ArrayableEntry service. Represents a row in the &quot;ArrayableEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ArrayableEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArrayableEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ArrayableEntryImpl
 * @generated
 */
public class ArrayableEntryModelImpl
	extends BaseModelImpl<ArrayableEntry> implements ArrayableEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a arrayable entry model instance should use the <code>ArrayableEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ArrayableEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"arrayableEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"integer_", Types.INTEGER}, {"name", Types.VARCHAR},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("arrayableEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("integer_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ArrayableEntry (arrayableEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,integer_ INTEGER,name VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ArrayableEntry";

	public static final String ENTITY_ALIAS = "arrayableEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY arrayableEntry.integer ASC, arrayableEntry.type ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ArrayableEntry.integer_ ASC, ArrayableEntry.type_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INTEGER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat730.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat730.model.ArrayableEntry"));

	public ArrayableEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _arrayableEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setArrayableEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _arrayableEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ArrayableEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ArrayableEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ArrayableEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ArrayableEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ArrayableEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ArrayableEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ArrayableEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ArrayableEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ArrayableEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ArrayableEntry, Object>>();

		attributeGetterFunctions.put(
			"arrayableEntryId", ArrayableEntry::getArrayableEntryId);
		attributeGetterFunctions.put("groupId", ArrayableEntry::getGroupId);
		attributeGetterFunctions.put("companyId", ArrayableEntry::getCompanyId);
		attributeGetterFunctions.put("userId", ArrayableEntry::getUserId);
		attributeGetterFunctions.put("integer", ArrayableEntry::getInteger);
		attributeGetterFunctions.put("name", ArrayableEntry::getName);
		attributeGetterFunctions.put("type", ArrayableEntry::getType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ArrayableEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ArrayableEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ArrayableEntry, ?>>();

		attributeSetterBiConsumers.put(
			"arrayableEntryId",
			(BiConsumer<ArrayableEntry, Long>)
				ArrayableEntry::setArrayableEntryId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ArrayableEntry, Long>)ArrayableEntry::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ArrayableEntry, Long>)ArrayableEntry::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ArrayableEntry, Long>)ArrayableEntry::setUserId);
		attributeSetterBiConsumers.put(
			"integer",
			(BiConsumer<ArrayableEntry, Integer>)ArrayableEntry::setInteger);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<ArrayableEntry, String>)ArrayableEntry::setName);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<ArrayableEntry, String>)ArrayableEntry::setType);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getArrayableEntryId() {
		return _arrayableEntryId;
	}

	@Override
	public void setArrayableEntryId(long arrayableEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arrayableEntryId = arrayableEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public int getInteger() {
		return _integer;
	}

	@Override
	public void setInteger(int integer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_integer = integer;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ArrayableEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ArrayableEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ArrayableEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArrayableEntryImpl arrayableEntryImpl = new ArrayableEntryImpl();

		arrayableEntryImpl.setArrayableEntryId(getArrayableEntryId());
		arrayableEntryImpl.setGroupId(getGroupId());
		arrayableEntryImpl.setCompanyId(getCompanyId());
		arrayableEntryImpl.setUserId(getUserId());
		arrayableEntryImpl.setInteger(getInteger());
		arrayableEntryImpl.setName(getName());
		arrayableEntryImpl.setType(getType());

		arrayableEntryImpl.resetOriginalValues();

		return arrayableEntryImpl;
	}

	@Override
	public int compareTo(ArrayableEntry arrayableEntry) {
		int value = 0;

		if (getInteger() < arrayableEntry.getInteger()) {
			value = -1;
		}
		else if (getInteger() > arrayableEntry.getInteger()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getType().compareTo(arrayableEntry.getType());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ArrayableEntry)) {
			return false;
		}

		ArrayableEntry arrayableEntry = (ArrayableEntry)object;

		long primaryKey = arrayableEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ArrayableEntry> toCacheModel() {
		ArrayableEntryCacheModel arrayableEntryCacheModel =
			new ArrayableEntryCacheModel();

		arrayableEntryCacheModel.arrayableEntryId = getArrayableEntryId();

		arrayableEntryCacheModel.groupId = getGroupId();

		arrayableEntryCacheModel.companyId = getCompanyId();

		arrayableEntryCacheModel.userId = getUserId();

		arrayableEntryCacheModel.integer = getInteger();

		arrayableEntryCacheModel.name = getName();

		String name = arrayableEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			arrayableEntryCacheModel.name = null;
		}

		arrayableEntryCacheModel.type = getType();

		String type = arrayableEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			arrayableEntryCacheModel.type = null;
		}

		return arrayableEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ArrayableEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ArrayableEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ArrayableEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArrayableEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ArrayableEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ArrayableEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ArrayableEntry.class, ModelWrapper.class);

	}

	private long _arrayableEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private int _integer;
	private String _name;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ArrayableEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ArrayableEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("arrayableEntryId", _arrayableEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("integer_", _integer);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("integer_", "integer");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("arrayableEntryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("integer_", 16L);

		columnBitmasks.put("name", 32L);

		columnBitmasks.put("type_", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ArrayableEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1336792427