/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat730.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat730.model.ERCCompanyEntry;
import com.liferay.portal.tools.service.builder.test.compat730.model.ERCCompanyEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ERCCompanyEntry service. Represents a row in the &quot;ERCCompanyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ERCCompanyEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ERCCompanyEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ERCCompanyEntryImpl
 * @generated
 */
public class ERCCompanyEntryModelImpl
	extends BaseModelImpl<ERCCompanyEntry> implements ERCCompanyEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a erc company entry model instance should use the <code>ERCCompanyEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ERCCompanyEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"ercCompanyEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"column1", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ercCompanyEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("column1", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ERCCompanyEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,ercCompanyEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,column1 INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ERCCompanyEntry";

	public static final String ENTITY_ALIAS = "ercCompanyEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ercCompanyEntry.ercCompanyEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ERCCompanyEntry.ercCompanyEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ERCCOMPANYENTRYID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat730.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat730.model.ERCCompanyEntry"));

	public ERCCompanyEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setErcCompanyEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ERCCompanyEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ERCCompanyEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ERCCompanyEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ERCCompanyEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ERCCompanyEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ERCCompanyEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ERCCompanyEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ERCCompanyEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ERCCompanyEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ERCCompanyEntry, Object>>();

		attributeGetterFunctions.put("uuid", ERCCompanyEntry::getUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", ERCCompanyEntry::getExternalReferenceCode);
		attributeGetterFunctions.put(
			"ercCompanyEntryId", ERCCompanyEntry::getErcCompanyEntryId);
		attributeGetterFunctions.put(
			"companyId", ERCCompanyEntry::getCompanyId);
		attributeGetterFunctions.put("userId", ERCCompanyEntry::getUserId);
		attributeGetterFunctions.put("userName", ERCCompanyEntry::getUserName);
		attributeGetterFunctions.put("column1", ERCCompanyEntry::getColumn1);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ERCCompanyEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ERCCompanyEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ERCCompanyEntry, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ERCCompanyEntry, String>)ERCCompanyEntry::setUuid);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<ERCCompanyEntry, String>)
				ERCCompanyEntry::setExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"ercCompanyEntryId",
			(BiConsumer<ERCCompanyEntry, Long>)
				ERCCompanyEntry::setErcCompanyEntryId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ERCCompanyEntry, Long>)ERCCompanyEntry::setCompanyId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ERCCompanyEntry, Long>)ERCCompanyEntry::setUserId);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ERCCompanyEntry, String>)ERCCompanyEntry::setUserName);
		attributeSetterBiConsumers.put(
			"column1",
			(BiConsumer<ERCCompanyEntry, Integer>)ERCCompanyEntry::setColumn1);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getErcCompanyEntryId() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setErcCompanyEntryId(long ercCompanyEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ercCompanyEntryId = ercCompanyEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public int getColumn1() {
		return _column1;
	}

	@Override
	public void setColumn1(int column1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_column1 = column1;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ERCCompanyEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ERCCompanyEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ERCCompanyEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ERCCompanyEntryImpl ercCompanyEntryImpl = new ERCCompanyEntryImpl();

		ercCompanyEntryImpl.setUuid(getUuid());
		ercCompanyEntryImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		ercCompanyEntryImpl.setErcCompanyEntryId(getErcCompanyEntryId());
		ercCompanyEntryImpl.setCompanyId(getCompanyId());
		ercCompanyEntryImpl.setUserId(getUserId());
		ercCompanyEntryImpl.setUserName(getUserName());
		ercCompanyEntryImpl.setColumn1(getColumn1());

		ercCompanyEntryImpl.resetOriginalValues();

		return ercCompanyEntryImpl;
	}

	@Override
	public int compareTo(ERCCompanyEntry ercCompanyEntry) {
		long primaryKey = ercCompanyEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ERCCompanyEntry)) {
			return false;
		}

		ERCCompanyEntry ercCompanyEntry = (ERCCompanyEntry)object;

		long primaryKey = ercCompanyEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ERCCompanyEntry> toCacheModel() {
		ERCCompanyEntryCacheModel ercCompanyEntryCacheModel =
			new ERCCompanyEntryCacheModel();

		ercCompanyEntryCacheModel.uuid = getUuid();

		String uuid = ercCompanyEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ercCompanyEntryCacheModel.uuid = null;
		}

		ercCompanyEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			ercCompanyEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			ercCompanyEntryCacheModel.externalReferenceCode = null;
		}

		ercCompanyEntryCacheModel.ercCompanyEntryId = getErcCompanyEntryId();

		ercCompanyEntryCacheModel.companyId = getCompanyId();

		ercCompanyEntryCacheModel.userId = getUserId();

		ercCompanyEntryCacheModel.userName = getUserName();

		String userName = ercCompanyEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ercCompanyEntryCacheModel.userName = null;
		}

		ercCompanyEntryCacheModel.column1 = getColumn1();

		return ercCompanyEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ERCCompanyEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ERCCompanyEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ERCCompanyEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ERCCompanyEntry.class, ModelWrapper.class);

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _ercCompanyEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private int _column1;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ERCCompanyEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ERCCompanyEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("ercCompanyEntryId", _ercCompanyEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("column1", _column1);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("ercCompanyEntryId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("column1", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ERCCompanyEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1270657182