/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat730.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat730.model.LikeFinderEntry;
import com.liferay.portal.tools.service.builder.test.compat730.model.LikeFinderEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LikeFinderEntry service. Represents a row in the &quot;LikeFinderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LikeFinderEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LikeFinderEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LikeFinderEntryImpl
 * @generated
 */
public class LikeFinderEntryModelImpl
	extends BaseModelImpl<LikeFinderEntry> implements LikeFinderEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a like finder entry model instance should use the <code>LikeFinderEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "LikeFinderEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"likeFinderEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"ownerId", Types.BIGINT}, {"ownerType", Types.INTEGER},
		{"portletId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("likeFinderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ownerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ownerType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("portletId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LikeFinderEntry (likeFinderEntryId LONG not null primary key,companyId LONG,ownerId LONG,ownerType INTEGER,portletId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LikeFinderEntry";

	public static final String ENTITY_ALIAS = "likeFinderEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY likeFinderEntry.likeFinderEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LikeFinderEntry.likeFinderEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OWNERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OWNERTYPE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PORTLETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LIKEFINDERENTRYID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat730.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat730.model.LikeFinderEntry"));

	public LikeFinderEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _likeFinderEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLikeFinderEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _likeFinderEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LikeFinderEntry.class;
	}

	@Override
	public String getModelClassName() {
		return LikeFinderEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LikeFinderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LikeFinderEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LikeFinderEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LikeFinderEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LikeFinderEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LikeFinderEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LikeFinderEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LikeFinderEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LikeFinderEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LikeFinderEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<LikeFinderEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<LikeFinderEntry, Object>>();

		attributeGetterFunctions.put(
			"likeFinderEntryId", LikeFinderEntry::getLikeFinderEntryId);
		attributeGetterFunctions.put(
			"companyId", LikeFinderEntry::getCompanyId);
		attributeGetterFunctions.put("ownerId", LikeFinderEntry::getOwnerId);
		attributeGetterFunctions.put(
			"ownerType", LikeFinderEntry::getOwnerType);
		attributeGetterFunctions.put(
			"portletId", LikeFinderEntry::getPortletId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<LikeFinderEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<LikeFinderEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LikeFinderEntry, ?>>();

		attributeSetterBiConsumers.put(
			"likeFinderEntryId",
			(BiConsumer<LikeFinderEntry, Long>)
				LikeFinderEntry::setLikeFinderEntryId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LikeFinderEntry, Long>)LikeFinderEntry::setCompanyId);
		attributeSetterBiConsumers.put(
			"ownerId",
			(BiConsumer<LikeFinderEntry, Long>)LikeFinderEntry::setOwnerId);
		attributeSetterBiConsumers.put(
			"ownerType",
			(BiConsumer<LikeFinderEntry, Integer>)
				LikeFinderEntry::setOwnerType);
		attributeSetterBiConsumers.put(
			"portletId",
			(BiConsumer<LikeFinderEntry, String>)LikeFinderEntry::setPortletId);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLikeFinderEntryId() {
		return _likeFinderEntryId;
	}

	@Override
	public void setLikeFinderEntryId(long likeFinderEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_likeFinderEntryId = likeFinderEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getOwnerId() {
		return _ownerId;
	}

	@Override
	public void setOwnerId(long ownerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ownerId = ownerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalOwnerId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("ownerId"));
	}

	@Override
	public int getOwnerType() {
		return _ownerType;
	}

	@Override
	public void setOwnerType(int ownerType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ownerType = ownerType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalOwnerType() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("ownerType"));
	}

	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return "";
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_portletId = portletId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPortletId() {
		return getColumnOriginalValue("portletId");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LikeFinderEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LikeFinderEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LikeFinderEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LikeFinderEntryImpl likeFinderEntryImpl = new LikeFinderEntryImpl();

		likeFinderEntryImpl.setLikeFinderEntryId(getLikeFinderEntryId());
		likeFinderEntryImpl.setCompanyId(getCompanyId());
		likeFinderEntryImpl.setOwnerId(getOwnerId());
		likeFinderEntryImpl.setOwnerType(getOwnerType());
		likeFinderEntryImpl.setPortletId(getPortletId());

		likeFinderEntryImpl.resetOriginalValues();

		return likeFinderEntryImpl;
	}

	@Override
	public int compareTo(LikeFinderEntry likeFinderEntry) {
		long primaryKey = likeFinderEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LikeFinderEntry)) {
			return false;
		}

		LikeFinderEntry likeFinderEntry = (LikeFinderEntry)object;

		long primaryKey = likeFinderEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LikeFinderEntry> toCacheModel() {
		LikeFinderEntryCacheModel likeFinderEntryCacheModel =
			new LikeFinderEntryCacheModel();

		likeFinderEntryCacheModel.likeFinderEntryId = getLikeFinderEntryId();

		likeFinderEntryCacheModel.companyId = getCompanyId();

		likeFinderEntryCacheModel.ownerId = getOwnerId();

		likeFinderEntryCacheModel.ownerType = getOwnerType();

		likeFinderEntryCacheModel.portletId = getPortletId();

		String portletId = likeFinderEntryCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			likeFinderEntryCacheModel.portletId = null;
		}

		return likeFinderEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LikeFinderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LikeFinderEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LikeFinderEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LikeFinderEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LikeFinderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LikeFinderEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LikeFinderEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LikeFinderEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LikeFinderEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LikeFinderEntry.class, ModelWrapper.class);

	}

	private long _likeFinderEntryId;
	private long _companyId;
	private long _ownerId;
	private int _ownerType;
	private String _portletId;

	public <T> T getColumnValue(String columnName) {
		Function<LikeFinderEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LikeFinderEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("likeFinderEntryId", _likeFinderEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("ownerId", _ownerId);
		_columnOriginalValues.put("ownerType", _ownerType);
		_columnOriginalValues.put("portletId", _portletId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("likeFinderEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("ownerId", 4L);

		columnBitmasks.put("ownerType", 8L);

		columnBitmasks.put("portletId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LikeFinderEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1331873872