#
# OAuth
#

liferay-one-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_ONE_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-one-etc-spring-boot-oahs,\
    liferay-one-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081
spring.messages.basename=content/Language
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false