#
# Application
#

liferay.one.jira.api.email.address=${LIFERAY_ONE_JIRA_API_EMAIL_ADDRESS}
liferay.one.jira.api.token=${LIFERAY_ONE_JIRA_API_TOKEN}
liferay.one.jira.business.event.asset.object.type.attribute.account=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_ACCOUNT}
liferay.one.jira.business.event.asset.object.type.attribute.actual.event.date=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_ACTUAL_EVENT_DATE}
liferay.one.jira.business.event.asset.object.type.attribute.associated.tickets=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_ASSOCIATED_TICKETS}
liferay.one.jira.business.event.asset.object.type.attribute.author=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_AUTHOR}
liferay.one.jira.business.event.asset.object.type.attribute.current.version=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_CURRENT_VERSION}
liferay.one.jira.business.event.asset.object.type.attribute.description=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_DESCRIPTION}
liferay.one.jira.business.event.asset.object.type.attribute.event.status=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_EVENT_STATUS}
liferay.one.jira.business.event.asset.object.type.attribute.event.type=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_EVENT_TYPE}
liferay.one.jira.business.event.asset.object.type.attribute.last.comment=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_LAST_COMMENT}
liferay.one.jira.business.event.asset.object.type.attribute.last.updated.author=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_LAST_UPDATED_AUTHOR}
liferay.one.jira.business.event.asset.object.type.attribute.name=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_NAME}
liferay.one.jira.business.event.asset.object.type.attribute.new.version=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_NEW_VERSION}
liferay.one.jira.business.event.asset.object.type.attribute.planned.event.date=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_PLANNED_EVENT_DATE}
liferay.one.jira.business.event.asset.object.type.attribute.time.zone=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ATTRIBUTE_TIME_ZONE}
liferay.one.jira.business.event.asset.object.type.id=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_ASSET_OBJECT_TYPE_ID}
liferay.one.jira.business.event.version.asset.object.type.attribute.author=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_VERSION_ASSET_OBJECT_TYPE_ATTRIBUTE_AUTHOR}
liferay.one.jira.business.event.version.asset.object.type.attribute.change=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_VERSION_ASSET_OBJECT_TYPE_ATTRIBUTE_CHANGE}
liferay.one.jira.business.event.version.asset.object.type.attribute.comment=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_VERSION_ASSET_OBJECT_TYPE_ATTRIBUTE_COMMENT}
liferay.one.jira.business.event.version.asset.object.type.attribute.created=${LIFERAY_ONE_JIRA_BUSINESS_EVENT_VERSION_ASSET_OBJECT_TYPE_ATTRIBUTE_CREATED}
liferay.one.jira.support.fls.portal.url=${LIFERAY_ONE_JIRA_SUPPORT_FLS_PORTAL_URL}
liferay.one.jira.support.fls.project=${LIFERAY_ONE_JIRA_SUPPORT_FLS_PROJECT}
liferay.one.jira.support.hc.field.request.type=${LIFERAY_ONE_JIRA_SUPPORT_HC_FIELD_REQUEST_TYPE}
liferay.one.jira.support.hc.portal.url=${LIFERAY_ONE_JIRA_SUPPORT_HC_PORTAL_URL}
liferay.one.jira.url=${LIFERAY_ONE_JIRA_URL}
liferay.one.jira.workspace.id=${LIFERAY_ONE_JIRA_WORKSPACE_ID}

#
# OAuth
#

liferay-one-etc-spring-boot-oahs.oauth2.headless.server.client.secret=${LIFERAY_ONE_ETC_SPRING_BOOT_OAHS_CLIENT_SECRET:myfancypassword}

liferay.oauth.application.external.reference.codes=\
    liferay-one-etc-spring-boot-oahs,\
    liferay-one-etc-spring-boot-oaua

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081
spring.messages.basename=content/Language
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false