/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat720.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntry;
import com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ERCGroupEntry service. Represents a row in the &quot;ERCGroupEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ERCGroupEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ERCGroupEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ERCGroupEntryImpl
 * @generated
 */
public class ERCGroupEntryModelImpl
	extends BaseModelImpl<ERCGroupEntry> implements ERCGroupEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a erc group entry model instance should use the <code>ERCGroupEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ERCGroupEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"ercGroupEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ercGroupEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ERCGroupEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,ercGroupEntryId LONG not null primary key,groupId LONG,companyId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ERCGroupEntry";

	public static final String ENTITY_ALIAS = "ercGroupEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ercGroupEntry.ercGroupEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ERCGroupEntry.ercGroupEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntry"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ERCGROUPENTRYID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat720.model.ERCGroupEntry"));

	public ERCGroupEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ercGroupEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setErcGroupEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ercGroupEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ERCGroupEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ERCGroupEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ERCGroupEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ERCGroupEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCGroupEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ERCGroupEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ERCGroupEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ERCGroupEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ERCGroupEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ERCGroupEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ERCGroupEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ERCGroupEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ERCGroupEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ERCGroupEntry, Object>>();

		attributeGetterFunctions.put("uuid", ERCGroupEntry::getUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", ERCGroupEntry::getExternalReferenceCode);
		attributeGetterFunctions.put(
			"ercGroupEntryId", ERCGroupEntry::getErcGroupEntryId);
		attributeGetterFunctions.put("groupId", ERCGroupEntry::getGroupId);
		attributeGetterFunctions.put("companyId", ERCGroupEntry::getCompanyId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ERCGroupEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ERCGroupEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ERCGroupEntry, ?>>();

		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ERCGroupEntry, String>)ERCGroupEntry::setUuid);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<ERCGroupEntry, String>)
				ERCGroupEntry::setExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"ercGroupEntryId",
			(BiConsumer<ERCGroupEntry, Long>)ERCGroupEntry::setErcGroupEntryId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ERCGroupEntry, Long>)ERCGroupEntry::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ERCGroupEntry, Long>)ERCGroupEntry::setCompanyId);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		_columnBitmask |= EXTERNALREFERENCECODE_COLUMN_BITMASK;

		if (_originalExternalReferenceCode == null) {
			_originalExternalReferenceCode = _externalReferenceCode;
		}

		_externalReferenceCode = externalReferenceCode;
	}

	public String getOriginalExternalReferenceCode() {
		return GetterUtil.getString(_originalExternalReferenceCode);
	}

	@Override
	public long getErcGroupEntryId() {
		return _ercGroupEntryId;
	}

	@Override
	public void setErcGroupEntryId(long ercGroupEntryId) {
		_ercGroupEntryId = ercGroupEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ERCGroupEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ERCGroupEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ERCGroupEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ERCGroupEntryImpl ercGroupEntryImpl = new ERCGroupEntryImpl();

		ercGroupEntryImpl.setUuid(getUuid());
		ercGroupEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		ercGroupEntryImpl.setErcGroupEntryId(getErcGroupEntryId());
		ercGroupEntryImpl.setGroupId(getGroupId());
		ercGroupEntryImpl.setCompanyId(getCompanyId());

		ercGroupEntryImpl.resetOriginalValues();

		return ercGroupEntryImpl;
	}

	@Override
	public int compareTo(ERCGroupEntry ercGroupEntry) {
		long primaryKey = ercGroupEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ERCGroupEntry)) {
			return false;
		}

		ERCGroupEntry ercGroupEntry = (ERCGroupEntry)object;

		long primaryKey = ercGroupEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalExternalReferenceCode = _externalReferenceCode;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ERCGroupEntry> toCacheModel() {
		ERCGroupEntryCacheModel ercGroupEntryCacheModel =
			new ERCGroupEntryCacheModel();

		ercGroupEntryCacheModel.uuid = getUuid();

		String uuid = ercGroupEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ercGroupEntryCacheModel.uuid = null;
		}

		ercGroupEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			ercGroupEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			ercGroupEntryCacheModel.externalReferenceCode = null;
		}

		ercGroupEntryCacheModel.ercGroupEntryId = getErcGroupEntryId();

		ercGroupEntryCacheModel.groupId = getGroupId();

		ercGroupEntryCacheModel.companyId = getCompanyId();

		return ercGroupEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ERCGroupEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ERCGroupEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCGroupEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ERCGroupEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ERCGroupEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ERCGroupEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCGroupEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ERCGroupEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ERCGroupEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ERCGroupEntry.class, ModelWrapper.class);

	}

	private String _uuid;
	private String _originalUuid;
	private String _externalReferenceCode;
	private String _originalExternalReferenceCode;
	private long _ercGroupEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _columnBitmask;
	private ERCGroupEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1001734356