/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat720.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntry;
import com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ERCVersionedEntry service. Represents a row in the &quot;ERCVersionedEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ERCVersionedEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ERCVersionedEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ERCVersionedEntryImpl
 * @generated
 */
public class ERCVersionedEntryModelImpl
	extends BaseModelImpl<ERCVersionedEntry> implements ERCVersionedEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a erc versioned entry model instance should use the <code>ERCVersionedEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ERCVersionedEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"ercVersionedEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ercVersionedEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ERCVersionedEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,ercVersionedEntryId LONG not null primary key,groupId LONG,companyId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ERCVersionedEntry";

	public static final String ENTITY_ALIAS = "ercVersionedEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ercVersionedEntry.ercVersionedEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ERCVersionedEntry.ercVersionedEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntry"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ERCVERSIONEDENTRYID_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat720.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat720.model.ERCVersionedEntry"));

	public ERCVersionedEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ercVersionedEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setErcVersionedEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ercVersionedEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ERCVersionedEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ERCVersionedEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ERCVersionedEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ERCVersionedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCVersionedEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ERCVersionedEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ERCVersionedEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ERCVersionedEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ERCVersionedEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ERCVersionedEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ERCVersionedEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ERCVersionedEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ERCVersionedEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ERCVersionedEntry, Object>>();

		attributeGetterFunctions.put("uuid", ERCVersionedEntry::getUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode",
			ERCVersionedEntry::getExternalReferenceCode);
		attributeGetterFunctions.put(
			"ercVersionedEntryId", ERCVersionedEntry::getErcVersionedEntryId);
		attributeGetterFunctions.put("groupId", ERCVersionedEntry::getGroupId);
		attributeGetterFunctions.put(
			"companyId", ERCVersionedEntry::getCompanyId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ERCVersionedEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ERCVersionedEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ERCVersionedEntry, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<ERCVersionedEntry, String>)ERCVersionedEntry::setUuid);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<ERCVersionedEntry, String>)
				ERCVersionedEntry::setExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"ercVersionedEntryId",
			(BiConsumer<ERCVersionedEntry, Long>)
				ERCVersionedEntry::setErcVersionedEntryId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ERCVersionedEntry, Long>)ERCVersionedEntry::setGroupId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ERCVersionedEntry, Long>)
				ERCVersionedEntry::setCompanyId);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		_columnBitmask |= EXTERNALREFERENCECODE_COLUMN_BITMASK;

		if (_originalExternalReferenceCode == null) {
			_originalExternalReferenceCode = _externalReferenceCode;
		}

		_externalReferenceCode = externalReferenceCode;
	}

	public String getOriginalExternalReferenceCode() {
		return GetterUtil.getString(_originalExternalReferenceCode);
	}

	@Override
	public long getErcVersionedEntryId() {
		return _ercVersionedEntryId;
	}

	@Override
	public void setErcVersionedEntryId(long ercVersionedEntryId) {
		_ercVersionedEntryId = ercVersionedEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ERCVersionedEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ERCVersionedEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ERCVersionedEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ERCVersionedEntryImpl ercVersionedEntryImpl =
			new ERCVersionedEntryImpl();

		ercVersionedEntryImpl.setUuid(getUuid());
		ercVersionedEntryImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		ercVersionedEntryImpl.setErcVersionedEntryId(getErcVersionedEntryId());
		ercVersionedEntryImpl.setGroupId(getGroupId());
		ercVersionedEntryImpl.setCompanyId(getCompanyId());

		ercVersionedEntryImpl.resetOriginalValues();

		return ercVersionedEntryImpl;
	}

	@Override
	public int compareTo(ERCVersionedEntry ercVersionedEntry) {
		long primaryKey = ercVersionedEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ERCVersionedEntry)) {
			return false;
		}

		ERCVersionedEntry ercVersionedEntry = (ERCVersionedEntry)object;

		long primaryKey = ercVersionedEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalExternalReferenceCode = _externalReferenceCode;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ERCVersionedEntry> toCacheModel() {
		ERCVersionedEntryCacheModel ercVersionedEntryCacheModel =
			new ERCVersionedEntryCacheModel();

		ercVersionedEntryCacheModel.uuid = getUuid();

		String uuid = ercVersionedEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ercVersionedEntryCacheModel.uuid = null;
		}

		ercVersionedEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			ercVersionedEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			ercVersionedEntryCacheModel.externalReferenceCode = null;
		}

		ercVersionedEntryCacheModel.ercVersionedEntryId =
			getErcVersionedEntryId();

		ercVersionedEntryCacheModel.groupId = getGroupId();

		ercVersionedEntryCacheModel.companyId = getCompanyId();

		return ercVersionedEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ERCVersionedEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ERCVersionedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCVersionedEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ERCVersionedEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ERCVersionedEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ERCVersionedEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCVersionedEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ERCVersionedEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ERCVersionedEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ERCVersionedEntry.class, ModelWrapper.class);

	}

	private String _uuid;
	private String _originalUuid;
	private String _externalReferenceCode;
	private String _originalExternalReferenceCode;
	private long _ercVersionedEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _columnBitmask;
	private ERCVersionedEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-211898844