/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.EagerBlobEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.EagerBlobEntryModel;
import com.liferay.portal.tools.service.builder.test.compat710.model.EagerBlobEntrySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EagerBlobEntry service. Represents a row in the &quot;EagerBlobEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EagerBlobEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EagerBlobEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerBlobEntryImpl
 * @generated
 */
@JSON(strict = true)
public class EagerBlobEntryModelImpl
	extends BaseModelImpl<EagerBlobEntry> implements EagerBlobEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a eager blob entry model instance should use the <code>EagerBlobEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "EagerBlobEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"eagerBlobEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"blob_", Types.BLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eagerBlobEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("blob_", Types.BLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table EagerBlobEntry (uuid_ VARCHAR(75) null,eagerBlobEntryId LONG not null primary key,groupId LONG,blob_ BLOB)";

	public static final String TABLE_SQL_DROP = "drop table EagerBlobEntry";

	public static final String ENTITY_ALIAS = "eagerBlobEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eagerBlobEntry.eagerBlobEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY EagerBlobEntry.eagerBlobEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = false;

	public static final boolean FINDER_CACHE_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EagerBlobEntry toModel(EagerBlobEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EagerBlobEntry model = new EagerBlobEntryImpl();

		model.setUuid(soapModel.getUuid());
		model.setEagerBlobEntryId(soapModel.getEagerBlobEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setBlob(soapModel.getBlob());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EagerBlobEntry> toModels(
		EagerBlobEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EagerBlobEntry> models = new ArrayList<EagerBlobEntry>(
			soapModels.length);

		for (EagerBlobEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.EagerBlobEntry"));

	public EagerBlobEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eagerBlobEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEagerBlobEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eagerBlobEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EagerBlobEntry.class;
	}

	@Override
	public String getModelClassName() {
		return EagerBlobEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EagerBlobEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EagerBlobEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EagerBlobEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EagerBlobEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EagerBlobEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EagerBlobEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EagerBlobEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EagerBlobEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EagerBlobEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EagerBlobEntry.class.getClassLoader(), EagerBlobEntry.class,
			ModelWrapper.class);

		try {
			Constructor<EagerBlobEntry> constructor =
				(Constructor<EagerBlobEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<EagerBlobEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<EagerBlobEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EagerBlobEntry, Object>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<EagerBlobEntry, Object>() {

				@Override
				public Object apply(EagerBlobEntry eagerBlobEntry) {
					return eagerBlobEntry.getUuid();
				}

			});
		attributeGetterFunctions.put(
			"eagerBlobEntryId",
			new Function<EagerBlobEntry, Object>() {

				@Override
				public Object apply(EagerBlobEntry eagerBlobEntry) {
					return eagerBlobEntry.getEagerBlobEntryId();
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<EagerBlobEntry, Object>() {

				@Override
				public Object apply(EagerBlobEntry eagerBlobEntry) {
					return eagerBlobEntry.getGroupId();
				}

			});
		attributeGetterFunctions.put(
			"blob",
			new Function<EagerBlobEntry, Object>() {

				@Override
				public Object apply(EagerBlobEntry eagerBlobEntry) {
					return eagerBlobEntry.getBlob();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<EagerBlobEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<EagerBlobEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EagerBlobEntry, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<EagerBlobEntry, Object>() {

				@Override
				public void accept(
					EagerBlobEntry eagerBlobEntry, Object uuidObject) {

					eagerBlobEntry.setUuid((String)uuidObject);
				}

			});
		attributeSetterBiConsumers.put(
			"eagerBlobEntryId",
			new BiConsumer<EagerBlobEntry, Object>() {

				@Override
				public void accept(
					EagerBlobEntry eagerBlobEntry,
					Object eagerBlobEntryIdObject) {

					eagerBlobEntry.setEagerBlobEntryId(
						(Long)eagerBlobEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<EagerBlobEntry, Object>() {

				@Override
				public void accept(
					EagerBlobEntry eagerBlobEntry, Object groupIdObject) {

					eagerBlobEntry.setGroupId((Long)groupIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"blob",
			new BiConsumer<EagerBlobEntry, Object>() {

				@Override
				public void accept(
					EagerBlobEntry eagerBlobEntry, Object blobObject) {

					eagerBlobEntry.setBlob((Blob)blobObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEagerBlobEntryId() {
		return _eagerBlobEntryId;
	}

	@Override
	public void setEagerBlobEntryId(long eagerBlobEntryId) {
		_eagerBlobEntryId = eagerBlobEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public Blob getBlob() {
		return _blob;
	}

	@Override
	public void setBlob(Blob blob) {
		_blob = blob;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, EagerBlobEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EagerBlobEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EagerBlobEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EagerBlobEntryImpl eagerBlobEntryImpl = new EagerBlobEntryImpl();

		eagerBlobEntryImpl.setUuid(getUuid());
		eagerBlobEntryImpl.setEagerBlobEntryId(getEagerBlobEntryId());
		eagerBlobEntryImpl.setGroupId(getGroupId());

		eagerBlobEntryImpl.resetOriginalValues();

		return eagerBlobEntryImpl;
	}

	@Override
	public int compareTo(EagerBlobEntry eagerBlobEntry) {
		long primaryKey = eagerBlobEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EagerBlobEntry)) {
			return false;
		}

		EagerBlobEntry eagerBlobEntry = (EagerBlobEntry)object;

		long primaryKey = eagerBlobEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalGroupId = _groupId;

		_setOriginalGroupId = false;
	}

	@Override
	public CacheModel<EagerBlobEntry> toCacheModel() {
		EagerBlobEntryCacheModel eagerBlobEntryCacheModel =
			new EagerBlobEntryCacheModel();

		eagerBlobEntryCacheModel.uuid = getUuid();

		String uuid = eagerBlobEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eagerBlobEntryCacheModel.uuid = null;
		}

		eagerBlobEntryCacheModel.eagerBlobEntryId = getEagerBlobEntryId();

		eagerBlobEntryCacheModel.groupId = getGroupId();

		return eagerBlobEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EagerBlobEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EagerBlobEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EagerBlobEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EagerBlobEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EagerBlobEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EagerBlobEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EagerBlobEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EagerBlobEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _eagerBlobEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Blob _blob;
	private EagerBlobEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:442623225