/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ERCCompanyEntry service. Represents a row in the &quot;ERCCompanyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ERCCompanyEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ERCCompanyEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ERCCompanyEntryImpl
 * @generated
 */
public class ERCCompanyEntryModelImpl
	extends BaseModelImpl<ERCCompanyEntry> implements ERCCompanyEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a erc company entry model instance should use the <code>ERCCompanyEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ERCCompanyEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"ercCompanyEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"column1", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ercCompanyEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("column1", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ERCCompanyEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,ercCompanyEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,column1 INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table ERCCompanyEntry";

	public static final String ENTITY_ALIAS = "ercCompanyEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ercCompanyEntry.ercCompanyEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ERCCompanyEntry.ercCompanyEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntry"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ERCCOMPANYENTRYID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.ERCCompanyEntry"));

	public ERCCompanyEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setErcCompanyEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ERCCompanyEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ERCCompanyEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ERCCompanyEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ERCCompanyEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ERCCompanyEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ERCCompanyEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ERCCompanyEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ERCCompanyEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ERCCompanyEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ERCCompanyEntry.class.getClassLoader(), ERCCompanyEntry.class,
			ModelWrapper.class);

		try {
			Constructor<ERCCompanyEntry> constructor =
				(Constructor<ERCCompanyEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ERCCompanyEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ERCCompanyEntry, Object>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getUuid();
				}

			});
		attributeGetterFunctions.put(
			"externalReferenceCode",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getExternalReferenceCode();
				}

			});
		attributeGetterFunctions.put(
			"ercCompanyEntryId",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getErcCompanyEntryId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getUserId();
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getUserName();
				}

			});
		attributeGetterFunctions.put(
			"column1",
			new Function<ERCCompanyEntry, Object>() {

				@Override
				public Object apply(ERCCompanyEntry ercCompanyEntry) {
					return ercCompanyEntry.getColumn1();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ERCCompanyEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ERCCompanyEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ERCCompanyEntry, ?>>();

		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry, Object uuidObject) {

					ercCompanyEntry.setUuid((String)uuidObject);
				}

			});
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry,
					Object externalReferenceCodeObject) {

					ercCompanyEntry.setExternalReferenceCode(
						(String)externalReferenceCodeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"ercCompanyEntryId",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry,
					Object ercCompanyEntryIdObject) {

					ercCompanyEntry.setErcCompanyEntryId(
						(Long)ercCompanyEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry, Object companyIdObject) {

					ercCompanyEntry.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry, Object userIdObject) {

					ercCompanyEntry.setUserId((Long)userIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry, Object userNameObject) {

					ercCompanyEntry.setUserName((String)userNameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"column1",
			new BiConsumer<ERCCompanyEntry, Object>() {

				@Override
				public void accept(
					ERCCompanyEntry ercCompanyEntry, Object column1Object) {

					ercCompanyEntry.setColumn1((Integer)column1Object);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		_columnBitmask |= EXTERNALREFERENCECODE_COLUMN_BITMASK;

		if (_originalExternalReferenceCode == null) {
			_originalExternalReferenceCode = _externalReferenceCode;
		}

		_externalReferenceCode = externalReferenceCode;
	}

	public String getOriginalExternalReferenceCode() {
		return GetterUtil.getString(_originalExternalReferenceCode);
	}

	@Override
	public long getErcCompanyEntryId() {
		return _ercCompanyEntryId;
	}

	@Override
	public void setErcCompanyEntryId(long ercCompanyEntryId) {
		_ercCompanyEntryId = ercCompanyEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public int getColumn1() {
		return _column1;
	}

	@Override
	public void setColumn1(int column1) {
		_column1 = column1;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ERCCompanyEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ERCCompanyEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ERCCompanyEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ERCCompanyEntryImpl ercCompanyEntryImpl = new ERCCompanyEntryImpl();

		ercCompanyEntryImpl.setUuid(getUuid());
		ercCompanyEntryImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		ercCompanyEntryImpl.setErcCompanyEntryId(getErcCompanyEntryId());
		ercCompanyEntryImpl.setCompanyId(getCompanyId());
		ercCompanyEntryImpl.setUserId(getUserId());
		ercCompanyEntryImpl.setUserName(getUserName());
		ercCompanyEntryImpl.setColumn1(getColumn1());

		ercCompanyEntryImpl.resetOriginalValues();

		return ercCompanyEntryImpl;
	}

	@Override
	public int compareTo(ERCCompanyEntry ercCompanyEntry) {
		long primaryKey = ercCompanyEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ERCCompanyEntry)) {
			return false;
		}

		ERCCompanyEntry ercCompanyEntry = (ERCCompanyEntry)object;

		long primaryKey = ercCompanyEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalExternalReferenceCode = _externalReferenceCode;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ERCCompanyEntry> toCacheModel() {
		ERCCompanyEntryCacheModel ercCompanyEntryCacheModel =
			new ERCCompanyEntryCacheModel();

		ercCompanyEntryCacheModel.uuid = getUuid();

		String uuid = ercCompanyEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ercCompanyEntryCacheModel.uuid = null;
		}

		ercCompanyEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			ercCompanyEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			ercCompanyEntryCacheModel.externalReferenceCode = null;
		}

		ercCompanyEntryCacheModel.ercCompanyEntryId = getErcCompanyEntryId();

		ercCompanyEntryCacheModel.companyId = getCompanyId();

		ercCompanyEntryCacheModel.userId = getUserId();

		ercCompanyEntryCacheModel.userName = getUserName();

		String userName = ercCompanyEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ercCompanyEntryCacheModel.userName = null;
		}

		ercCompanyEntryCacheModel.column1 = getColumn1();

		return ercCompanyEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ERCCompanyEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ERCCompanyEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ERCCompanyEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ERCCompanyEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ERCCompanyEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ERCCompanyEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private String _externalReferenceCode;
	private String _originalExternalReferenceCode;
	private long _ercCompanyEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private int _column1;
	private long _columnBitmask;
	private ERCCompanyEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1081026473