/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.MappingEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.MappingEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MappingEntry service. Represents a row in the &quot;MappingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MappingEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MappingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MappingEntryImpl
 * @generated
 */
public class MappingEntryModelImpl
	extends BaseModelImpl<MappingEntry> implements MappingEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mapping entry model instance should use the <code>MappingEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "MappingEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mappingEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mappingEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MappingEntry (mappingEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MappingEntry";

	public static final String ENTITY_ALIAS = "mappingEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mappingEntry.mappingEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MappingEntry.mappingEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.MappingEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.MappingEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final String MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_NAME =
		"MappingEntries_BasicEntries";

	public static final Object[][]
		MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"basicEntryId", Types.BIGINT},
			{"mappingEntryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_SQL_CREATE =
			"create table MappingEntries_BasicEntries (companyId LONG not null,basicEntryId LONG not null,mappingEntryId LONG not null,primary key (basicEntryId, mappingEntryId))";

	public static final boolean
		FINDER_CACHE_ENABLED_MAPPINGENTRIES_BASICENTRIES =
			GetterUtil.getBoolean(
				com.liferay.portal.tools.service.builder.test.compat710.service.
					util.ServiceProps.get(
						"value.object.finder.cache.enabled.MappingEntries_BasicEntries"),
				true);

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.MappingEntry"));

	public MappingEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mappingEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMappingEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mappingEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MappingEntry.class;
	}

	@Override
	public String getModelClassName() {
		return MappingEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MappingEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MappingEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MappingEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MappingEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MappingEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MappingEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MappingEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MappingEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, MappingEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			MappingEntry.class.getClassLoader(), MappingEntry.class,
			ModelWrapper.class);

		try {
			Constructor<MappingEntry> constructor =
				(Constructor<MappingEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<MappingEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MappingEntry, Object>>();

		attributeGetterFunctions.put(
			"mappingEntryId",
			new Function<MappingEntry, Object>() {

				@Override
				public Object apply(MappingEntry mappingEntry) {
					return mappingEntry.getMappingEntryId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<MappingEntry, Object>() {

				@Override
				public Object apply(MappingEntry mappingEntry) {
					return mappingEntry.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<MappingEntry, Object>() {

				@Override
				public Object apply(MappingEntry mappingEntry) {
					return mappingEntry.getName();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<MappingEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<MappingEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MappingEntry, ?>>();

		attributeSetterBiConsumers.put(
			"mappingEntryId",
			new BiConsumer<MappingEntry, Object>() {

				@Override
				public void accept(
					MappingEntry mappingEntry, Object mappingEntryIdObject) {

					mappingEntry.setMappingEntryId((Long)mappingEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<MappingEntry, Object>() {

				@Override
				public void accept(
					MappingEntry mappingEntry, Object companyIdObject) {

					mappingEntry.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<MappingEntry, Object>() {

				@Override
				public void accept(
					MappingEntry mappingEntry, Object nameObject) {

					mappingEntry.setName((String)nameObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMappingEntryId() {
		return _mappingEntryId;
	}

	@Override
	public void setMappingEntryId(long mappingEntryId) {
		_mappingEntryId = mappingEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MappingEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MappingEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MappingEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MappingEntryImpl mappingEntryImpl = new MappingEntryImpl();

		mappingEntryImpl.setMappingEntryId(getMappingEntryId());
		mappingEntryImpl.setCompanyId(getCompanyId());
		mappingEntryImpl.setName(getName());

		mappingEntryImpl.resetOriginalValues();

		return mappingEntryImpl;
	}

	@Override
	public int compareTo(MappingEntry mappingEntry) {
		long primaryKey = mappingEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MappingEntry)) {
			return false;
		}

		MappingEntry mappingEntry = (MappingEntry)object;

		long primaryKey = mappingEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<MappingEntry> toCacheModel() {
		MappingEntryCacheModel mappingEntryCacheModel =
			new MappingEntryCacheModel();

		mappingEntryCacheModel.mappingEntryId = getMappingEntryId();

		mappingEntryCacheModel.companyId = getCompanyId();

		mappingEntryCacheModel.name = getName();

		String name = mappingEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mappingEntryCacheModel.name = null;
		}

		return mappingEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MappingEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MappingEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MappingEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MappingEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MappingEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MappingEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MappingEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mappingEntryId;
	private long _companyId;
	private String _name;
	private MappingEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-490336107