/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MVCCEntry service. Represents a row in the &quot;MVCCEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MVCCEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MVCCEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MVCCEntryImpl
 * @generated
 */
public class MVCCEntryModelImpl
	extends BaseModelImpl<MVCCEntry> implements MVCCEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mvcc entry model instance should use the <code>MVCCEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "MVCCEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"mvccEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mvccEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MVCCEntry (mvccVersion LONG default 0 not null,mvccEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MVCCEntry";

	public static final String ENTITY_ALIAS = "mvccEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mvccEntry.mvccEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MVCCEntry.mvccEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntry"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long NAME_COLUMN_BITMASK = 2L;

	public static final long MVCCENTRYID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.MVCCEntry"));

	public MVCCEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mvccEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMvccEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mvccEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MVCCEntry.class;
	}

	@Override
	public String getModelClassName() {
		return MVCCEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MVCCEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MVCCEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MVCCEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MVCCEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MVCCEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MVCCEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MVCCEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MVCCEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MVCCEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, MVCCEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			MVCCEntry.class.getClassLoader(), MVCCEntry.class,
			ModelWrapper.class);

		try {
			Constructor<MVCCEntry> constructor =
				(Constructor<MVCCEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<MVCCEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<MVCCEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MVCCEntry, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion",
			new Function<MVCCEntry, Object>() {

				@Override
				public Object apply(MVCCEntry mvccEntry) {
					return mvccEntry.getMvccVersion();
				}

			});
		attributeGetterFunctions.put(
			"mvccEntryId",
			new Function<MVCCEntry, Object>() {

				@Override
				public Object apply(MVCCEntry mvccEntry) {
					return mvccEntry.getMvccEntryId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<MVCCEntry, Object>() {

				@Override
				public Object apply(MVCCEntry mvccEntry) {
					return mvccEntry.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<MVCCEntry, Object>() {

				@Override
				public Object apply(MVCCEntry mvccEntry) {
					return mvccEntry.getName();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<MVCCEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<MVCCEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MVCCEntry, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			new BiConsumer<MVCCEntry, Object>() {

				@Override
				public void accept(
					MVCCEntry mvccEntry, Object mvccVersionObject) {

					mvccEntry.setMvccVersion((Long)mvccVersionObject);
				}

			});
		attributeSetterBiConsumers.put(
			"mvccEntryId",
			new BiConsumer<MVCCEntry, Object>() {

				@Override
				public void accept(
					MVCCEntry mvccEntry, Object mvccEntryIdObject) {

					mvccEntry.setMvccEntryId((Long)mvccEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<MVCCEntry, Object>() {

				@Override
				public void accept(
					MVCCEntry mvccEntry, Object companyIdObject) {

					mvccEntry.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<MVCCEntry, Object>() {

				@Override
				public void accept(MVCCEntry mvccEntry, Object nameObject) {
					mvccEntry.setName((String)nameObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getMvccEntryId() {
		return _mvccEntryId;
	}

	@Override
	public void setMvccEntryId(long mvccEntryId) {
		_mvccEntryId = mvccEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MVCCEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MVCCEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MVCCEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MVCCEntryImpl mvccEntryImpl = new MVCCEntryImpl();

		mvccEntryImpl.setMvccVersion(getMvccVersion());
		mvccEntryImpl.setMvccEntryId(getMvccEntryId());
		mvccEntryImpl.setCompanyId(getCompanyId());
		mvccEntryImpl.setName(getName());

		mvccEntryImpl.resetOriginalValues();

		return mvccEntryImpl;
	}

	@Override
	public int compareTo(MVCCEntry mvccEntry) {
		long primaryKey = mvccEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MVCCEntry)) {
			return false;
		}

		MVCCEntry mvccEntry = (MVCCEntry)object;

		long primaryKey = mvccEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalName = _name;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MVCCEntry> toCacheModel() {
		MVCCEntryCacheModel mvccEntryCacheModel = new MVCCEntryCacheModel();

		mvccEntryCacheModel.mvccVersion = getMvccVersion();

		mvccEntryCacheModel.mvccEntryId = getMvccEntryId();

		mvccEntryCacheModel.companyId = getCompanyId();

		mvccEntryCacheModel.name = getName();

		String name = mvccEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mvccEntryCacheModel.name = null;
		}

		return mvccEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MVCCEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MVCCEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MVCCEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MVCCEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MVCCEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MVCCEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MVCCEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MVCCEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MVCCEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _mvccEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private MVCCEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1702512819