/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.TreeEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.TreeEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TreeEntry service. Represents a row in the &quot;TreeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TreeEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TreeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreeEntryImpl
 * @generated
 */
public class TreeEntryModelImpl
	extends BaseModelImpl<TreeEntry> implements TreeEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tree entry model instance should use the <code>TreeEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "TreeEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"treeEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"parentTreeEntryId", Types.BIGINT}, {"leftTreeEntryId", Types.BIGINT},
		{"rightTreeEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("treeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentTreeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leftTreeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rightTreeEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TreeEntry (treeEntryId LONG not null primary key,groupId LONG,parentTreeEntryId LONG,leftTreeEntryId LONG,rightTreeEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table TreeEntry";

	public static final String ENTITY_ALIAS = "treeEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY treeEntry.treeEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TreeEntry.treeEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.TreeEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.TreeEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.TreeEntry"));

	public TreeEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _treeEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTreeEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _treeEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TreeEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TreeEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TreeEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TreeEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreeEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TreeEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TreeEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TreeEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TreeEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TreeEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TreeEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TreeEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TreeEntry.class.getClassLoader(), TreeEntry.class,
			ModelWrapper.class);

		try {
			Constructor<TreeEntry> constructor =
				(Constructor<TreeEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TreeEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<TreeEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TreeEntry, Object>>();

		attributeGetterFunctions.put(
			"treeEntryId",
			new Function<TreeEntry, Object>() {

				@Override
				public Object apply(TreeEntry treeEntry) {
					return treeEntry.getTreeEntryId();
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TreeEntry, Object>() {

				@Override
				public Object apply(TreeEntry treeEntry) {
					return treeEntry.getGroupId();
				}

			});
		attributeGetterFunctions.put(
			"parentTreeEntryId",
			new Function<TreeEntry, Object>() {

				@Override
				public Object apply(TreeEntry treeEntry) {
					return treeEntry.getParentTreeEntryId();
				}

			});
		attributeGetterFunctions.put(
			"leftTreeEntryId",
			new Function<TreeEntry, Object>() {

				@Override
				public Object apply(TreeEntry treeEntry) {
					return treeEntry.getLeftTreeEntryId();
				}

			});
		attributeGetterFunctions.put(
			"rightTreeEntryId",
			new Function<TreeEntry, Object>() {

				@Override
				public Object apply(TreeEntry treeEntry) {
					return treeEntry.getRightTreeEntryId();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<TreeEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<TreeEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TreeEntry, ?>>();

		attributeSetterBiConsumers.put(
			"treeEntryId",
			new BiConsumer<TreeEntry, Object>() {

				@Override
				public void accept(
					TreeEntry treeEntry, Object treeEntryIdObject) {

					treeEntry.setTreeEntryId((Long)treeEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TreeEntry, Object>() {

				@Override
				public void accept(TreeEntry treeEntry, Object groupIdObject) {
					treeEntry.setGroupId((Long)groupIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"parentTreeEntryId",
			new BiConsumer<TreeEntry, Object>() {

				@Override
				public void accept(
					TreeEntry treeEntry, Object parentTreeEntryIdObject) {

					treeEntry.setParentTreeEntryId(
						(Long)parentTreeEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"leftTreeEntryId",
			new BiConsumer<TreeEntry, Object>() {

				@Override
				public void accept(
					TreeEntry treeEntry, Object leftTreeEntryIdObject) {

					treeEntry.setLeftTreeEntryId((Long)leftTreeEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"rightTreeEntryId",
			new BiConsumer<TreeEntry, Object>() {

				@Override
				public void accept(
					TreeEntry treeEntry, Object rightTreeEntryIdObject) {

					treeEntry.setRightTreeEntryId((Long)rightTreeEntryIdObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTreeEntryId() {
		return _treeEntryId;
	}

	@Override
	public void setTreeEntryId(long treeEntryId) {
		_treeEntryId = treeEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getParentTreeEntryId() {
		return _parentTreeEntryId;
	}

	@Override
	public void setParentTreeEntryId(long parentTreeEntryId) {
		if (!_setOriginalParentTreeEntryId) {
			_setOriginalParentTreeEntryId = true;

			_originalParentTreeEntryId = _parentTreeEntryId;
		}

		_parentTreeEntryId = parentTreeEntryId;
	}

	public long getOriginalParentTreeEntryId() {
		return _originalParentTreeEntryId;
	}

	@Override
	public long getLeftTreeEntryId() {
		return _leftTreeEntryId;
	}

	@Override
	public void setLeftTreeEntryId(long leftTreeEntryId) {
		_leftTreeEntryId = leftTreeEntryId;
	}

	@Override
	public long getRightTreeEntryId() {
		return _rightTreeEntryId;
	}

	@Override
	public void setRightTreeEntryId(long rightTreeEntryId) {
		_rightTreeEntryId = rightTreeEntryId;
	}

	public long getNestedSetsTreeNodeLeft() {
		return _leftTreeEntryId;
	}

	public long getNestedSetsTreeNodeRight() {
		return _rightTreeEntryId;
	}

	public long getNestedSetsTreeNodeScopeId() {
		return _groupId;
	}

	public void setNestedSetsTreeNodeLeft(long nestedSetsTreeNodeLeft) {
		_leftTreeEntryId = nestedSetsTreeNodeLeft;
	}

	public void setNestedSetsTreeNodeRight(long nestedSetsTreeNodeRight) {
		_rightTreeEntryId = nestedSetsTreeNodeRight;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TreeEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TreeEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TreeEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TreeEntryImpl treeEntryImpl = new TreeEntryImpl();

		treeEntryImpl.setTreeEntryId(getTreeEntryId());
		treeEntryImpl.setGroupId(getGroupId());
		treeEntryImpl.setParentTreeEntryId(getParentTreeEntryId());
		treeEntryImpl.setLeftTreeEntryId(getLeftTreeEntryId());
		treeEntryImpl.setRightTreeEntryId(getRightTreeEntryId());

		treeEntryImpl.resetOriginalValues();

		return treeEntryImpl;
	}

	@Override
	public int compareTo(TreeEntry treeEntry) {
		long primaryKey = treeEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TreeEntry)) {
			return false;
		}

		TreeEntry treeEntry = (TreeEntry)object;

		long primaryKey = treeEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalParentTreeEntryId = _parentTreeEntryId;

		_setOriginalParentTreeEntryId = false;
	}

	@Override
	public CacheModel<TreeEntry> toCacheModel() {
		TreeEntryCacheModel treeEntryCacheModel = new TreeEntryCacheModel();

		treeEntryCacheModel.treeEntryId = getTreeEntryId();

		treeEntryCacheModel.groupId = getGroupId();

		treeEntryCacheModel.parentTreeEntryId = getParentTreeEntryId();

		treeEntryCacheModel.leftTreeEntryId = getLeftTreeEntryId();

		treeEntryCacheModel.rightTreeEntryId = getRightTreeEntryId();

		return treeEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TreeEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TreeEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreeEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TreeEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TreeEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TreeEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TreeEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TreeEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TreeEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _treeEntryId;
	private long _groupId;
	private long _parentTreeEntryId;
	private long _originalParentTreeEntryId;
	private boolean _setOriginalParentTreeEntryId;
	private long _leftTreeEntryId;
	private long _rightTreeEntryId;
	private TreeEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1243395680