/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat710.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntry;
import com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WhereClauseEntry service. Represents a row in the &quot;WhereClauseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WhereClauseEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WhereClauseEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WhereClauseEntryImpl
 * @generated
 */
public class WhereClauseEntryModelImpl
	extends BaseModelImpl<WhereClauseEntry> implements WhereClauseEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a where clause entry model instance should use the <code>WhereClauseEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "WhereClauseEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"whereClauseEntryId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"nickname", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("whereClauseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nickname", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WhereClauseEntry (whereClauseEntryId LONG not null primary key,name VARCHAR(75) null,nickname VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table WhereClauseEntry";

	public static final String ENTITY_ALIAS = "whereClauseEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY whereClauseEntry.whereClauseEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WhereClauseEntry.whereClauseEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntry"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntry"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntry"),
		true);

	public static final long NAME_COLUMN_BITMASK = 1L;

	public static final long WHERECLAUSEENTRYID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.compat710.service.util.
			ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.compat710.model.WhereClauseEntry"));

	public WhereClauseEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _whereClauseEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWhereClauseEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _whereClauseEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WhereClauseEntry.class;
	}

	@Override
	public String getModelClassName() {
		return WhereClauseEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WhereClauseEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WhereClauseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WhereClauseEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WhereClauseEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WhereClauseEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WhereClauseEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WhereClauseEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WhereClauseEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WhereClauseEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WhereClauseEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WhereClauseEntry.class.getClassLoader(), WhereClauseEntry.class,
			ModelWrapper.class);

		try {
			Constructor<WhereClauseEntry> constructor =
				(Constructor<WhereClauseEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WhereClauseEntry, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<WhereClauseEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<WhereClauseEntry, Object>>();

		attributeGetterFunctions.put(
			"whereClauseEntryId",
			new Function<WhereClauseEntry, Object>() {

				@Override
				public Object apply(WhereClauseEntry whereClauseEntry) {
					return whereClauseEntry.getWhereClauseEntryId();
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WhereClauseEntry, Object>() {

				@Override
				public Object apply(WhereClauseEntry whereClauseEntry) {
					return whereClauseEntry.getName();
				}

			});
		attributeGetterFunctions.put(
			"nickname",
			new Function<WhereClauseEntry, Object>() {

				@Override
				public Object apply(WhereClauseEntry whereClauseEntry) {
					return whereClauseEntry.getNickname();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<WhereClauseEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<WhereClauseEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<WhereClauseEntry, ?>>();

		attributeSetterBiConsumers.put(
			"whereClauseEntryId",
			new BiConsumer<WhereClauseEntry, Object>() {

				@Override
				public void accept(
					WhereClauseEntry whereClauseEntry,
					Object whereClauseEntryIdObject) {

					whereClauseEntry.setWhereClauseEntryId(
						(Long)whereClauseEntryIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WhereClauseEntry, Object>() {

				@Override
				public void accept(
					WhereClauseEntry whereClauseEntry, Object nameObject) {

					whereClauseEntry.setName((String)nameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"nickname",
			new BiConsumer<WhereClauseEntry, Object>() {

				@Override
				public void accept(
					WhereClauseEntry whereClauseEntry, Object nicknameObject) {

					whereClauseEntry.setNickname((String)nicknameObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWhereClauseEntryId() {
		return _whereClauseEntryId;
	}

	@Override
	public void setWhereClauseEntryId(long whereClauseEntryId) {
		_whereClauseEntryId = whereClauseEntryId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getNickname() {
		if (_nickname == null) {
			return "";
		}
		else {
			return _nickname;
		}
	}

	@Override
	public void setNickname(String nickname) {
		_nickname = nickname;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, WhereClauseEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WhereClauseEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WhereClauseEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WhereClauseEntryImpl whereClauseEntryImpl = new WhereClauseEntryImpl();

		whereClauseEntryImpl.setWhereClauseEntryId(getWhereClauseEntryId());
		whereClauseEntryImpl.setName(getName());
		whereClauseEntryImpl.setNickname(getNickname());

		whereClauseEntryImpl.resetOriginalValues();

		return whereClauseEntryImpl;
	}

	@Override
	public int compareTo(WhereClauseEntry whereClauseEntry) {
		long primaryKey = whereClauseEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WhereClauseEntry)) {
			return false;
		}

		WhereClauseEntry whereClauseEntry = (WhereClauseEntry)object;

		long primaryKey = whereClauseEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalName = _name;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<WhereClauseEntry> toCacheModel() {
		WhereClauseEntryCacheModel whereClauseEntryCacheModel =
			new WhereClauseEntryCacheModel();

		whereClauseEntryCacheModel.whereClauseEntryId = getWhereClauseEntryId();

		whereClauseEntryCacheModel.name = getName();

		String name = whereClauseEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			whereClauseEntryCacheModel.name = null;
		}

		whereClauseEntryCacheModel.nickname = getNickname();

		String nickname = whereClauseEntryCacheModel.nickname;

		if ((nickname != null) && (nickname.length() == 0)) {
			whereClauseEntryCacheModel.nickname = null;
		}

		return whereClauseEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WhereClauseEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WhereClauseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WhereClauseEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(WhereClauseEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WhereClauseEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WhereClauseEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WhereClauseEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WhereClauseEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WhereClauseEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _whereClauseEntryId;
	private String _name;
	private String _originalName;
	private String _nickname;
	private long _columnBitmask;
	private WhereClauseEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1037134604