#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/portal-tools-rest-builder-test
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Portal.Tools.REST.Builder.Test)
osgi.jaxrs.resource=true