/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.CacheReplicatorEntry;
import com.liferay.portal.tools.service.builder.test.model.CacheReplicatorEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CacheReplicatorEntry service. Represents a row in the &quot;CacheReplicatorEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CacheReplicatorEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CacheReplicatorEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CacheReplicatorEntryImpl
 * @generated
 */
public class CacheReplicatorEntryModelImpl
	extends BaseModelImpl<CacheReplicatorEntry>
	implements CacheReplicatorEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cache replicator entry model instance should use the <code>CacheReplicatorEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "CacheReplicatorEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"cacheReplicatorEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cacheReplicatorEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CacheReplicatorEntry (cacheReplicatorEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CacheReplicatorEntry";

	public static final String ENTITY_ALIAS = "cacheReplicatorEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cacheReplicatorEntry.cacheReplicatorEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CacheReplicatorEntry.cacheReplicatorEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CACHEREPLICATORENTRYID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.CacheReplicatorEntry"));

	public CacheReplicatorEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cacheReplicatorEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCacheReplicatorEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cacheReplicatorEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CacheReplicatorEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CacheReplicatorEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CacheReplicatorEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CacheReplicatorEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CacheReplicatorEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CacheReplicatorEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CacheReplicatorEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CacheReplicatorEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CacheReplicatorEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CacheReplicatorEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CacheReplicatorEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CacheReplicatorEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CacheReplicatorEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CacheReplicatorEntry, Object>>();

			attributeGetterFunctions.put(
				"cacheReplicatorEntryId",
				CacheReplicatorEntry::getCacheReplicatorEntryId);
			attributeGetterFunctions.put(
				"companyId", CacheReplicatorEntry::getCompanyId);
			attributeGetterFunctions.put("name", CacheReplicatorEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CacheReplicatorEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CacheReplicatorEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CacheReplicatorEntry, ?>>();

			attributeSetterBiConsumers.put(
				"cacheReplicatorEntryId",
				(BiConsumer<CacheReplicatorEntry, Long>)
					CacheReplicatorEntry::setCacheReplicatorEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CacheReplicatorEntry, Long>)
					CacheReplicatorEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<CacheReplicatorEntry, String>)
					CacheReplicatorEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getCacheReplicatorEntryId() {
		return _cacheReplicatorEntryId;
	}

	@Override
	public void setCacheReplicatorEntryId(long cacheReplicatorEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cacheReplicatorEntryId = cacheReplicatorEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CacheReplicatorEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CacheReplicatorEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CacheReplicatorEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CacheReplicatorEntryImpl cacheReplicatorEntryImpl =
			new CacheReplicatorEntryImpl();

		cacheReplicatorEntryImpl.setCacheReplicatorEntryId(
			getCacheReplicatorEntryId());
		cacheReplicatorEntryImpl.setCompanyId(getCompanyId());
		cacheReplicatorEntryImpl.setName(getName());

		cacheReplicatorEntryImpl.resetOriginalValues();

		return cacheReplicatorEntryImpl;
	}

	@Override
	public CacheReplicatorEntry cloneWithOriginalValues() {
		CacheReplicatorEntryImpl cacheReplicatorEntryImpl =
			new CacheReplicatorEntryImpl();

		cacheReplicatorEntryImpl.setCacheReplicatorEntryId(
			this.<Long>getColumnOriginalValue("cacheReplicatorEntryId"));
		cacheReplicatorEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cacheReplicatorEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return cacheReplicatorEntryImpl;
	}

	@Override
	public int compareTo(CacheReplicatorEntry cacheReplicatorEntry) {
		long primaryKey = cacheReplicatorEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CacheReplicatorEntry)) {
			return false;
		}

		CacheReplicatorEntry cacheReplicatorEntry =
			(CacheReplicatorEntry)object;

		long primaryKey = cacheReplicatorEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CacheReplicatorEntry> toCacheModel() {
		CacheReplicatorEntryCacheModel cacheReplicatorEntryCacheModel =
			new CacheReplicatorEntryCacheModel();

		cacheReplicatorEntryCacheModel.cacheReplicatorEntryId =
			getCacheReplicatorEntryId();

		cacheReplicatorEntryCacheModel.companyId = getCompanyId();

		cacheReplicatorEntryCacheModel.name = getName();

		String name = cacheReplicatorEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			cacheReplicatorEntryCacheModel.name = null;
		}

		return cacheReplicatorEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CacheReplicatorEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CacheReplicatorEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CacheReplicatorEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CacheReplicatorEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CacheReplicatorEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CacheReplicatorEntry.class, ModelWrapper.class);

	}

	private long _cacheReplicatorEntryId;
	private long _companyId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<CacheReplicatorEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CacheReplicatorEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"cacheReplicatorEntryId", _cacheReplicatorEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("cacheReplicatorEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CacheReplicatorEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1493559654