/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.DefinedDefaultOrderEntry;
import com.liferay.portal.tools.service.builder.test.model.DefinedDefaultOrderEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DefinedDefaultOrderEntry service. Represents a row in the &quot;DefinedDefaultOrderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DefinedDefaultOrderEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DefinedDefaultOrderEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DefinedDefaultOrderEntryImpl
 * @generated
 */
public class DefinedDefaultOrderEntryModelImpl
	extends BaseModelImpl<DefinedDefaultOrderEntry>
	implements DefinedDefaultOrderEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a defined default order entry model instance should use the <code>DefinedDefaultOrderEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DefinedDefaultOrderEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"definedDefaultOrderEntryId", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("definedDefaultOrderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DefinedDefaultOrderEntry (definedDefaultOrderEntryId LONG not null primary key,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table DefinedDefaultOrderEntry";

	public static final String ENTITY_ALIAS = "definedDefaultOrderEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY definedDefaultOrderEntry.modifiedDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DefinedDefaultOrderEntry.modifiedDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.DefinedDefaultOrderEntry"));

	public DefinedDefaultOrderEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _definedDefaultOrderEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDefinedDefaultOrderEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _definedDefaultOrderEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DefinedDefaultOrderEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DefinedDefaultOrderEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DefinedDefaultOrderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DefinedDefaultOrderEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DefinedDefaultOrderEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DefinedDefaultOrderEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DefinedDefaultOrderEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DefinedDefaultOrderEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DefinedDefaultOrderEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DefinedDefaultOrderEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DefinedDefaultOrderEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<DefinedDefaultOrderEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<DefinedDefaultOrderEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DefinedDefaultOrderEntry, Object>>();

			attributeGetterFunctions.put(
				"definedDefaultOrderEntryId",
				DefinedDefaultOrderEntry::getDefinedDefaultOrderEntryId);
			attributeGetterFunctions.put(
				"modifiedDate", DefinedDefaultOrderEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"name", DefinedDefaultOrderEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<DefinedDefaultOrderEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DefinedDefaultOrderEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DefinedDefaultOrderEntry, ?>>();

			attributeSetterBiConsumers.put(
				"definedDefaultOrderEntryId",
				(BiConsumer<DefinedDefaultOrderEntry, Long>)
					DefinedDefaultOrderEntry::setDefinedDefaultOrderEntryId);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DefinedDefaultOrderEntry, Date>)
					DefinedDefaultOrderEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<DefinedDefaultOrderEntry, String>)
					DefinedDefaultOrderEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getDefinedDefaultOrderEntryId() {
		return _definedDefaultOrderEntryId;
	}

	@Override
	public void setDefinedDefaultOrderEntryId(long definedDefaultOrderEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_definedDefaultOrderEntryId = definedDefaultOrderEntryId;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DefinedDefaultOrderEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DefinedDefaultOrderEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DefinedDefaultOrderEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DefinedDefaultOrderEntryImpl definedDefaultOrderEntryImpl =
			new DefinedDefaultOrderEntryImpl();

		definedDefaultOrderEntryImpl.setDefinedDefaultOrderEntryId(
			getDefinedDefaultOrderEntryId());
		definedDefaultOrderEntryImpl.setModifiedDate(getModifiedDate());
		definedDefaultOrderEntryImpl.setName(getName());

		definedDefaultOrderEntryImpl.resetOriginalValues();

		return definedDefaultOrderEntryImpl;
	}

	@Override
	public DefinedDefaultOrderEntry cloneWithOriginalValues() {
		DefinedDefaultOrderEntryImpl definedDefaultOrderEntryImpl =
			new DefinedDefaultOrderEntryImpl();

		definedDefaultOrderEntryImpl.setDefinedDefaultOrderEntryId(
			this.<Long>getColumnOriginalValue("definedDefaultOrderEntryId"));
		definedDefaultOrderEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		definedDefaultOrderEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return definedDefaultOrderEntryImpl;
	}

	@Override
	public int compareTo(DefinedDefaultOrderEntry definedDefaultOrderEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), definedDefaultOrderEntry.getModifiedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DefinedDefaultOrderEntry)) {
			return false;
		}

		DefinedDefaultOrderEntry definedDefaultOrderEntry =
			(DefinedDefaultOrderEntry)object;

		long primaryKey = definedDefaultOrderEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DefinedDefaultOrderEntry> toCacheModel() {
		DefinedDefaultOrderEntryCacheModel definedDefaultOrderEntryCacheModel =
			new DefinedDefaultOrderEntryCacheModel();

		definedDefaultOrderEntryCacheModel.definedDefaultOrderEntryId =
			getDefinedDefaultOrderEntryId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			definedDefaultOrderEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			definedDefaultOrderEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		definedDefaultOrderEntryCacheModel.name = getName();

		String name = definedDefaultOrderEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			definedDefaultOrderEntryCacheModel.name = null;
		}

		return definedDefaultOrderEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DefinedDefaultOrderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DefinedDefaultOrderEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DefinedDefaultOrderEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DefinedDefaultOrderEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, DefinedDefaultOrderEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						DefinedDefaultOrderEntry.class, ModelWrapper.class);

	}

	private long _definedDefaultOrderEntryId;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<DefinedDefaultOrderEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DefinedDefaultOrderEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"definedDefaultOrderEntryId", _definedDefaultOrderEntryId);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("definedDefaultOrderEntryId", 1L);

		columnBitmasks.put("modifiedDate", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DefinedDefaultOrderEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1184392687