/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.DynamicQueryEntry;
import com.liferay.portal.tools.service.builder.test.model.DynamicQueryEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DynamicQueryEntry service. Represents a row in the &quot;DynamicQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DynamicQueryEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DynamicQueryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DynamicQueryEntryImpl
 * @generated
 */
public class DynamicQueryEntryModelImpl
	extends BaseModelImpl<DynamicQueryEntry> implements DynamicQueryEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dynamic query entry model instance should use the <code>DynamicQueryEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DynamicQueryEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"dynamicQueryEntryId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"amount", Types.BIGINT},
		{"description", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dynamicQueryEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("amount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DynamicQueryEntry (dynamicQueryEntryId LONG not null primary key,createDate DATE null,modifiedDate DATE null,amount LONG,description VARCHAR(75) null,name VARCHAR(75) null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table DynamicQueryEntry";

	public static final String ENTITY_ALIAS = "dynamicQueryEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dynamicQueryEntry.dynamicQueryEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DynamicQueryEntry.dynamicQueryEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DYNAMICQUERYENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.DynamicQueryEntry"));

	public DynamicQueryEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dynamicQueryEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDynamicQueryEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dynamicQueryEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DynamicQueryEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DynamicQueryEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DynamicQueryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DynamicQueryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DynamicQueryEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DynamicQueryEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DynamicQueryEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DynamicQueryEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DynamicQueryEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DynamicQueryEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DynamicQueryEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DynamicQueryEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DynamicQueryEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DynamicQueryEntry, Object>>();

			attributeGetterFunctions.put(
				"dynamicQueryEntryId",
				DynamicQueryEntry::getDynamicQueryEntryId);
			attributeGetterFunctions.put(
				"createDate", DynamicQueryEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DynamicQueryEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"amount", DynamicQueryEntry::getAmount);
			attributeGetterFunctions.put(
				"description", DynamicQueryEntry::getDescription);
			attributeGetterFunctions.put("name", DynamicQueryEntry::getName);
			attributeGetterFunctions.put(
				"status", DynamicQueryEntry::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DynamicQueryEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DynamicQueryEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DynamicQueryEntry, ?>>();

			attributeSetterBiConsumers.put(
				"dynamicQueryEntryId",
				(BiConsumer<DynamicQueryEntry, Long>)
					DynamicQueryEntry::setDynamicQueryEntryId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DynamicQueryEntry, Date>)
					DynamicQueryEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DynamicQueryEntry, Date>)
					DynamicQueryEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"amount",
				(BiConsumer<DynamicQueryEntry, Long>)
					DynamicQueryEntry::setAmount);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<DynamicQueryEntry, String>)
					DynamicQueryEntry::setDescription);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<DynamicQueryEntry, String>)
					DynamicQueryEntry::setName);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<DynamicQueryEntry, Integer>)
					DynamicQueryEntry::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getDynamicQueryEntryId() {
		return _dynamicQueryEntryId;
	}

	@Override
	public void setDynamicQueryEntryId(long dynamicQueryEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dynamicQueryEntryId = dynamicQueryEntryId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(long amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DynamicQueryEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DynamicQueryEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DynamicQueryEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DynamicQueryEntryImpl dynamicQueryEntryImpl =
			new DynamicQueryEntryImpl();

		dynamicQueryEntryImpl.setDynamicQueryEntryId(getDynamicQueryEntryId());
		dynamicQueryEntryImpl.setCreateDate(getCreateDate());
		dynamicQueryEntryImpl.setModifiedDate(getModifiedDate());
		dynamicQueryEntryImpl.setAmount(getAmount());
		dynamicQueryEntryImpl.setDescription(getDescription());
		dynamicQueryEntryImpl.setName(getName());
		dynamicQueryEntryImpl.setStatus(getStatus());

		dynamicQueryEntryImpl.resetOriginalValues();

		return dynamicQueryEntryImpl;
	}

	@Override
	public DynamicQueryEntry cloneWithOriginalValues() {
		DynamicQueryEntryImpl dynamicQueryEntryImpl =
			new DynamicQueryEntryImpl();

		dynamicQueryEntryImpl.setDynamicQueryEntryId(
			this.<Long>getColumnOriginalValue("dynamicQueryEntryId"));
		dynamicQueryEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dynamicQueryEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dynamicQueryEntryImpl.setAmount(
			this.<Long>getColumnOriginalValue("amount"));
		dynamicQueryEntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		dynamicQueryEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		dynamicQueryEntryImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));

		return dynamicQueryEntryImpl;
	}

	@Override
	public int compareTo(DynamicQueryEntry dynamicQueryEntry) {
		long primaryKey = dynamicQueryEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DynamicQueryEntry)) {
			return false;
		}

		DynamicQueryEntry dynamicQueryEntry = (DynamicQueryEntry)object;

		long primaryKey = dynamicQueryEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DynamicQueryEntry> toCacheModel() {
		DynamicQueryEntryCacheModel dynamicQueryEntryCacheModel =
			new DynamicQueryEntryCacheModel();

		dynamicQueryEntryCacheModel.dynamicQueryEntryId =
			getDynamicQueryEntryId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dynamicQueryEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			dynamicQueryEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dynamicQueryEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dynamicQueryEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dynamicQueryEntryCacheModel.amount = getAmount();

		dynamicQueryEntryCacheModel.description = getDescription();

		String description = dynamicQueryEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			dynamicQueryEntryCacheModel.description = null;
		}

		dynamicQueryEntryCacheModel.name = getName();

		String name = dynamicQueryEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dynamicQueryEntryCacheModel.name = null;
		}

		dynamicQueryEntryCacheModel.status = getStatus();

		return dynamicQueryEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DynamicQueryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DynamicQueryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DynamicQueryEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DynamicQueryEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DynamicQueryEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DynamicQueryEntry.class, ModelWrapper.class);

	}

	private long _dynamicQueryEntryId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _amount;
	private String _description;
	private String _name;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		Function<DynamicQueryEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DynamicQueryEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("dynamicQueryEntryId", _dynamicQueryEntryId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("dynamicQueryEntryId", 1L);

		columnBitmasks.put("createDate", 2L);

		columnBitmasks.put("modifiedDate", 4L);

		columnBitmasks.put("amount", 8L);

		columnBitmasks.put("description", 16L);

		columnBitmasks.put("name", 32L);

		columnBitmasks.put("status", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DynamicQueryEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1313578954