/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.UndefinedDefaultOrderEntry;
import com.liferay.portal.tools.service.builder.test.model.UndefinedDefaultOrderEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UndefinedDefaultOrderEntry service. Represents a row in the &quot;UndefinedDefaultOrderEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UndefinedDefaultOrderEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UndefinedDefaultOrderEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UndefinedDefaultOrderEntryImpl
 * @generated
 */
public class UndefinedDefaultOrderEntryModelImpl
	extends BaseModelImpl<UndefinedDefaultOrderEntry>
	implements UndefinedDefaultOrderEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a undefined default order entry model instance should use the <code>UndefinedDefaultOrderEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "UndefinedDefaultOrderEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"undefinedDefaultOrderEntryId", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("undefinedDefaultOrderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UndefinedDefaultOrderEntry (undefinedDefaultOrderEntryId LONG not null primary key,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table UndefinedDefaultOrderEntry";

	public static final String ENTITY_ALIAS = "undefinedDefaultOrderEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY undefinedDefaultOrderEntry.undefinedDefaultOrderEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY UndefinedDefaultOrderEntry.undefinedDefaultOrderEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UNDEFINEDDEFAULTORDERENTRYID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.UndefinedDefaultOrderEntry"));

	public UndefinedDefaultOrderEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _undefinedDefaultOrderEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUndefinedDefaultOrderEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _undefinedDefaultOrderEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UndefinedDefaultOrderEntry.class;
	}

	@Override
	public String getModelClassName() {
		return UndefinedDefaultOrderEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UndefinedDefaultOrderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UndefinedDefaultOrderEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UndefinedDefaultOrderEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(UndefinedDefaultOrderEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UndefinedDefaultOrderEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UndefinedDefaultOrderEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UndefinedDefaultOrderEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UndefinedDefaultOrderEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UndefinedDefaultOrderEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<UndefinedDefaultOrderEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<UndefinedDefaultOrderEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<UndefinedDefaultOrderEntry, Object>>();

			attributeGetterFunctions.put(
				"undefinedDefaultOrderEntryId",
				UndefinedDefaultOrderEntry::getUndefinedDefaultOrderEntryId);
			attributeGetterFunctions.put(
				"modifiedDate", UndefinedDefaultOrderEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"name", UndefinedDefaultOrderEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<UndefinedDefaultOrderEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UndefinedDefaultOrderEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<UndefinedDefaultOrderEntry, ?>>();

			attributeSetterBiConsumers.put(
				"undefinedDefaultOrderEntryId",
				(BiConsumer<UndefinedDefaultOrderEntry, Long>)
					UndefinedDefaultOrderEntry::
						setUndefinedDefaultOrderEntryId);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<UndefinedDefaultOrderEntry, Date>)
					UndefinedDefaultOrderEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<UndefinedDefaultOrderEntry, String>)
					UndefinedDefaultOrderEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getUndefinedDefaultOrderEntryId() {
		return _undefinedDefaultOrderEntryId;
	}

	@Override
	public void setUndefinedDefaultOrderEntryId(
		long undefinedDefaultOrderEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_undefinedDefaultOrderEntryId = undefinedDefaultOrderEntryId;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, UndefinedDefaultOrderEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UndefinedDefaultOrderEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UndefinedDefaultOrderEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UndefinedDefaultOrderEntryImpl undefinedDefaultOrderEntryImpl =
			new UndefinedDefaultOrderEntryImpl();

		undefinedDefaultOrderEntryImpl.setUndefinedDefaultOrderEntryId(
			getUndefinedDefaultOrderEntryId());
		undefinedDefaultOrderEntryImpl.setModifiedDate(getModifiedDate());
		undefinedDefaultOrderEntryImpl.setName(getName());

		undefinedDefaultOrderEntryImpl.resetOriginalValues();

		return undefinedDefaultOrderEntryImpl;
	}

	@Override
	public UndefinedDefaultOrderEntry cloneWithOriginalValues() {
		UndefinedDefaultOrderEntryImpl undefinedDefaultOrderEntryImpl =
			new UndefinedDefaultOrderEntryImpl();

		undefinedDefaultOrderEntryImpl.setUndefinedDefaultOrderEntryId(
			this.<Long>getColumnOriginalValue("undefinedDefaultOrderEntryId"));
		undefinedDefaultOrderEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		undefinedDefaultOrderEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return undefinedDefaultOrderEntryImpl;
	}

	@Override
	public int compareTo(
		UndefinedDefaultOrderEntry undefinedDefaultOrderEntry) {

		long primaryKey = undefinedDefaultOrderEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UndefinedDefaultOrderEntry)) {
			return false;
		}

		UndefinedDefaultOrderEntry undefinedDefaultOrderEntry =
			(UndefinedDefaultOrderEntry)object;

		long primaryKey = undefinedDefaultOrderEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UndefinedDefaultOrderEntry> toCacheModel() {
		UndefinedDefaultOrderEntryCacheModel
			undefinedDefaultOrderEntryCacheModel =
				new UndefinedDefaultOrderEntryCacheModel();

		undefinedDefaultOrderEntryCacheModel.undefinedDefaultOrderEntryId =
			getUndefinedDefaultOrderEntryId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			undefinedDefaultOrderEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			undefinedDefaultOrderEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		undefinedDefaultOrderEntryCacheModel.name = getName();

		String name = undefinedDefaultOrderEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			undefinedDefaultOrderEntryCacheModel.name = null;
		}

		return undefinedDefaultOrderEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UndefinedDefaultOrderEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UndefinedDefaultOrderEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UndefinedDefaultOrderEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UndefinedDefaultOrderEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, UndefinedDefaultOrderEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						UndefinedDefaultOrderEntry.class, ModelWrapper.class);

	}

	private long _undefinedDefaultOrderEntryId;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<UndefinedDefaultOrderEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UndefinedDefaultOrderEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"undefinedDefaultOrderEntryId", _undefinedDefaultOrderEntryId);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("undefinedDefaultOrderEntryId", 1L);

		columnBitmasks.put("modifiedDate", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UndefinedDefaultOrderEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:292341681