resource "helm_release" "argocd" {
	chart="argo-cd"
	create_namespace=false
	depends_on=[
		kubernetes_namespace.argocd,
		kubernetes_secret.argocd_secret,
	]
	name="argocd"
	namespace=var.argocd_namespace
	repository="https://argoproj.github.io/argo-helm"
	values=[
		yamlencode(
			{
				applicationSet={
					resources={
						limits={
							memory="768Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				configs={
					cm={
						"application.resourceTrackingMethod"="annotation"
						"controller.diff.timeout"="120s"
						"kustomize.buildOptions"="--enable-helm"
						"resource.customizations.health.gcp.liferay.com_LiferayInfrastructure"=file("${path.module}/health-gcp.liferay.com_LiferayInfrastructure.lua")
						"resource.customizations.ignoreDifferences.all"=yamlencode(
							{
								jsonPointers=["/metadata/labels/apiextensions.crossplane.io~1composite"]
								managedFieldsManagers=[
									"apiextensions.crossplane.io/composite",
									"crossplane",
									"kube-controller-manager",
								]
							})
						"resource.customizations.ignoreDifferences.gcp.liferay.com_LiferayInfrastructure"=yamlencode(
							{
								jsonPointers=[
									"/spec/restorePhase",
									"/spec/targetActiveDataPlane",
									"/status/atProvider",
									"/status/internalMetadata",
								]
							})
						"resource.exclusions"=yamlencode(
							[
								{
									apiGroups=["*"]
									kinds=["ProviderConfigUsage"]
								},
								{
									apiGroups=["apiextensions.crossplane.io"]
									kinds=["ManagedResourceDefinition"]
								},
							])
					}
					params={
						"server.insecure"="true"
					}
				}
				controller={
					resources={
						limits={
							memory="8Gi"
						}
						requests={
							cpu="109m"
							memory="1.5Gi"
						}
					}
				}
				dex={
					resources={
						limits={
							memory="768Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				installCRDs=true
				notifications={
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				redis={
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				repoServer={
					livenessProbe={
						failureThreshold=6
						periodSeconds=15
						timeoutSeconds=10
					}
					readinessProbe={
						periodSeconds=15
						timeoutSeconds=10
					}
					resources={
						limits={
							memory="1.5Gi"
						}
						requests={
							cpu="250m"
							memory="128Mi"
						}
					}
				}
				server={
					livenessProbe={
						initialDelaySeconds=90
						timeoutSeconds=5
					}
					readinessProbe={
						initialDelaySeconds=60
						timeoutSeconds=5
					}
					resources={
						limits={
							memory="768Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
					service={
						type="ClusterIP"
					}
				}
			}),
	]
	version=var.argocd_helm_chart_version
	wait=true
}
resource "kubernetes_namespace" "argocd" {
	metadata {
		labels=local.common_labels
		name=var.argocd_namespace
	}
}
resource "kubernetes_secret" "argocd_secret" {
	data={
		"server.secretkey"=random_password.argocd_server_secretkey.result
	}
	lifecycle {
		ignore_changes=[
			data,
			metadata[0].labels,
		]
	}
	metadata {
		annotations={
			"meta.helm.sh/release-name"="argocd"
			"meta.helm.sh/release-namespace"=var.argocd_namespace
		}
		labels=merge(
			local.common_labels,
			{
				"app.kubernetes.io/managed-by"="Helm"
			})
		name="argocd-secret"
		namespace=var.argocd_namespace
	}
	type="Opaque"
}
resource "random_password" "argocd_server_secretkey" {
	length=32
	special=false
}