apiVersion: batch/v1
kind: Job
metadata:
    generateName: aihub-crawler-
    labels:
        app: aihub-crawler
spec:
    backoffLimit: 1
    template:
        metadata:
            labels:
                app: aihub-crawler
        spec:
            containers:
                -   image: placeholder
                    name: crawler
                    resources:
                        limits:
                            cpu: "2"
                            memory: 4Gi
                        requests:
                            cpu: "1"
                            memory: 2Gi
                    securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                            drop:
                                -   ALL
            restartPolicy: Never
            securityContext:
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                    type: RuntimeDefault
    ttlSecondsAfterFinished: 86400