defaults:
    run:
        shell: bash
jobs:
    promote:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            -   id: auth_nonproduction
                name: Authenticate to Google Cloud (Non-production)
                uses: google-github-actions/auth@v3
                with:
                    project_id: ${{vars.GCP_PROJECT_ID_EXTERNAL_NONPRODUCTION}}
                    workload_identity_provider: ${{vars.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRODUCTION}}
            -   id: auth_production
                name: Authenticate to Google Cloud (Production)
                uses: google-github-actions/auth@v3
                with:
                    project_id: ${{vars.GCP_PROJECT_ID_EXTERNAL_PRODUCTION}}
                    workload_identity_provider: ${{vars.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_PRODUCTION}}
            -   name: Install ORAS
                uses: oras-project/setup-oras@v1
            -   env:
                    HELM_CHART_REGISTRY_PRODUCTION: ${{vars.HELM_CHART_REGISTRY_PRODUCTION}}
                name: Promote Helm chart
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        oras cp \
                            --from-password "${{steps.auth_nonproduction.outputs.auth_token}}" \
                            --from-username oauth2accesstoken \
                            --to-password "${{steps.auth_production.outputs.auth_token}}" \
                            --to-username oauth2accesstoken \
                            "${{inputs.source_image_ref}}" \
                            "${HELM_CHART_REGISTRY_PRODUCTION}/${{inputs.chart_name}}:${{inputs.chart_version}}"
                    }

                    main "${@}"
on:
    workflow_call:
        inputs:
            chart_name:
                required: true
                type: string
            chart_version:
                required: true
                type: string
            source_image_ref:
                required: true
                type: string
permissions:
    contents: read
    id-token: write