defaults:
    run:
        shell: bash
jobs:
    test-cloud-terraform:
        if: ${{(github.event_name == 'pull_request' && github.repository == 'cloudnative-team/liferay-portal') || (github.event_name == 'push' && github.repository == 'liferay/liferay-portal')}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Terraform
                uses: hashicorp/setup-terraform@v3
                with:
                    terraform_version: 1.10.0
            -   name: Set up TFLint
                uses: terraform-linters/setup-tflint@v4
                with:
                    github_token: ${{secrets.GITHUB_TOKEN}}
            -   name: Initialize Terraform
                run: terraform init -backend=false -input=false
                working-directory: ./cloud/terraform/${{matrix.stack}}
            -   name: Validate Terraform
                run: terraform validate
                working-directory: ./cloud/terraform/${{matrix.stack}}
            -   name: Run TFLint
                run: |
                    function main {
                        local cloud="${{matrix.stack}}"

                        cloud="${cloud%%/*}"

                        local config="${GITHUB_WORKSPACE}/cloud/terraform/${cloud}/.tflint.hcl"

                        tflint --config="${config}" --init

                        tflint --config="${config}"
                    }

                    main
                working-directory: ./cloud/terraform/${{matrix.stack}}
            -   name: Run Checkov
                uses: bridgecrewio/checkov-action@v12
                with:
                    directory: ./cloud/terraform/${{matrix.stack}}
                    framework: terraform
                    soft_fail: false
        strategy:
            fail-fast: false
            matrix:
                stack:
                    -   aws/dependencies
                    -   aws/ecr
                    -   aws/eks
                    -   aws/gitops/platform
                    -   aws/gitops/resources
                    -   gcp/gitops/platform
                    -   gcp/gitops/resources
                    -   gcp/gke
on:
    pull_request:
        paths:
            -   .github/workflows/ci-test-cloud-terraform.yaml
            -   cloud/terraform/**
    push:
        branches:
            -   master
        paths:
            -   .github/workflows/ci-test-cloud-terraform.yaml
            -   cloud/terraform/**