/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.compat740.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.compat740.model.MappingEntry;
import com.liferay.portal.tools.service.builder.test.compat740.model.MappingEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MappingEntry service. Represents a row in the &quot;MappingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MappingEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MappingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MappingEntryImpl
 * @generated
 */
public class MappingEntryModelImpl
	extends BaseModelImpl<MappingEntry> implements MappingEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mapping entry model instance should use the <code>MappingEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "MappingEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mappingEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mappingEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MappingEntry (mappingEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MappingEntry";

	public static final String ENTITY_ALIAS = "mappingEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mappingEntry.mappingEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MappingEntry.mappingEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MAPPINGENTRYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public static final String MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_NAME =
		"MappingEntries_BasicEntries";

	public static final Object[][]
		MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"basicEntryId", Types.BIGINT},
			{"mappingEntryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_MAPPINGENTRIES_BASICENTRIES_SQL_CREATE =
			"create table MappingEntries_BasicEntries (companyId LONG not null,basicEntryId LONG not null,mappingEntryId LONG not null,primary key (basicEntryId, mappingEntryId))";

	public MappingEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mappingEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMappingEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mappingEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MappingEntry.class;
	}

	@Override
	public String getModelClassName() {
		return MappingEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MappingEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MappingEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MappingEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MappingEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MappingEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MappingEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MappingEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MappingEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<MappingEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<MappingEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<MappingEntry, Object>>();

			attributeGetterFunctions.put(
				"mappingEntryId", MappingEntry::getMappingEntryId);
			attributeGetterFunctions.put(
				"companyId", MappingEntry::getCompanyId);
			attributeGetterFunctions.put("name", MappingEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<MappingEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<MappingEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<MappingEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mappingEntryId",
				(BiConsumer<MappingEntry, Long>)
					MappingEntry::setMappingEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<MappingEntry, Long>)MappingEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<MappingEntry, String>)MappingEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMappingEntryId() {
		return _mappingEntryId;
	}

	@Override
	public void setMappingEntryId(long mappingEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mappingEntryId = mappingEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MappingEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MappingEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MappingEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MappingEntryImpl mappingEntryImpl = new MappingEntryImpl();

		mappingEntryImpl.setMappingEntryId(getMappingEntryId());
		mappingEntryImpl.setCompanyId(getCompanyId());
		mappingEntryImpl.setName(getName());

		mappingEntryImpl.resetOriginalValues();

		return mappingEntryImpl;
	}

	@Override
	public MappingEntry cloneWithOriginalValues() {
		MappingEntryImpl mappingEntryImpl = new MappingEntryImpl();

		mappingEntryImpl.setMappingEntryId(
			this.<Long>getColumnOriginalValue("mappingEntryId"));
		mappingEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		mappingEntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return mappingEntryImpl;
	}

	@Override
	public int compareTo(MappingEntry mappingEntry) {
		long primaryKey = mappingEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MappingEntry)) {
			return false;
		}

		MappingEntry mappingEntry = (MappingEntry)object;

		long primaryKey = mappingEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MappingEntry> toCacheModel() {
		MappingEntryCacheModel mappingEntryCacheModel =
			new MappingEntryCacheModel();

		mappingEntryCacheModel.mappingEntryId = getMappingEntryId();

		mappingEntryCacheModel.companyId = getCompanyId();

		mappingEntryCacheModel.name = getName();

		String name = mappingEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mappingEntryCacheModel.name = null;
		}

		return mappingEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MappingEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MappingEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MappingEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MappingEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MappingEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MappingEntry.class, ModelWrapper.class);

	}

	private long _mappingEntryId;
	private long _companyId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<MappingEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MappingEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mappingEntryId", _mappingEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mappingEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MappingEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1890895674